//! Tests generated by same-file `macro_rules!` invocations (#5334).
//!
//! `syntax::expand_local_test_macros` expands the bounded shape it
//! documents; this pass parses each expansion with the ordinary file-fact
//! producer and registers the `#[test]` functions it yields as `TestFact`s
//! of the invoking file. Every fact line is pinned to the invocation, so
//! readers that locate a test or its calls by line point at the source the
//! user wrote. Invocations the expander refuses register nothing.

use super::{RustIndex, TestFact};
use crate::analysis::syntax::expand_local_test_macros;
use crate::analysis::syntax::ra::summarize_file_with_parser;
use std::collections::BTreeSet;
use std::path::PathBuf;

pub(super) fn register_macro_generated_tests(index: &mut RustIndex) {
    let mut generated: Vec<TestFact> = Vec::new();
    for (path, file) in &index.files {
        for expansion in expand_local_test_macros(&file.data.source) {
            let Ok(facts) = summarize_file_with_parser(path, &expansion.text) else {
                continue;
            };
            // The same exact attribute-path rule the style normalizer
            // applies to hand-written tests; the parser's own check is a
            // prefix match.
            for mut test in facts.tests.into_iter().filter(|test| {
                super::test_styles::attributes_define_test(test.attrs.iter().map(String::as_str))
            }) {
                pin_to_invocation(&mut test, path, expansion.start_line, expansion.end_line);
                generated.push(test);
            }
        }
    }
    if generated.is_empty() {
        return;
    }
    let mut known: BTreeSet<(PathBuf, usize, String)> = index
        .tests()
        .iter()
        .map(|test| (test.file.clone(), test.start_line, test.name.clone()))
        .collect();
    for test in generated {
        if !known.insert((test.file.clone(), test.start_line, test.name.clone())) {
            continue;
        }
        let file_path = test.file.clone();
        let id = index.test_facts.allocate(test);
        index.test_order.push(id);
        if let Some(file) = index.files.get_mut(&file_path) {
            file.tests.push(id);
            file.tests.sort_by(|&left, &right| {
                let left = &index.test_facts[left];
                let right = &index.test_facts[right];
                left.start_line
                    .cmp(&right.start_line)
                    .then(left.end_line.cmp(&right.end_line))
                    .then(left.name.cmp(&right.name))
            });
        }
    }
}

fn pin_to_invocation(test: &mut TestFact, path: &std::path::Path, start: usize, end: usize) {
    test.file = path.to_path_buf();
    test.start_line = start;
    test.end_line = end;
    for call in &mut test.calls {
        call.line = start;
    }
    for assertion in &mut test.assertions {
        assertion.line = start;
    }
    for literal in &mut test.literals {
        literal.line = start;
    }
    // Shadow lines are body-relative. Every call now sits on the body's
    // first line, so a `let` anywhere in the body shadows from there: the
    // conservative reading, which drops a call rather than keeps one.
    for binding in &mut test.let_bindings {
        binding.line = 0;
    }
}

#[cfg(test)]
mod tests {
    use super::super::build_index;
    use std::error::Error;
    use std::fs;
    use std::path::PathBuf;
    use std::time::{SystemTime, UNIX_EPOCH};

    struct TempDir(PathBuf);

    impl Drop for TempDir {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    fn temp_dir(name: &str) -> Result<TempDir, Box<dyn Error>> {
        let stamp = SystemTime::now().duration_since(UNIX_EPOCH)?.as_nanos();
        let root = std::env::temp_dir().join(format!("ripr-{name}-{stamp}"));
        fs::create_dir_all(&root)?;
        Ok(TempDir(root))
    }

    #[test]
    fn macro_generated_tests_are_indexed_at_their_invocations() -> Result<(), Box<dyn Error>> {
        let dir = temp_dir("macro-generated-tests")?;
        let root = dir.0.as_path();
        fs::create_dir_all(root.join("src"))?;
        fs::create_dir_all(root.join("tests"))?;
        fs::write(
            root.join("Cargo.toml"),
            "[package]\nname = \"macrocase\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
        )?;
        fs::write(
            root.join("src/lib.rs"),
            "pub fn is_adult(age: u32) -> bool {\n    age >= 18\n}\n",
        )?;
        fs::write(
            root.join("tests/gen.rs"),
            "macro_rules! age_case {\n    ($name:ident, $age:expr, $want:expr) => {\n        #[test]\n        fn $name() {\n            assert_eq!(macrocase::is_adult($age), $want);\n        }\n    };\n}\n\nage_case!(seventeen_is_minor, 17, false);\nage_case!(eighteen_is_adult, 18, true);\n",
        )?;
        let index = build_index(
            root,
            &[PathBuf::from("src/lib.rs"), PathBuf::from("tests/gen.rs")],
        )?;
        let tests: Vec<_> = index
            .tests()
            .iter()
            .map(|test| {
                (
                    test.name.clone(),
                    test.start_line,
                    test.calls.iter().any(|call| call.name == "is_adult"),
                    test.assertions.len(),
                )
            })
            .collect();
        assert_eq!(
            tests,
            vec![
                ("seventeen_is_minor".to_string(), 10, true, 1),
                ("eighteen_is_adult".to_string(), 11, true, 1),
            ]
        );
        Ok(())
    }
}
