//! Owner-return pins (#4478): an `assert_eq!` whose operand is a call of
//! the changed owner pins the owner's whole return value, so it observes a
//! changed `return_value` expression without sharing a token with it.
//!
//! Crediting that assertion is only sound when three facts hold, and each
//! gate below fails closed when ripr cannot establish one:
//!
//! 1. The call names the owner. A bare `name(..)` names a module-level
//!    function, never an associated function or a trait method. A method
//!    call `recv.name(..)` names a function with a `self` receiver, and only
//!    when the receiver's type dispatches to the owner: the test binds the
//!    receiver to a type ripr can read, that type reaches the owner's `impl`
//!    or trait, and no other definition of `name` in the workspace could
//!    take the call instead.
//! 2. The call's return value came through the changed expression. The
//!    changed expression must be the owner's tail. When the owner has other
//!    exits (`?`, `return`), the changed expression must be the owner's only
//!    `Ok(..)` (or `Some(..)`) constructor and the pinned value must be that
//!    constructor too: an `Err(..)` pin observes an early exit that never
//!    evaluates the changed `Ok(..)`.
//! 3. The pinned value is the whole return value: `assert_eq!` with the call
//!    as a complete operand, nothing chained after it. `assert_ne!` pins
//!    nothing.
//!
//! This is bounded syntax, not name resolution. The documented residuals:
//! methods generated by derive or attribute macros are invisible, a
//! `macro_rules!` body that defines the method counts only when ripr can
//! read its `fn` text, and an out-of-workspace trait in scope that also
//! names the method is not detected.

use super::super::rust_index::{FunctionSummary, OracleFact, RustIndex, TestSummary};
use super::reveal::{
    assertion_comparison_operands, contains_as_whole_word, file_imports_foreign_callee_name,
    file_imports_own_item,
};
use crate::analysis::extract::{
    fact_body_defines_callee_fn, fact_body_let_shadow_line, mask_comments_and_strings,
    test_body_defines_callee_fn, test_body_let_shadow_line,
};
use crate::analysis::facts::FunctionContainer;
use crate::domain::{Probe, ProbeFamily};
use std::path::PathBuf;

/// The owner-side half of the pin, established once per probe.
pub(in crate::analysis) struct OwnerReturnPin {
    name: String,
    call: PinCall,
    path: ReturnPathGate,
}

enum PinCall {
    /// `name(..)`: the owner is a module-level function.
    Bare,
    /// `recv.name(..)`: the receiver's type must be one of `receivers`, and
    /// a trait method also needs its trait in the test's scope.
    Method {
        receivers: Vec<ReceiverType>,
        trait_scope: Option<TraitScope>,
    },
}

/// A trait method is callable with method syntax only while its trait is
/// in scope.
struct TraitScope {
    trait_name: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
enum ReceiverType {
    /// A struct, enum or union declared in the workspace.
    Named(String),
    /// `&[u8]`, read from `&[..][..]` or `&b".."[..]`.
    ByteSlice,
}

enum ReturnPathGate {
    /// The changed expression is the owner's only exit.
    Any,
    /// The pinned value must start with this constructor.
    Head(&'static str),
}

impl OwnerReturnPin {
    /// The owner-side gates: `None` when the probe is not a return value,
    /// the owner's declaration or return paths are not established, or
    /// another workspace definition could take a call by the owner's name.
    pub(in crate::analysis) fn establish(
        probe: &Probe,
        owner: &FunctionSummary,
        index: &RustIndex,
    ) -> Option<Self> {
        if !matches!(probe.family, ProbeFamily::ReturnValue) || !owner.item.has_body {
            return None;
        }
        let parser_backed = index
            .files
            .get(&owner.file)
            .is_some_and(|facts| !facts.used_lexical_fallback);
        if !parser_backed {
            return None;
        }
        let name = owner.name.as_str();
        let changed_line = probe.location.line.checked_sub(owner.start_line)?;
        let path = return_path_gate(&owner.body, &probe.expression, changed_line)?;
        let call = match (&owner.item.container, owner.item.has_self_param) {
            (FunctionContainer::Free, false) => PinCall::Bare,
            (FunctionContainer::Inherent { self_ty }, true) => PinCall::Method {
                receivers: vec![declared_receiver(self_ty, index)?],
                trait_scope: None,
            },
            (
                FunctionContainer::TraitImpl {
                    trait_path,
                    self_ty,
                },
                true,
            ) => PinCall::Method {
                receivers: vec![declared_receiver(self_ty, index)?],
                trait_scope: Some(TraitScope {
                    trait_name: path_base_name(trait_path)?.to_string(),
                }),
            },
            (FunctionContainer::Trait { trait_name }, true) => {
                let receivers = trait_impl_receivers(trait_name, index);
                if receivers.is_empty() {
                    return None;
                }
                PinCall::Method {
                    receivers,
                    trait_scope: Some(TraitScope {
                        trait_name: trait_name.clone(),
                    }),
                }
            }
            _ => return None,
        };
        let method = matches!(call, PinCall::Method { .. });
        if other_definition_competes(owner, index, method) {
            return None;
        }
        Some(Self {
            name: name.to_string(),
            call,
            path,
        })
    }

    /// The test-side gates: whether `assertion` in `test` pins the owner's
    /// return value through a call that names the owner.
    pub(in crate::analysis) fn admits(
        &self,
        test: &TestSummary,
        assertion: &OracleFact,
        index: &RustIndex,
    ) -> bool {
        if assertion.text.contains("assert_ne!") {
            return false;
        }
        let Some(operands) = assertion_comparison_operands(&assertion.text) else {
            return false;
        };
        let (call, expected) = match (
            owner_call_shape(operands[0], &self.name),
            owner_call_shape(operands[1], &self.name),
        ) {
            (Some(call), None) => (call, operands[1]),
            (None, Some(call)) => (call, operands[0]),
            _ => return false,
        };
        if !self.path.admits(expected) {
            return false;
        }
        match (&self.call, call) {
            (PinCall::Bare, CallShape::Bare) => !test_body_shadows_owner(test, &self.name),
            (
                PinCall::Method {
                    receivers,
                    trait_scope,
                },
                CallShape::Method(receiver),
            ) => {
                let test_source = index
                    .files
                    .get(&test.file)
                    .map(|facts| facts.source.as_str());
                let Some(receiver_type) = test_receiver_type(test, receiver, test_source, index)
                else {
                    return false;
                };
                receivers.contains(&receiver_type)
                    && (receiver_type != ReceiverType::ByteSlice
                        || !BYTE_SLICE_METHODS.contains(&self.name.as_str()))
                    && trait_scope.as_ref().is_none_or(|scope| {
                        test_source
                            .is_some_and(|source| trait_in_scope(source, &scope.trait_name, index))
                    })
            }
            _ => false,
        }
    }
}

impl ReturnPathGate {
    fn admits(&self, expected: &str) -> bool {
        match self {
            Self::Any => true,
            Self::Head(head) => constructor_call_span(expected.trim(), head).is_some(),
        }
    }
}

#[derive(Clone, Copy)]
enum CallShape<'a> {
    Bare,
    Method(&'a str),
}

/// The operand as a complete call of `name`: `name(..)` or `recv.name(..)`
/// with a plain identifier receiver and nothing chained after the call.
fn owner_call_shape<'a>(operand: &'a str, name: &str) -> Option<CallShape<'a>> {
    let operand = operand.trim();
    let call_start = if operand.starts_with(name) {
        0
    } else {
        let dot = operand.find('.')?;
        let receiver = &operand[..dot];
        if !is_plain_identifier(receiver) || receiver == "self" {
            return None;
        }
        if !operand[dot + 1..].starts_with(name) {
            return None;
        }
        dot + 1
    };
    let after_name = &operand[call_start + name.len()..];
    if !after_name.starts_with('(') {
        return None;
    }
    let masked = mask_comments_and_strings(operand);
    let opening = call_start + name.len();
    let closing = matching_close(&masked, opening, b'(', b')')?;
    if !operand[closing + 1..].trim().is_empty() {
        return None;
    }
    Some(if call_start == 0 {
        CallShape::Bare
    } else {
        CallShape::Method(&operand[..call_start - 1])
    })
}

/// The span of `head(..)` when `text` is exactly one `head(..)` call.
fn constructor_call_span(text: &str, head: &str) -> Option<usize> {
    let rest = text.strip_prefix(head)?;
    if !rest.starts_with('(') {
        return None;
    }
    let masked = mask_comments_and_strings(text);
    let closing = matching_close(&masked, head.len(), b'(', b')')?;
    text[closing + 1..].trim().is_empty().then_some(closing)
}

/// Whether the owner's return value can only have come through the changed
/// expression, and if so what the pinned value must look like.
/// `changed_line` is the changed line's offset from the body's first line;
/// the tail must span it, so an identical expression elsewhere in the body
/// is not mistaken for the changed one.
fn return_path_gate(body: &str, expression: &str, changed_line: usize) -> Option<ReturnPathGate> {
    let masked = mask_comments_and_strings(body);
    let open = body_block_open(&masked)?;
    let close = matching_close(&masked, open, b'{', b'}')?;
    let inner = &masked[open + 1..close];
    let inner_text = &body[open + 1..close];
    let changed = collapse_whitespace(expression.trim().trim_end_matches(';'));
    let changed = changed
        .strip_prefix("return ")
        .map_or(changed.as_str(), str::trim);
    if changed.is_empty() {
        return None;
    }
    let spans_changed_line = |start: usize, end: usize| {
        let line_of = |offset: usize| body[..open + 1 + offset].matches('\n').count();
        let text = &inner_text[start..end];
        let first = start + (text.len() - text.trim_start().len());
        let last = start + text.trim_end().len();
        (line_of(first)..=line_of(last)).contains(&changed_line)
    };
    let (after_semicolon, after_brace) = top_level_tail_starts(inner);
    let tail_is_changed = [after_semicolon, after_brace].into_iter().any(|start| {
        collapse_whitespace(&inner_text[start..]) == changed
            && spans_changed_line(start, inner_text.len())
    });
    // `return <changed>;` as the final statement is also the tail.
    let final_return_is_changed = !tail_is_changed
        && inner[after_semicolon..].trim().is_empty()
        && final_statement(inner, after_semicolon).is_some_and(|(start, end)| {
            collapse_whitespace(&inner_text[start..end])
                .strip_prefix("return ")
                .is_some_and(|value| value.trim() == changed)
                && spans_changed_line(start, end)
        });
    if !tail_is_changed && !final_return_is_changed {
        return None;
    }
    if has_unbounded_macro(inner) {
        return None;
    }
    let returns = whole_word_offsets(inner, "return");
    let other_returns = returns.len() - usize::from(final_return_is_changed);
    let early_exits = inner.bytes().filter(|byte| *byte == b'?').count() + other_returns;
    if early_exits == 0 {
        return Some(ReturnPathGate::Any);
    }
    let (head, other) = if constructor_call_span(changed, "Ok").is_some() {
        ("Ok", "Err")
    } else if constructor_call_span(changed, "Some").is_some() {
        ("Some", "None")
    } else {
        return None;
    };
    let head_calls = whole_word_offsets(inner, head)
        .into_iter()
        .filter(|offset| inner[offset + head.len()..].trim_start().starts_with('('))
        .count();
    if head_calls != 1 {
        return None;
    }
    // Every other `return` must build the other constructor. When the
    // changed expression is the final `return`, it is the last one.
    let last = returns.len().checked_sub(1);
    let returns_agree = returns.iter().enumerate().all(|(position, offset)| {
        (final_return_is_changed && Some(position) == last)
            || starts_with_word(inner[offset + "return".len()..].trim_start(), other)
    });
    returns_agree.then_some(ReturnPathGate::Head(head))
}

/// Whether `text` starts with the whole word `word`.
fn starts_with_word(text: &str, word: &str) -> bool {
    text.strip_prefix(word).is_some_and(|after| {
        !after.starts_with(|character: char| character.is_ascii_alphanumeric() || character == '_')
    })
}

/// Byte offset of the `{` that opens the function body: the first brace
/// after the parameter list closes.
fn body_block_open(masked: &str) -> Option<usize> {
    let params = masked.find('(')?;
    let params_close = matching_close(masked, params, b'(', b')')?;
    masked[params_close..]
        .find('{')
        .map(|offset| params_close + offset)
}

/// Where the tail expression may start: after the last top-level `;`, and
/// after the last top-level `}` (a block-like statement needs no `;`).
fn top_level_tail_starts(inner: &str) -> (usize, usize) {
    let mut depth = 0usize;
    let mut after_semicolon = 0usize;
    let mut after_brace = 0usize;
    for (offset, byte) in inner.bytes().enumerate() {
        match byte {
            b'(' | b'[' | b'{' => depth += 1,
            b')' | b']' => depth = depth.saturating_sub(1),
            b'}' => {
                depth = depth.saturating_sub(1);
                if depth == 0 {
                    after_brace = offset + 1;
                }
            }
            b';' if depth == 0 => after_semicolon = offset + 1,
            _ => {}
        }
    }
    (after_semicolon, after_brace.max(after_semicolon))
}

/// The span of the top-level statement that ends at the `;` just before
/// `end`, without the `;`.
fn final_statement(masked: &str, end: usize) -> Option<(usize, usize)> {
    let statement_end = end.checked_sub(1)?;
    let (previous_semicolon, previous_brace) = top_level_tail_starts(&masked[..statement_end]);
    Some((previous_semicolon.max(previous_brace), statement_end))
}

/// Macros that cannot return a value from the enclosing function. Any other
/// macro in the owner body (`bail!`, `ensure!`, a crate's own macro) may
/// hide a `return`, so the return paths are not established.
const NON_RETURNING_MACROS: &[&str] = &[
    "assert",
    "assert_eq",
    "assert_ne",
    "cfg",
    "column",
    "concat",
    "dbg",
    "debug_assert",
    "debug_assert_eq",
    "debug_assert_ne",
    "eprint",
    "eprintln",
    "file",
    "format",
    "format_args",
    "line",
    "matches",
    "module_path",
    "panic",
    "print",
    "println",
    "stringify",
    "todo",
    "unimplemented",
    "unreachable",
    "vec",
    "write",
    "writeln",
];

fn has_unbounded_macro(masked: &str) -> bool {
    let bytes = masked.as_bytes();
    bytes.iter().enumerate().any(|(offset, byte)| {
        if *byte != b'!' || offset == 0 || !is_ident_byte(bytes[offset - 1]) {
            return false;
        }
        // `!=` is an operator, not a macro bang.
        if bytes.get(offset + 1) == Some(&b'=') {
            return false;
        }
        let start = masked[..offset]
            .rfind(|character: char| !(character.is_ascii_alphanumeric() || character == '_'))
            .map_or(0, |position| position + 1);
        !NON_RETURNING_MACROS.contains(&&masked[start..offset])
    })
}

/// Whether another workspace definition of the owner's name could take a
/// call by that name. A bare call competes with every other module-level
/// function of the name; a method call competes with every other method of
/// the name that has a body (overrides, inherent methods of other types,
/// other traits' methods), except a pure `(**self).name(..)` forward, which
/// dispatches to the same method on the pointee. A definition whose item
/// container is unknown (lexical fallback) always competes, and so does a
/// `fn name` the parser never indexed (inside a `macro_rules!` body).
fn other_definition_competes(owner: &FunctionSummary, index: &RustIndex, method: bool) -> bool {
    let name = owner.name.as_str();
    let is_owner = |file: &PathBuf, line: usize| *file == owner.file && line == owner.start_line;
    let indexed_competes = index.functions.iter().any(|function| {
        if function.name != name || is_owner(&function.file, function.start_line) {
            return false;
        }
        match function.item.container {
            FunctionContainer::Unknown => true,
            FunctionContainer::Local => false,
            FunctionContainer::Free => !method,
            _ => {
                method
                    && function.item.has_self_param
                    && function.item.has_body
                    && !is_self_forward(&function.body, name)
            }
        }
    });
    if indexed_competes {
        return true;
    }
    index.files.iter().any(|(path, facts)| {
        // Masking only erases text, so a file whose raw source has no
        // `fn <name>` has none after masking either; skip the mask.
        if fn_definition_offsets(&facts.source, name).is_empty() {
            return false;
        }
        let masked = mask_comments_and_strings(&facts.source);
        fn_definition_offsets(&masked, name)
            .into_iter()
            .any(|offset| {
                let line = masked[..offset]
                    .bytes()
                    .filter(|byte| *byte == b'\n')
                    .count()
                    + 1;
                let indexed = facts
                    .functions
                    .iter()
                    .any(|function| function.name == name && function.start_line == line)
                    || is_owner(path, line);
                if indexed {
                    return false;
                }
                let Some(definition) = unindexed_definition(&facts.source, &masked, offset) else {
                    return true;
                };
                match definition.body {
                    None => false,
                    Some(body) => definition.has_self == method && !is_self_forward(body, name),
                }
            })
    })
}

struct UnindexedDefinition<'a> {
    has_self: bool,
    body: Option<&'a str>,
}

/// The parameter receiver and body of a `fn` definition the parser did not
/// index, read from its text.
fn unindexed_definition<'a>(
    source: &'a str,
    masked: &str,
    offset: usize,
) -> Option<UnindexedDefinition<'a>> {
    let params = offset + masked[offset..].find('(')?;
    let params_close = matching_close(masked, params, b'(', b')')?;
    let first_param = masked[params + 1..params_close]
        .split(',')
        .next()
        .unwrap_or("")
        .trim();
    let receiver = first_param.trim_start_matches('&').trim_start();
    let receiver = if receiver.starts_with('\'') {
        receiver
            .split_once(char::is_whitespace)
            .map_or("", |(_, rest)| rest.trim_start())
    } else {
        receiver
    };
    let receiver = receiver
        .strip_prefix("mut ")
        .map_or(receiver, str::trim_start);
    let has_self =
        receiver == "self" || receiver.starts_with("self:") || receiver.starts_with("self ");
    let mut depth = 0usize;
    for (relative, byte) in masked[params_close..].bytes().enumerate() {
        match byte {
            b'(' | b'[' => depth += 1,
            b')' | b']' => depth = depth.saturating_sub(1),
            b';' if depth == 0 => {
                return Some(UnindexedDefinition {
                    has_self,
                    body: None,
                });
            }
            b'{' if depth == 0 => {
                let open = params_close + relative;
                let close = matching_close(masked, open, b'{', b'}')?;
                return Some(UnindexedDefinition {
                    has_self,
                    body: Some(&source[open..=close]),
                });
            }
            _ => {}
        }
    }
    None
}

/// Whether `body` only forwards to the same method on the pointee:
/// `{ (**self).name(..) }` or `{ (*self).name(..) }`.
fn is_self_forward(body: &str, name: &str) -> bool {
    let masked = mask_comments_and_strings(body);
    let Some(open) = masked.find('{') else {
        return false;
    };
    let Some(close) = matching_close(&masked, open, b'{', b'}') else {
        return false;
    };
    let inner = body[open + 1..close].trim();
    ["(**self).", "(*self)."].iter().any(|prefix| {
        inner
            .strip_prefix(prefix)
            .is_some_and(|call| matches!(owner_call_shape(call, name), Some(CallShape::Bare)))
    })
}

/// Offsets of the `fn` keyword in every `fn <name>` definition.
fn fn_definition_offsets(masked: &str, name: &str) -> Vec<usize> {
    whole_word_offsets(masked, "fn")
        .into_iter()
        .filter(|offset| {
            let rest = masked[offset + 2..].trim_start();
            rest.strip_prefix(name).is_some_and(|after| {
                let after = after.trim_start();
                after.starts_with('(') || after.starts_with('<')
            })
        })
        .collect()
}

/// The receiver type an `impl` block's self type names, when it is one this
/// module can match a test binding against.
fn declared_receiver(self_ty: &str, index: &RustIndex) -> Option<ReceiverType> {
    if is_byte_slice_type(self_ty) {
        return Some(ReceiverType::ByteSlice);
    }
    if self_ty.starts_with(['&', '[', '(', '*']) || self_ty.starts_with("dyn ") {
        return None;
    }
    let base = path_base_name(self_ty)?;
    type_declared_in_workspace(base, index).then(|| ReceiverType::Named(base.to_string()))
}

/// Every receiver type with an `impl .. <trait_name> for <type>` block in
/// the workspace.
fn trait_impl_receivers(trait_name: &str, index: &RustIndex) -> Vec<ReceiverType> {
    let mut receivers = Vec::new();
    for facts in index.files.values() {
        if !facts.source.contains(trait_name) {
            continue;
        }
        let masked = mask_comments_and_strings(&facts.source);
        for offset in whole_word_offsets(&masked, "impl") {
            let Some(header_end) = masked[offset..].find(['{', ';']) else {
                continue;
            };
            let header = collapse_whitespace(&masked[offset + "impl".len()..offset + header_end]);
            let header = strip_leading_generics(&header);
            let Some((trait_path, self_ty)) = header.split_once(" for ") else {
                continue;
            };
            let self_ty = self_ty.split(" where ").next().unwrap_or(self_ty).trim();
            if path_base_name(trait_path.trim()) != Some(trait_name) {
                continue;
            }
            if let Some(receiver) = declared_receiver(self_ty, index)
                && !receivers.contains(&receiver)
            {
                receivers.push(receiver);
            }
        }
    }
    receivers
}

fn strip_leading_generics(header: &str) -> &str {
    let header = header.trim_start();
    if !header.starts_with('<') {
        return header;
    }
    let mut depth = 0usize;
    for (offset, byte) in header.bytes().enumerate() {
        match byte {
            b'<' => depth += 1,
            b'>' => {
                depth = depth.saturating_sub(1);
                if depth == 0 {
                    return header[offset + 1..].trim_start();
                }
            }
            _ => {}
        }
    }
    header
}

fn type_declared_in_workspace(name: &str, index: &RustIndex) -> bool {
    let declares = |text: &str| {
        ["struct", "enum", "union"].iter().any(|keyword| {
            whole_word_offsets(text, keyword)
                .into_iter()
                .any(|offset| starts_with_word(text[offset + keyword.len()..].trim_start(), name))
        })
    };
    // The raw check is a superset of the masked one; mask only on a hit.
    index
        .files
        .values()
        .any(|facts| declares(&facts.source) && declares(&mask_comments_and_strings(&facts.source)))
}

/// The type the test binds `receiver` to: every `let` that binds the name
/// is a simple `let [mut] receiver [: T] = ..;` whose type ripr can read,
/// and all of them agree. Other uses of the binding (borrows, arguments,
/// reassignments) cannot change a Rust binding's type; another binding of
/// the same name in a pattern ripr does not read (a closure parameter, a
/// `for` or match-arm pattern, a destructuring `let`, a nested `fn`)
/// leaves the type unestablished.
fn test_receiver_type(
    test: &TestSummary,
    receiver: &str,
    test_source: Option<&str>,
    index: &RustIndex,
) -> Option<ReceiverType> {
    let masked = mask_comments_and_strings(&test.body);
    if binds_outside_let(&masked, receiver) {
        return None;
    }
    let mut bound: Option<ReceiverType> = None;
    for offset in whole_word_offsets(&masked, "let") {
        let pattern_start = offset + "let".len();
        let Some(relative_end) = top_level_semicolon(&masked[pattern_start..]) else {
            // A `let` ripr cannot bound (an `if let` closing its block):
            // its pattern may still bind the name.
            let rest = &masked[pattern_start..];
            let end = rest.find(['=', '{']).unwrap_or(rest.len());
            if contains_as_whole_word(&rest[..end], receiver) {
                return None;
            }
            continue;
        };
        let statement_end = pattern_start + relative_end;
        let statement = &masked[pattern_start..statement_end];
        let pattern_end = statement
            .match_indices('=')
            .map(|(position, _)| position)
            .find(|position| {
                !matches!(statement.as_bytes().get(position + 1), Some(b'=' | b'>'))
                    && !matches!(
                        statement.as_bytes().get(position.wrapping_sub(1)),
                        Some(b'=' | b'!' | b'<' | b'>')
                    )
            })
            .unwrap_or(statement.len());
        if !contains_as_whole_word(&statement[..pattern_end], receiver) {
            continue;
        }
        let pattern = statement[..pattern_end].trim();
        let pattern = pattern
            .strip_prefix("mut ")
            .map_or(pattern, str::trim_start);
        let annotation = pattern.strip_prefix(receiver)?.trim_start();
        if !(annotation.is_empty() || annotation.starts_with(':')) {
            return None;
        }
        let binding = &test.body[pattern_start..statement_end];
        let binding = &binding[binding.find(receiver)? + receiver.len()..];
        let receiver_type = binding_type(binding, test_source, index)?;
        match &bound {
            None => bound = Some(receiver_type),
            Some(existing) if *existing == receiver_type => {}
            Some(_) => return None,
        }
    }
    bound
}

/// Whether `name` may be bound by a pattern that is not a `let`: a closure
/// parameter list, a `for` pattern, a match arm, or a nested `fn`'s
/// parameters. Lexical and conservative: a `|` operator or an unrelated
/// match arm that mentions the name also counts.
fn binds_outside_let(masked: &str, name: &str) -> bool {
    if whole_word_offsets(masked, "fn").len() > 1 {
        return true;
    }
    let bytes = masked.as_bytes();
    let pipes = bytes
        .iter()
        .enumerate()
        .filter(|(offset, byte)| {
            **byte == b'|'
                && bytes.get(offset + 1) != Some(&b'|')
                && (*offset == 0 || bytes[offset - 1] != b'|')
        })
        .map(|(offset, _)| offset)
        .collect::<Vec<_>>();
    // Every region between two consecutive pipes: a `|` operator must not
    // shift a closure's parameter list out of the pairing.
    if pipes
        .windows(2)
        .any(|pair| contains_as_whole_word(&masked[pair[0]..pair[1]], name))
    {
        return true;
    }
    let for_pattern = whole_word_offsets(masked, "for").into_iter().any(|offset| {
        let rest = &masked[offset + "for".len()..];
        let end = whole_word_offsets(rest, "in")
            .first()
            .copied()
            .unwrap_or(rest.len());
        contains_as_whole_word(&rest[..end], name)
    });
    if for_pattern {
        return true;
    }
    masked.match_indices("=>").any(|(arrow, _)| {
        let start = masked[..arrow]
            .rfind(['{', ',', '}'])
            .map_or(0, |position| position + 1);
        contains_as_whole_word(&masked[start..arrow], name)
    })
}

/// The type of one `let <receiver> ...;` binding: its annotation, or a
/// constructor-shaped initializer.
fn binding_type(
    binding: &str,
    test_source: Option<&str>,
    index: &RustIndex,
) -> Option<ReceiverType> {
    let binding = binding.trim();
    let (annotation, initializer) = if let Some(rest) = binding.strip_prefix(':') {
        let (annotation, initializer) = rest.split_once('=')?;
        (Some(annotation.trim()), initializer.trim())
    } else {
        (None, binding.strip_prefix('=')?.trim())
    };
    if let Some(annotation) = annotation {
        return named_or_slice(annotation, test_source, index);
    }
    if is_byte_slice_expression(initializer) {
        return Some(ReceiverType::ByteSlice);
    }
    let initializer = initializer
        .strip_suffix('?')
        .or_else(|| initializer.strip_suffix(".unwrap()"))
        .unwrap_or(initializer)
        .trim();
    let type_end = initializer
        .find(|character: char| !(character.is_ascii_alphanumeric() || character == '_'))?;
    let type_name = &initializer[..type_end];
    let rest = &initializer[type_end..];
    let constructor = if let Some(call) = rest.strip_prefix("::") {
        let call_end =
            call.find(|character: char| !(character.is_ascii_alphanumeric() || character == '_'))?;
        // Only a conventional constructor names the type it returns; an
        // arbitrary associated function may return anything.
        if !is_constructor_name(&call[..call_end]) {
            return None;
        }
        let masked = mask_comments_and_strings(&call[call_end..]);
        masked.starts_with('(')
            && matching_close(&masked, 0, b'(', b')')
                .is_some_and(|closing| masked[closing + 1..].trim().is_empty())
    } else {
        let rest = rest.trim_start();
        let (open, close) = if rest.starts_with('{') {
            (b'{', b'}')
        } else {
            (b'(', b')')
        };
        let masked = mask_comments_and_strings(rest);
        masked.as_bytes().first() == Some(&open)
            && matching_close(&masked, 0, open, close)
                .is_some_and(|closing| masked[closing + 1..].trim().is_empty())
    };
    if !constructor {
        return None;
    }
    named_or_slice(type_name, test_source, index)
}

/// Associated-function names that conventionally return `Self` (after
/// `?` or `.unwrap()` for the fallible ones).
fn is_constructor_name(name: &str) -> bool {
    matches!(name, "new" | "default" | "from" | "try_from" | "try_new")
        || ["new_", "with_", "from_"]
            .iter()
            .any(|prefix| name.starts_with(prefix))
}

fn named_or_slice(
    type_text: &str,
    test_source: Option<&str>,
    index: &RustIndex,
) -> Option<ReceiverType> {
    if is_byte_slice_type(type_text) {
        return Some(ReceiverType::ByteSlice);
    }
    let base = path_base_name(type_text)?;
    if !base.starts_with(|character: char| character.is_ascii_uppercase()) {
        return None;
    }
    // A test file that imports the name from outside the workspace binds a
    // different type than the workspace declaration.
    if test_source
        .is_some_and(|source| file_imports_foreign_callee_name(source, base, &index.package_names))
    {
        return None;
    }
    Some(ReceiverType::Named(base.to_string()))
}

/// A trait's methods are callable with method syntax only while the trait
/// is in scope: the test's file imports it by name from the workspace, or
/// declares it.
fn trait_in_scope(source: &str, trait_name: &str, index: &RustIndex) -> bool {
    if file_imports_foreign_callee_name(source, trait_name, &index.package_names) {
        return false;
    }
    if file_imports_own_item(source, trait_name, &index.package_names) {
        return true;
    }
    let masked = mask_comments_and_strings(source);
    whole_word_offsets(&masked, "trait")
        .into_iter()
        .any(|offset| {
            masked[offset + "trait".len()..]
                .trim_start()
                .strip_prefix(trait_name)
                .is_some_and(|after| {
                    !after.starts_with(|character: char| {
                        character.is_ascii_alphanumeric() || character == '_'
                    })
                })
        })
}

fn test_body_shadows_owner(test: &TestSummary, owner: &str) -> bool {
    if fact_body_defines_callee_fn(&test.nested_fn_names, owner)
        || fact_body_let_shadow_line(&test.let_bindings, owner).is_some()
    {
        return true;
    }
    let masked = mask_comments_and_strings(&test.body);
    test_body_defines_callee_fn(&masked, owner)
        || test_body_let_shadow_line(&masked, owner).is_some()
}

fn is_byte_slice_type(text: &str) -> bool {
    let compact: String = text.split_whitespace().collect();
    let Some(rest) = compact.strip_prefix('&') else {
        return false;
    };
    let rest = match rest.strip_prefix('\'') {
        Some(lifetime) => lifetime.trim_start_matches(|character: char| {
            character.is_ascii_alphanumeric() || character == '_'
        }),
        None => rest,
    };
    rest == "[u8]"
}

/// `&[..][..]` or `&b".."[..]`: a byte-slice expression.
fn is_byte_slice_expression(initializer: &str) -> bool {
    let Some(rest) = initializer.trim().strip_prefix('&') else {
        return false;
    };
    let Some(array) = rest.trim_end().strip_suffix("[..]") else {
        return false;
    };
    let array = array.trim();
    if let Some(bytes) = array.strip_prefix("b\"") {
        return bytes.ends_with('"');
    }
    let masked = mask_comments_and_strings(array);
    masked.starts_with('[')
        && matching_close(&masked, 0, b'[', b']').is_some_and(|close| close + 1 == masked.len())
}

/// The last `::` segment of a path, without generic arguments.
fn path_base_name(path: &str) -> Option<&str> {
    let path = path.trim();
    let without_generics = path.split('<').next()?.trim();
    let base = without_generics.rsplit("::").next()?.trim();
    is_plain_identifier(base).then_some(base)
}

fn is_plain_identifier(text: &str) -> bool {
    text.starts_with(|character: char| character.is_ascii_alphabetic() || character == '_')
        && text
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || character == '_')
}

fn is_ident_byte(byte: u8) -> bool {
    byte.is_ascii_alphanumeric() || byte == b'_'
}

fn whole_word_offsets(text: &str, word: &str) -> Vec<usize> {
    let bytes = text.as_bytes();
    let mut offsets = Vec::new();
    let mut search = 0usize;
    while let Some(relative) = text[search..].find(word) {
        let offset = search + relative;
        let end = offset + word.len();
        let before_ok = offset == 0 || !is_ident_byte(bytes[offset - 1]);
        let after_ok = end >= bytes.len() || !is_ident_byte(bytes[end]);
        if before_ok && after_ok {
            offsets.push(offset);
        }
        search = end;
    }
    offsets
}

/// Offset of the first `;` outside brackets.
fn top_level_semicolon(masked: &str) -> Option<usize> {
    let mut depth = 0usize;
    for (offset, byte) in masked.bytes().enumerate() {
        match byte {
            b'(' | b'[' | b'{' => depth += 1,
            b')' | b']' | b'}' => depth = depth.checked_sub(1)?,
            b';' if depth == 0 => return Some(offset),
            _ => {}
        }
    }
    None
}

/// The offset of the bracket closing the one at `opening`, in masked text.
fn matching_close(masked: &str, opening: usize, open: u8, close: u8) -> Option<usize> {
    let bytes = masked.as_bytes();
    if bytes.get(opening) != Some(&open) {
        return None;
    }
    let mut depth = 0usize;
    for (offset, byte) in bytes.iter().enumerate().skip(opening) {
        if *byte == open {
            depth += 1;
        } else if *byte == close {
            depth = depth.checked_sub(1)?;
            if depth == 0 {
                return Some(offset);
            }
        }
    }
    None
}

fn collapse_whitespace(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// Method names `&[u8]` resolves before a workspace trait's method: the
/// inherent methods of slices and byte slices, and the methods of prelude
/// and `std::io` traits implemented for them. A byte-slice receiver never
/// credits a pin through one of these names.
const BYTE_SLICE_METHODS: &[&str] = &[
    "align_to",
    "align_to_mut",
    "array_chunks",
    "array_windows",
    "as_array",
    "as_ascii",
    "as_chunks",
    "as_flattened",
    "as_mut",
    "as_mut_ptr",
    "as_mut_ptr_range",
    "as_ptr",
    "as_ptr_range",
    "as_rchunks",
    "as_ref",
    "as_simd",
    "binary_search",
    "binary_search_by",
    "binary_search_by_key",
    "borrow",
    "by_ref",
    "bytes",
    "chain",
    "chunk_by",
    "chunks",
    "chunks_exact",
    "clone",
    "clone_from",
    "cmp",
    "concat",
    "connect",
    "consume",
    "contains",
    "copy_from_slice",
    "copy_within",
    "element_offset",
    "ends_with",
    "eq",
    "eq_ignore_ascii_case",
    "escape_ascii",
    "fill",
    "fill_buf",
    "fill_with",
    "first",
    "first_chunk",
    "fmt",
    "ge",
    "get",
    "get_mut",
    "get_unchecked",
    "gt",
    "hash",
    "into",
    "into_iter",
    "is_ascii",
    "is_empty",
    "is_sorted",
    "is_sorted_by",
    "is_sorted_by_key",
    "iter",
    "join",
    "last",
    "last_chunk",
    "le",
    "len",
    "lines",
    "lt",
    "make_ascii_lowercase",
    "make_ascii_uppercase",
    "max",
    "min",
    "ne",
    "partial_cmp",
    "partition_point",
    "rchunks",
    "rchunks_exact",
    "read",
    "read_buf",
    "read_exact",
    "read_line",
    "read_to_end",
    "read_to_string",
    "read_until",
    "read_vectored",
    "repeat",
    "reverse",
    "rotate_left",
    "rotate_right",
    "rsplit",
    "rsplit_once",
    "rsplitn",
    "select_nth_unstable",
    "skip_until",
    "sort",
    "sort_by",
    "sort_by_cached_key",
    "sort_by_key",
    "sort_unstable",
    "sort_unstable_by",
    "sort_unstable_by_key",
    "split",
    "split_at",
    "split_at_checked",
    "split_first",
    "split_first_chunk",
    "split_inclusive",
    "split_last",
    "split_last_chunk",
    "split_off",
    "split_off_first",
    "split_off_last",
    "split_once",
    "splitn",
    "starts_with",
    "strip_prefix",
    "strip_suffix",
    "subslice_range",
    "swap",
    "swap_with_slice",
    "take",
    "to_ascii_lowercase",
    "to_ascii_uppercase",
    "to_owned",
    "to_vec",
    "trim_ascii",
    "trim_ascii_end",
    "trim_ascii_start",
    "trim_prefix",
    "trim_suffix",
    "try_into",
    "type_id",
    "utf8_chunks",
    "windows",
];

#[cfg(test)]
mod tests;
