//! Owner-return pins (#4478): an `assert_eq!` whose operand is a call of
//! the changed owner pins the owner's whole return value, so it observes a
//! changed `return_value` expression without sharing a token with it.
//!
//! Crediting that assertion is only sound when three facts hold, and each
//! gate below fails closed when ripr cannot establish one:
//!
//! 1. The call names the owner. A bare `name(..)` names a module-level
//!    function, never an associated function or a trait method. A method
//!    call `recv.name(..)` names a function with a `self` receiver, and only
//!    when the receiver's type dispatches to the owner: the test binds the
//!    receiver to a type ripr can read, that type reaches the owner's `impl`
//!    or trait, and no other definition of `name` in the workspace could
//!    take the call instead.
//! 2. The call's return value came through the changed expression. The
//!    changed expression must be the owner's tail and must evaluate all of
//!    its parts on every input (no closure, `&&`/`||`, branch, or skipping
//!    combinator such as `map_or`). When the owner has other
//!    exits (`?`, `return`), the changed expression must be the owner's only
//!    `Ok(..)` (or `Some(..)`) constructor and the pinned value must be that
//!    constructor too: an `Err(..)` pin observes an early exit that never
//!    evaluates the changed `Ok(..)`.
//! 3. The pinned value is the whole return value: one plain `assert_eq!`
//!    in the test's own body with the call as a complete operand, nothing
//!    chained after it, and an expected value that does not call the owner
//!    again. `assert_ne!`, `debug_assert_eq!` and a `#[should_panic]` test
//!    pin nothing. Its exact parser context must also establish an eager
//!    statement path (or a directly invoked bounded closure), and no visible
//!    workspace macro definition/import may compete with `assert_eq!`.
//!    Deferred, conditional and ambiguous contexts do not supply this pin.
//!
//! This is bounded syntax, not name resolution. The documented residuals:
//! methods generated by derive or attribute macros are invisible, a
//! `macro_rules!` body that defines the method counts only when ripr can
//! read its `fn` text, and an out-of-workspace trait in scope that also
//! names the method is not detected.

use super::super::rust_index::{FunctionSummary, OracleFact, RustIndex, TestSummary};
use super::reveal::{
    assertion_comparison_operands, contains_as_whole_word, file_imports_foreign_callee_name,
    file_imports_own_item,
};
use crate::analysis::extract::{
    fact_body_defines_callee_fn, fact_body_let_shadow_line, mask_comments_and_strings,
    test_body_defines_callee_fn, test_body_let_shadow_line,
};
use crate::analysis::facts::{FunctionContainer, SourceRoleProvenanceEdgeKind};
use crate::analysis::syntax::{
    OwnerPinAssertions, empty_macro_binding_ambiguities, local_empty_macro_names,
    owner_pin_assertions, trusted_macro_binding_ambiguities,
};
use crate::domain::{Probe, ProbeFamily};
use rayon::prelude::*;
use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

/// The owner-side half of the pin, established once per probe.
pub(in crate::analysis) struct OwnerReturnPin {
    name: String,
    call: PinCall,
    path: ReturnPathGate,
    /// Per test file: whether the owner's trait is in scope. The trait is
    /// fixed per pin and the scan masks the whole file, so it runs once.
    trait_scope_by_file: RefCell<BTreeMap<PathBuf, bool>>,
}

/// Run-scoped syntax decisions shared by every probe against one index.
/// No cache outlives that immutable index; no public/file facts are changed.
#[derive(Clone, Debug, Default)]
pub(in crate::analysis) struct OwnerPinSyntax {
    ambiguous_macro_bindings: RefCell<Option<BTreeSet<String>>>,
    by_file: RefCell<BTreeMap<PathBuf, OwnerPinAssertions>>,
    empty_macro_ambiguities: RefCell<BTreeMap<PathBuf, BTreeSet<String>>>,
}

impl OwnerPinSyntax {
    /// Shared equality-oracle admission for the bounded supported families.
    /// Execution provenance is independent of the error/boundary/value matcher.
    /// Applicability is the invocation
    /// identity, not the more restrictive owner-pin operand shape, so token
    /// matches and nested diagnostic syntax cannot bypass the same refusal.
    pub(in crate::analysis) fn admits_equality_assertion(
        &self,
        probe: &Probe,
        test: &TestSummary,
        assertion: &OracleFact,
        index: &RustIndex,
    ) -> bool {
        !matches!(
            probe.family,
            ProbeFamily::ReturnValue | ProbeFamily::ErrorPath | ProbeFamily::Predicate
        ) || !is_bare_assert_eq_invocation(&assertion.text)
            || self.admits(test, assertion, index)
    }

    fn admits(&self, test: &TestSummary, assertion: &OracleFact, index: &RustIndex) -> bool {
        let mut ambiguous = self.ambiguous_macro_bindings.borrow_mut();
        // Parses every workspace file once per run, so on a warm `ripr check`
        // of a large workspace this scan dominated wall time (37% on
        // ripr-swarm). Files are independent and the result is a set, so the
        // scan runs on the rayon pool with an order-independent answer.
        let ambiguous = ambiguous.get_or_insert_with(|| {
            let sources = index
                .files()
                .values()
                .map(|facts| facts.data().source.as_str())
                .collect::<Vec<_>>();
            sources
                .par_iter()
                .flat_map_iter(|source| {
                    trusted_macro_binding_ambiguities(
                        source,
                        &index.package_names,
                        NON_RETURNING_MACROS,
                    )
                })
                .collect()
        });
        let Some(facts) = index
            .files()
            .get(&test.file)
            .filter(|facts| !facts.used_lexical_fallback)
        else {
            return false;
        };
        if facts.role_provenance.earliest_unresolved_reason.is_some() {
            return false;
        }
        let mut empty_by_file = self.empty_macro_ambiguities.borrow_mut();
        let empty_ambiguities = empty_by_file.entry(test.file.clone()).or_insert_with(|| {
            let names = local_empty_macro_names(&facts.source);
            if names.is_empty() {
                return BTreeSet::new();
            }
            index
                .files()
                .iter()
                .flat_map(|(path, file)| {
                    empty_macro_binding_ambiguities(
                        &file.source,
                        &index.package_names,
                        &names,
                        path == &test.file,
                    )
                })
                .collect()
        });
        let ambiguous: BTreeSet<_> = ambiguous.union(empty_ambiguities).cloned().collect();
        let mut by_file = self.by_file.borrow_mut();
        for edge in &facts.role_provenance.edges {
            // Module composition already owns resolution. Include expansions
            // lack an exact declaration coordinate here, so remain unknown.
            if edge.kind != SourceRoleProvenanceEdgeKind::Module {
                return false;
            }
            let Some(parent) = index
                .files()
                .get(&edge.parent)
                .filter(|facts| !facts.used_lexical_fallback)
            else {
                return false;
            };
            if !by_file
                .entry(edge.parent.clone())
                .or_insert_with(|| owner_pin_assertions(&parent.source, NON_RETURNING_MACROS))
                .admits_module_declaration(edge.line, &edge.declaration)
            {
                return false;
            }
        }
        by_file
            .entry(test.file.clone())
            .or_insert_with(|| owner_pin_assertions(&facts.source, NON_RETURNING_MACROS))
            .admits(
                (test.start_line, test.end_line, &test.name),
                &test.body,
                (assertion.line, &assertion.text),
                &ambiguous,
            )
    }
}

/// Whether a test file imports a name from outside the workspace; the
/// caller supplies its run-scoped memo.
pub(in crate::analysis) type ForeignImport<'a> = &'a dyn Fn(&Path, &str) -> bool;

enum PinCall {
    /// `name(..)`: the owner is a module-level function.
    Bare,
    /// `recv.name(..)`: the receiver's type must be one of `receivers`, and
    /// a trait method also needs its trait in the test's scope.
    Method {
        receivers: Vec<ReceiverType>,
        trait_scope: Option<TraitScope>,
    },
}

/// A trait method is callable with method syntax only while its trait is
/// in scope.
struct TraitScope {
    trait_name: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
enum ReceiverType {
    /// A struct, enum or union declared in the workspace.
    Named(String),
    /// `&[u8]`, read from `&[..][..]` or `&b".."[..]`.
    ByteSlice,
}

enum ReturnPathGate {
    /// The changed expression is the owner's only exit.
    Any,
    /// The pinned value must start with this constructor.
    Head(&'static str),
}

impl OwnerReturnPin {
    /// The owner-side gates: `None` when the probe is not a return value,
    /// the owner's declaration or return paths are not established, or
    /// another workspace definition could take a call by the owner's name.
    pub(in crate::analysis) fn establish(
        probe: &Probe,
        owner: &FunctionSummary,
        index: &RustIndex,
    ) -> Option<Self> {
        if !matches!(probe.family, ProbeFamily::ReturnValue) || !owner.item.has_body {
            return None;
        }
        let parser_backed = index
            .files()
            .get(&owner.file)
            .is_some_and(|facts| !facts.used_lexical_fallback);
        if !parser_backed {
            return None;
        }
        let name = owner.name.as_str();
        let changed_line = probe.location.line.checked_sub(owner.start_line)?;
        let path = return_path_gate(&owner.body, &probe.expression, changed_line)?;
        let call = match (&owner.item.container, owner.item.has_self_param) {
            (FunctionContainer::Free, false) => PinCall::Bare,
            (FunctionContainer::Inherent { self_ty }, true) => PinCall::Method {
                receivers: vec![declared_receiver(self_ty, index)?],
                trait_scope: None,
            },
            (
                FunctionContainer::TraitImpl {
                    trait_path,
                    self_ty,
                },
                true,
            ) => PinCall::Method {
                receivers: vec![declared_receiver(self_ty, index)?],
                trait_scope: Some(TraitScope {
                    trait_name: path_base_name(trait_path)?.to_string(),
                }),
            },
            (FunctionContainer::Trait { trait_name }, true) => {
                let receivers = trait_impl_receivers(trait_name, index);
                if receivers.is_empty() {
                    return None;
                }
                PinCall::Method {
                    receivers,
                    trait_scope: Some(TraitScope {
                        trait_name: trait_name.clone(),
                    }),
                }
            }
            _ => return None,
        };
        let method = matches!(call, PinCall::Method { .. });
        if other_definition_competes(owner, index, method) {
            return None;
        }
        Some(Self {
            name: name.to_string(),
            call,
            path,
            trait_scope_by_file: RefCell::default(),
        })
    }

    /// The test-side gates: whether `assertion` in `test` pins the owner's
    /// return value through a call that names the owner.
    pub(in crate::analysis) fn admits(
        &self,
        test: &TestSummary,
        assertion: &OracleFact,
        index: &RustIndex,
        imports_foreign: ForeignImport<'_>,
        syntax: &OwnerPinSyntax,
    ) -> bool {
        // The assertion must be the test's own: a harness trial's body is
        // only its registration, and a helper's `let` bindings are not in it.
        if !(test.start_line..=test.end_line).contains(&assertion.line) {
            return false;
        }
        // A `#[should_panic]` test passes when the values differ.
        if test
            .attrs
            .iter()
            .chain(std::iter::once(&test.body))
            .any(|text| text.contains("should_panic"))
        {
            return false;
        }
        if !is_plain_assert_eq(&assertion.text) || !syntax.admits(test, assertion, index) {
            return false;
        }
        let Some(operands) = assertion_comparison_operands(&assertion.text) else {
            return false;
        };
        let (call, expected) = match (
            owner_call_shape(operands[0], &self.name),
            owner_call_shape(operands[1], &self.name),
        ) {
            (Some(call), None) => (call, operands[1]),
            (None, Some(call)) => (call, operands[0]),
            _ => return false,
        };
        // `assert_eq!(f(4), f(2) + f(2))` compares the owner with itself.
        if contains_as_whole_word(&mask_comments_and_strings(expected), &self.name) {
            return false;
        }
        if !self.path.admits(expected) {
            return false;
        }
        let test_source = index
            .files()
            .get(&test.file)
            .map(|facts| facts.data().source.as_str());
        let masked_body = mask_comments_and_strings(&test.body);
        match (&self.call, call) {
            (PinCall::Bare, CallShape::Bare) => {
                !test_body_shadows_owner(test, &self.name)
                    && !binds_outside_let(&masked_body, &self.name)
                    && !bound_by_macro(&masked_body, &self.name)
                    && test_source.is_some_and(|source| !file_renames_to(source, &self.name))
            }
            (
                PinCall::Method {
                    receivers,
                    trait_scope,
                },
                CallShape::Method(receiver),
            ) => {
                if bound_by_macro(&masked_body, receiver) {
                    return false;
                }
                let Some(receiver_type) =
                    test_receiver_type(test, receiver, test_source, index, imports_foreign)
                else {
                    return false;
                };
                if !receivers.contains(&receiver_type) {
                    return false;
                }
                let shadowed_by_std = match &receiver_type {
                    ReceiverType::ByteSlice => BYTE_SLICE_METHODS.contains(&self.name.as_str()),
                    ReceiverType::Named(_) => {
                        BY_VALUE_PRELUDE_METHODS.contains(&self.name.as_str())
                    }
                };
                !shadowed_by_std
                    && trait_scope.as_ref().is_none_or(|scope| {
                        self.trait_in_scope(test, test_source, &scope.trait_name, index)
                    })
            }
            _ => false,
        }
    }

    fn trait_in_scope(
        &self,
        test: &TestSummary,
        test_source: Option<&str>,
        trait_name: &str,
        index: &RustIndex,
    ) -> bool {
        let Some(source) = test_source else {
            return false;
        };
        if let Some(known) = self.trait_scope_by_file.borrow().get(&test.file) {
            return *known;
        }
        let in_scope = trait_in_scope(source, trait_name, index);
        self.trait_scope_by_file
            .borrow_mut()
            .insert(test.file.clone(), in_scope);
        in_scope
    }
}

impl ReturnPathGate {
    fn admits(&self, expected: &str) -> bool {
        match self {
            Self::Any => true,
            Self::Head(head) => constructor_call_span(expected.trim(), head).is_some(),
        }
    }
}

#[derive(Clone, Copy)]
enum CallShape<'a> {
    Bare,
    Method(&'a str),
}

/// The operand as a complete call of `name`: `name(..)` or `recv.name(..)`
/// with a plain identifier receiver and nothing chained after the call.
fn owner_call_shape<'a>(operand: &'a str, name: &str) -> Option<CallShape<'a>> {
    let operand = operand.trim();
    let call_start = if operand.starts_with(name) {
        0
    } else {
        let dot = operand.find('.')?;
        let receiver = &operand[..dot];
        if !is_plain_identifier(receiver) || receiver == "self" {
            return None;
        }
        if !operand[dot + 1..].starts_with(name) {
            return None;
        }
        dot + 1
    };
    let after_name = &operand[call_start + name.len()..];
    if !after_name.starts_with('(') {
        return None;
    }
    let masked = mask_comments_and_strings(operand);
    let opening = call_start + name.len();
    let closing = matching_close(&masked, opening, b'(', b')')?;
    if !operand[closing + 1..].trim().is_empty() {
        return None;
    }
    Some(if call_start == 0 {
        CallShape::Bare
    } else {
        CallShape::Method(&operand[..call_start - 1])
    })
}

/// The span of `head(..)` when `text` is exactly one `head(..)` call.
fn constructor_call_span(text: &str, head: &str) -> Option<usize> {
    let rest = text.strip_prefix(head)?;
    if !rest.starts_with('(') {
        return None;
    }
    let masked = mask_comments_and_strings(text);
    let closing = matching_close(&masked, head.len(), b'(', b')')?;
    text[closing + 1..].trim().is_empty().then_some(closing)
}

/// Whether the owner's return value can only have come through the changed
/// expression, and if so what the pinned value must look like.
/// `changed_line` is the changed line's offset from the body's first line;
/// the tail must span it, so an identical expression elsewhere in the body
/// is not mistaken for the changed one.
fn return_path_gate(body: &str, expression: &str, changed_line: usize) -> Option<ReturnPathGate> {
    let masked = mask_comments_and_strings(body);
    let open = body_block_open(&masked)?;
    let close = matching_close(&masked, open, b'{', b'}')?;
    let inner = &masked[open + 1..close];
    let inner_text = &body[open + 1..close];
    let changed = collapse_whitespace(expression.trim().trim_end_matches(';'));
    let changed = changed
        .strip_prefix("return ")
        .map_or(changed.as_str(), str::trim);
    if changed.is_empty() {
        return None;
    }
    let spans_changed_line = |start: usize, end: usize| {
        let line_of = |offset: usize| body[..open + 1 + offset].matches('\n').count();
        let text = &inner_text[start..end];
        let first = start + (text.len() - text.trim_start().len());
        let last = start + text.trim_end().len();
        (line_of(first)..=line_of(last)).contains(&changed_line)
    };
    let (after_semicolon, after_brace) = top_level_tail_starts(inner);
    let tail_is_changed = [after_semicolon, after_brace].into_iter().any(|start| {
        collapse_whitespace(&inner_text[start..]) == changed
            && spans_changed_line(start, inner_text.len())
    });
    // `return <changed>;` as the final statement is also the tail.
    let final_return_is_changed = !tail_is_changed
        && inner[after_semicolon..].trim().is_empty()
        && final_statement(inner, after_semicolon).is_some_and(|(start, end)| {
            collapse_whitespace(&inner_text[start..end])
                .strip_prefix("return ")
                .is_some_and(|value| value.trim() == changed)
                && spans_changed_line(start, end)
        });
    if !tail_is_changed && !final_return_is_changed {
        return None;
    }
    if has_unbounded_macro(inner) || evaluates_conditionally(&mask_comments_and_strings(changed)) {
        return None;
    }
    let returns = whole_word_offsets(inner, "return");
    let other_returns = returns.len() - usize::from(final_return_is_changed);
    let early_exits = inner.bytes().filter(|byte| *byte == b'?').count() + other_returns;
    if early_exits == 0 {
        return Some(ReturnPathGate::Any);
    }
    let (head, other) = if constructor_call_span(changed, "Ok").is_some() {
        ("Ok", "Err")
    } else if constructor_call_span(changed, "Some").is_some() {
        ("Some", "None")
    } else {
        return None;
    };
    let head_calls = whole_word_offsets(inner, head)
        .into_iter()
        .filter(|offset| inner[offset + head.len()..].trim_start().starts_with('('))
        .count();
    if head_calls != 1 {
        return None;
    }
    // Every other `return` must build the other constructor. When the
    // changed expression is the final `return`, it is the last one.
    let last = returns.len().checked_sub(1);
    let returns_agree = returns.iter().enumerate().all(|(position, offset)| {
        (final_return_is_changed && Some(position) == last)
            || starts_with_word(inner[offset + "return".len()..].trim_start(), other)
    });
    returns_agree.then_some(ReturnPathGate::Head(head))
}

/// Whether `text` starts with the whole word `word`.
fn starts_with_word(text: &str, word: &str) -> bool {
    text.strip_prefix(word).is_some_and(|after| {
        !after.starts_with(|character: char| character.is_ascii_alphanumeric() || character == '_')
    })
}

/// Byte offset of the `{` that opens the function body: the first brace
/// after the parameter list closes.
fn body_block_open(masked: &str) -> Option<usize> {
    let params = masked.find('(')?;
    let params_close = matching_close(masked, params, b'(', b')')?;
    masked[params_close..]
        .find('{')
        .map(|offset| params_close + offset)
}

/// Where the tail expression may start: after the last top-level `;`, and
/// after the last top-level `}` (a block-like statement needs no `;`).
fn top_level_tail_starts(inner: &str) -> (usize, usize) {
    let mut depth = 0usize;
    let mut after_semicolon = 0usize;
    let mut after_brace = 0usize;
    for (offset, byte) in inner.bytes().enumerate() {
        match byte {
            b'(' | b'[' | b'{' => depth += 1,
            b')' | b']' => depth = depth.saturating_sub(1),
            b'}' => {
                depth = depth.saturating_sub(1);
                if depth == 0 {
                    after_brace = offset + 1;
                }
            }
            b';' if depth == 0 => after_semicolon = offset + 1,
            _ => {}
        }
    }
    (after_semicolon, after_brace.max(after_semicolon))
}

/// The span of the top-level statement that ends at the `;` just before
/// `end`, without the `;`.
fn final_statement(masked: &str, end: usize) -> Option<(usize, usize)> {
    let statement_end = end.checked_sub(1)?;
    let (previous_semicolon, previous_brace) = top_level_tail_starts(&masked[..statement_end]);
    Some((previous_semicolon.max(previous_brace), statement_end))
}

/// Macros that cannot return a value from the enclosing function. Any other
/// macro in the owner body (`bail!`, `ensure!`, a crate's own macro) may
/// hide a `return`, so the return paths are not established.
const NON_RETURNING_MACROS: &[&str] = &[
    "assert",
    "assert_eq",
    "assert_ne",
    "cfg",
    "column",
    "concat",
    "dbg",
    "debug_assert",
    "debug_assert_eq",
    "debug_assert_ne",
    "eprint",
    "eprintln",
    "file",
    "format",
    "format_args",
    "line",
    "matches",
    "module_path",
    "panic",
    "print",
    "println",
    "stringify",
    "todo",
    "unimplemented",
    "unreachable",
    "vec",
    "write",
    "writeln",
];

fn has_unbounded_macro(masked: &str) -> bool {
    macro_invocations(masked)
        .into_iter()
        .any(|(name, _)| !NON_RETURNING_MACROS.contains(&name))
}

/// Every `name!` macro invocation in masked text, with the offset of its
/// opening delimiter. Whitespace may separate the name, the `!` and the
/// delimiter (`ensure !(..)`); a keyword before `!` is a negation
/// (`if !done`), not a macro.
fn macro_invocations(masked: &str) -> Vec<(&str, usize)> {
    let bytes = masked.as_bytes();
    let mut invocations = Vec::new();
    for (offset, byte) in bytes.iter().enumerate() {
        if *byte != b'!' || bytes.get(offset + 1) == Some(&b'=') {
            continue;
        }
        let before = masked[..offset].trim_end();
        let start = before
            .rfind(|character: char| !(character.is_ascii_alphanumeric() || character == '_'))
            .map_or(0, |position| position + 1);
        let name = &before[start..];
        if !is_plain_identifier(name) || NEGATING_KEYWORDS.contains(&name) {
            continue;
        }
        let after = &masked[offset + 1..];
        let delimiter = offset + 1 + (after.len() - after.trim_start().len());
        if matches!(bytes.get(delimiter), Some(b'(' | b'[' | b'{')) {
            invocations.push((name, delimiter));
        }
    }
    invocations
}

/// Keywords a `!` negation can follow; never macro names.
const NEGATING_KEYWORDS: &[&str] = &[
    "if", "while", "return", "match", "in", "else", "break", "let", "mut", "move", "as",
];

/// Whether the changed tail evaluates some of its parts only on some
/// inputs: a closure or `|`/`||`/`&&` operator, a branch or loop, or a
/// combinator that skips its argument (`map_or(0, ..)` on `None`). A pin on
/// such an input never evaluates the changed part, so the tail's value is
/// not established to come through it.
fn evaluates_conditionally(masked_tail: &str) -> bool {
    if masked_tail.contains('|') || masked_tail.contains("&&") {
        return true;
    }
    if [
        "if", "match", "else", "loop", "while", "for", "break", "continue",
    ]
    .iter()
    .any(|keyword| contains_as_whole_word(masked_tail, keyword))
    {
        return true;
    }
    CONDITIONAL_COMBINATORS.iter().any(|combinator| {
        whole_word_offsets(masked_tail, combinator)
            .into_iter()
            .any(|offset| {
                let before = masked_tail[..offset].trim_end();
                (before.ends_with('.') || before.ends_with("::"))
                    && masked_tail[offset + combinator.len()..]
                        .trim_start()
                        .starts_with(['(', ':'])
            })
    })
}

/// `Option`/`Result`/`bool` methods that evaluate or apply an argument only
/// on some inputs.
const CONDITIONAL_COMBINATORS: &[&str] = &[
    "and",
    "and_then",
    "filter",
    "get_or_insert_with",
    "is_none_or",
    "is_ok_and",
    "is_some_and",
    "map",
    "map_err",
    "map_or",
    "map_or_else",
    "ok_or",
    "ok_or_else",
    "or",
    "or_else",
    "then",
    "then_some",
    "unwrap_or",
    "unwrap_or_default",
    "unwrap_or_else",
    "xor",
    "zip",
];

fn is_bare_assert_eq_invocation(text: &str) -> bool {
    let masked = mask_comments_and_strings(text);
    let mut invocation = masked.trim_start();
    // The parser includes a macro statement's attributes in its fact text.
    // Skip only complete attributes; do not mistake an inner invocation in
    // another oracle's token tree for that oracle's own identity.
    while let Some(attribute) = invocation.strip_prefix('#') {
        let attribute = attribute.trim_start();
        let Some(close) = matching_close(attribute, 0, b'[', b']') else {
            return false;
        };
        invocation = attribute[close + 1..].trim_start();
    }
    invocation
        .strip_prefix("r#")
        .unwrap_or(invocation)
        .strip_prefix("assert_eq")
        .is_some_and(|after_name| after_name.trim_start().starts_with('!'))
}

/// Whether `text` is one plain `assert_eq!` invocation: not
/// `debug_assert_eq!` (compiled out in release tests), not a crate's own
/// `*_assert_eq!`, not a path-qualified or repeated one.
fn is_plain_assert_eq(text: &str) -> bool {
    let masked = mask_comments_and_strings(text);
    let invocations = macro_invocations(&masked);
    let [(name, _)] = invocations.as_slice() else {
        return false;
    };
    *name == "assert_eq"
        && masked
            .find("assert_eq")
            .is_some_and(|offset| !masked[..offset].trim_end().ends_with(':'))
}

/// Whether a macro other than a known non-binding one mentions `name` in
/// its arguments: `let_assert!(Ok(p) = ..)` and similar macros bind
/// patterns ripr does not read.
fn bound_by_macro(masked: &str, name: &str) -> bool {
    macro_invocations(masked)
        .into_iter()
        .filter(|(macro_name, _)| !NON_RETURNING_MACROS.contains(macro_name))
        .any(|(_, delimiter)| {
            let (open, close) = match masked.as_bytes()[delimiter] {
                b'(' => (b'(', b')'),
                b'[' => (b'[', b']'),
                _ => (b'{', b'}'),
            };
            let end = matching_close(masked, delimiter, open, close).unwrap_or(masked.len());
            contains_as_whole_word(&masked[delimiter..end], name)
        })
}

/// Whether the file renames some item to `name` (`use a::b as name;`), so
/// `name` may not be the item it looks like.
fn file_renames_to(source: &str, name: &str) -> bool {
    if !source.contains(name) {
        return false;
    }
    let masked = mask_comments_and_strings(source);
    whole_word_offsets(&masked, "as")
        .into_iter()
        .any(|offset| starts_with_word(masked[offset + "as".len()..].trim_start(), name))
}

/// Whether the file declares a type alias `type name`.
fn file_aliases_type(source: &str, name: &str) -> bool {
    if !source.contains(name) {
        return false;
    }
    let masked = mask_comments_and_strings(source);
    whole_word_offsets(&masked, "type")
        .into_iter()
        .any(|offset| starts_with_word(masked[offset + "type".len()..].trim_start(), name))
}

/// Whether another workspace definition of the owner's name could take a
/// call by that name. A bare call competes with every other module-level
/// function of the name; a method call competes with every other method of
/// the name that has a body (overrides, inherent methods of other types,
/// other traits' methods), except a pure `(**self).name(..)` forward, which
/// dispatches to the same method on the pointee. A definition whose item
/// container is unknown (lexical fallback) always competes, and so does a
/// `fn name` the parser never indexed (inside a `macro_rules!` body).
fn other_definition_competes(owner: &FunctionSummary, index: &RustIndex, method: bool) -> bool {
    let name = owner.name.as_str();
    let is_owner = |file: &PathBuf, line: usize| *file == owner.file && line == owner.start_line;
    let indexed_competes = index.functions().iter().any(|function| {
        if function.name != name || is_owner(&function.file, function.start_line) {
            return false;
        }
        match function.item.container {
            FunctionContainer::Unknown => true,
            FunctionContainer::Local => false,
            FunctionContainer::Free => !method,
            _ => {
                method
                    && function.item.has_self_param
                    && function.item.has_body
                    && !is_self_forward(&function.body, name)
            }
        }
    });
    if indexed_competes {
        return true;
    }
    index.files().iter().any(|(path, facts)| {
        // Masking only erases text, so a file whose raw source has no
        // `fn <name>` has none after masking either; skip the mask.
        if !facts.source.contains(name) || fn_definition_offsets(&facts.source, name).is_empty() {
            return false;
        }
        let masked = mask_comments_and_strings(&facts.source);
        fn_definition_offsets(&masked, name)
            .into_iter()
            .any(|offset| {
                let line = masked[..offset]
                    .bytes()
                    .filter(|byte| *byte == b'\n')
                    .count()
                    + 1;
                let indexed = facts
                    .functions
                    .iter()
                    .any(|function| function.name == name && function.start_line == line)
                    || is_owner(path, line);
                if indexed {
                    return false;
                }
                let Some(definition) = unindexed_definition(&facts.source, &masked, offset) else {
                    return true;
                };
                match definition.body {
                    None => false,
                    Some(body) => definition.has_self == method && !is_self_forward(body, name),
                }
            })
    })
}

struct UnindexedDefinition<'a> {
    has_self: bool,
    body: Option<&'a str>,
}

/// The parameter receiver and body of a `fn` definition the parser did not
/// index, read from its text.
fn unindexed_definition<'a>(
    source: &'a str,
    masked: &str,
    offset: usize,
) -> Option<UnindexedDefinition<'a>> {
    let params = offset + masked[offset..].find('(')?;
    let params_close = matching_close(masked, params, b'(', b')')?;
    let first_param = masked[params + 1..params_close]
        .split(',')
        .next()
        .unwrap_or("")
        .trim();
    let receiver = first_param.trim_start_matches('&').trim_start();
    let receiver = if receiver.starts_with('\'') {
        receiver
            .split_once(char::is_whitespace)
            .map_or("", |(_, rest)| rest.trim_start())
    } else {
        receiver
    };
    let receiver = receiver
        .strip_prefix("mut ")
        .map_or(receiver, str::trim_start);
    let has_self =
        receiver == "self" || receiver.starts_with("self:") || receiver.starts_with("self ");
    let mut depth = 0usize;
    for (relative, byte) in masked[params_close..].bytes().enumerate() {
        match byte {
            b'(' | b'[' => depth += 1,
            b')' | b']' => depth = depth.saturating_sub(1),
            b';' if depth == 0 => {
                return Some(UnindexedDefinition {
                    has_self,
                    body: None,
                });
            }
            b'{' if depth == 0 => {
                let open = params_close + relative;
                let close = matching_close(masked, open, b'{', b'}')?;
                return Some(UnindexedDefinition {
                    has_self,
                    body: Some(&source[open..=close]),
                });
            }
            _ => {}
        }
    }
    None
}

/// Whether `body` only forwards to the same method on the pointee:
/// `{ (**self).name(..) }` or `{ (*self).name(..) }`.
fn is_self_forward(body: &str, name: &str) -> bool {
    let masked = mask_comments_and_strings(body);
    let Some(open) = masked.find('{') else {
        return false;
    };
    let Some(close) = matching_close(&masked, open, b'{', b'}') else {
        return false;
    };
    let inner = body[open + 1..close].trim();
    ["(**self).", "(*self)."].iter().any(|prefix| {
        inner
            .strip_prefix(prefix)
            .is_some_and(|call| matches!(owner_call_shape(call, name), Some(CallShape::Bare)))
    })
}

/// Offsets of the `fn` keyword in every `fn <name>` definition.
fn fn_definition_offsets(masked: &str, name: &str) -> Vec<usize> {
    whole_word_offsets(masked, "fn")
        .into_iter()
        .filter(|offset| {
            let rest = masked[offset + 2..].trim_start();
            rest.strip_prefix(name).is_some_and(|after| {
                let after = after.trim_start();
                after.starts_with('(') || after.starts_with('<')
            })
        })
        .collect()
}

/// The receiver type an `impl` block's self type names, when it is one this
/// module can match a test binding against.
fn declared_receiver(self_ty: &str, index: &RustIndex) -> Option<ReceiverType> {
    if is_byte_slice_type(self_ty) {
        return Some(ReceiverType::ByteSlice);
    }
    if self_ty.starts_with(['&', '[', '(', '*']) || self_ty.starts_with("dyn ") {
        return None;
    }
    let base = path_base_name(self_ty)?;
    type_declared_in_workspace(base, index).then(|| ReceiverType::Named(base.to_string()))
}

/// Every receiver type with an `impl .. <trait_name> for <type>` block in
/// the workspace.
fn trait_impl_receivers(trait_name: &str, index: &RustIndex) -> Vec<ReceiverType> {
    let mut receivers = Vec::new();
    for facts in index.files().values() {
        if whole_word_offsets(&facts.source, trait_name).is_empty() {
            continue;
        }
        let masked = mask_comments_and_strings(&facts.source);
        for offset in whole_word_offsets(&masked, "impl") {
            let Some(header_end) = masked[offset..].find(['{', ';']) else {
                continue;
            };
            let header = collapse_whitespace(&masked[offset + "impl".len()..offset + header_end]);
            let header = strip_leading_generics(&header);
            let Some((trait_path, self_ty)) = header.split_once(" for ") else {
                continue;
            };
            let self_ty = self_ty.split(" where ").next().unwrap_or(self_ty).trim();
            if path_base_name(trait_path.trim()) != Some(trait_name) {
                continue;
            }
            if let Some(receiver) = declared_receiver(self_ty, index)
                && !receivers.contains(&receiver)
            {
                receivers.push(receiver);
            }
        }
    }
    receivers
}

fn strip_leading_generics(header: &str) -> &str {
    let header = header.trim_start();
    if !header.starts_with('<') {
        return header;
    }
    let mut depth = 0usize;
    for (offset, byte) in header.bytes().enumerate() {
        match byte {
            b'<' => depth += 1,
            b'>' => {
                depth = depth.saturating_sub(1);
                if depth == 0 {
                    return header[offset + 1..].trim_start();
                }
            }
            _ => {}
        }
    }
    header
}

fn type_declared_in_workspace(name: &str, index: &RustIndex) -> bool {
    let declares = |text: &str| {
        ["struct", "enum", "union"].iter().any(|keyword| {
            whole_word_offsets(text, keyword)
                .into_iter()
                .any(|offset| starts_with_word(text[offset + keyword.len()..].trim_start(), name))
        })
    };
    // The raw check is a superset of the masked one; mask only on a hit.
    index.files().values().any(|facts| {
        facts.source.contains(name)
            && declares(&facts.source)
            && declares(&mask_comments_and_strings(&facts.source))
    })
}

/// The type the test binds `receiver` to: every `let` that binds the name
/// is a simple `let [mut] receiver [: T] = ..;` whose type ripr can read,
/// and all of them agree. Other uses of the binding (borrows, arguments,
/// reassignments) cannot change a Rust binding's type; another binding of
/// the same name in a pattern ripr does not read (a closure parameter, a
/// `for` or match-arm pattern, a destructuring `let`, a nested `fn`)
/// leaves the type unestablished.
fn test_receiver_type(
    test: &TestSummary,
    receiver: &str,
    test_source: Option<&str>,
    index: &RustIndex,
    imports_foreign: ForeignImport<'_>,
) -> Option<ReceiverType> {
    let masked = mask_comments_and_strings(&test.body);
    if binds_outside_let(&masked, receiver) {
        return None;
    }
    let mut bound: Option<ReceiverType> = None;
    for offset in whole_word_offsets(&masked, "let") {
        let pattern_start = offset + "let".len();
        let Some(relative_end) = top_level_semicolon(&masked[pattern_start..]) else {
            // A `let` ripr cannot bound (an `if let` closing its block):
            // its pattern may still bind the name.
            let rest = &masked[pattern_start..];
            let end = rest.find(['=', '{']).unwrap_or(rest.len());
            if contains_as_whole_word(&rest[..end], receiver) {
                return None;
            }
            continue;
        };
        let statement_end = pattern_start + relative_end;
        let statement = &masked[pattern_start..statement_end];
        let pattern_end = statement
            .match_indices('=')
            .map(|(position, _)| position)
            .find(|position| {
                !matches!(statement.as_bytes().get(position + 1), Some(b'=' | b'>'))
                    && !matches!(
                        statement.as_bytes().get(position.wrapping_sub(1)),
                        Some(b'=' | b'!' | b'<' | b'>')
                    )
            })
            .unwrap_or(statement.len());
        if !contains_as_whole_word(&statement[..pattern_end], receiver) {
            continue;
        }
        let pattern = statement[..pattern_end].trim();
        let pattern = pattern
            .strip_prefix("mut ")
            .map_or(pattern, str::trim_start);
        let annotation = pattern.strip_prefix(receiver)?.trim_start();
        if !(annotation.is_empty() || annotation.starts_with(':')) {
            return None;
        }
        let binding = &test.body[pattern_start..statement_end];
        let binding = &binding[binding.find(receiver)? + receiver.len()..];
        let receiver_type = binding_type(binding, test, test_source, index, imports_foreign)?;
        match &bound {
            None => bound = Some(receiver_type),
            Some(existing) if *existing == receiver_type => {}
            Some(_) => return None,
        }
    }
    bound
}

/// Whether `name` may be bound by a pattern that is not a `let`: a closure
/// parameter list, a `for` pattern, a match arm, the test's own or a
/// nested `fn`'s parameters. Lexical and conservative: a `|` operator or an unrelated
/// match arm that mentions the name also counts.
fn binds_outside_let(masked: &str, name: &str) -> bool {
    let fns = whole_word_offsets(masked, "fn");
    if fns.len() > 1 {
        return true;
    }
    // The test's own parameters (`#[case] name: T`) bind the name too.
    let parameters = fns.first().and_then(|offset| {
        let open = offset + masked[*offset..].find('(')?;
        let close = matching_close(masked, open, b'(', b')')?;
        Some(&masked[open..close])
    });
    if parameters.is_none_or(|parameters| contains_as_whole_word(parameters, name)) {
        return true;
    }
    let bytes = masked.as_bytes();
    let pipes = bytes
        .iter()
        .enumerate()
        .filter(|(offset, byte)| {
            **byte == b'|'
                && bytes.get(offset + 1) != Some(&b'|')
                && (*offset == 0 || bytes[offset - 1] != b'|')
        })
        .map(|(offset, _)| offset)
        .collect::<Vec<_>>();
    // Every region between two consecutive pipes: a `|` operator must not
    // shift a closure's parameter list out of the pairing.
    if pipes
        .windows(2)
        .any(|pair| contains_as_whole_word(&masked[pair[0]..pair[1]], name))
    {
        return true;
    }
    let for_pattern = whole_word_offsets(masked, "for").into_iter().any(|offset| {
        let rest = &masked[offset + "for".len()..];
        let end = whole_word_offsets(rest, "in")
            .first()
            .copied()
            .unwrap_or(rest.len());
        contains_as_whole_word(&rest[..end], name)
    });
    if for_pattern {
        return true;
    }
    masked.match_indices("=>").any(|(arrow, _)| {
        let start = masked[..arrow]
            .rfind(['{', ',', '}'])
            .map_or(0, |position| position + 1);
        contains_as_whole_word(&masked[start..arrow], name)
    })
}

/// The type of one `let <receiver> ...;` binding: its annotation, or a
/// constructor-shaped initializer.
fn binding_type(
    binding: &str,
    test: &TestSummary,
    test_source: Option<&str>,
    index: &RustIndex,
    imports_foreign: ForeignImport<'_>,
) -> Option<ReceiverType> {
    let binding = binding.trim();
    let (annotation, initializer) = if let Some(rest) = binding.strip_prefix(':') {
        let (annotation, initializer) = rest.split_once('=')?;
        (Some(annotation.trim()), initializer.trim())
    } else {
        (None, binding.strip_prefix('=')?.trim())
    };
    if let Some(annotation) = annotation {
        return named_or_slice(annotation, test, test_source, imports_foreign);
    }
    if is_byte_slice_expression(initializer) {
        return Some(ReceiverType::ByteSlice);
    }
    let (initializer, unwrapped) = strip_unwrap(initializer);
    let type_end = initializer
        .find(|character: char| !(character.is_ascii_alphanumeric() || character == '_'))?;
    let type_name = &initializer[..type_end];
    let rest = &initializer[type_end..];
    let constructor = if let Some(call) = rest.strip_prefix("::") {
        let call_end =
            call.find(|character: char| !(character.is_ascii_alphanumeric() || character == '_'))?;
        let masked = mask_comments_and_strings(&call[call_end..]);
        masked.starts_with('(')
            && matching_close(&masked, 0, b'(', b')')
                .is_some_and(|closing| masked[closing + 1..].trim().is_empty())
            && constructor_returns_self(type_name, &call[..call_end], unwrapped, index)
    } else {
        let rest = rest.trim_start();
        let (open, close) = if rest.starts_with('{') {
            (b'{', b'}')
        } else {
            (b'(', b')')
        };
        let masked = mask_comments_and_strings(rest);
        !unwrapped
            && masked.as_bytes().first() == Some(&open)
            && matching_close(&masked, 0, open, close)
                .is_some_and(|closing| masked[closing + 1..].trim().is_empty())
    };
    if !constructor {
        return None;
    }
    named_or_slice(type_name, test, test_source, imports_foreign)
}

/// The initializer without a trailing `?`, `.unwrap()` or `.expect(..)`,
/// and whether one was there.
fn strip_unwrap(initializer: &str) -> (&str, bool) {
    let initializer = initializer.trim();
    if let Some(rest) = initializer
        .strip_suffix('?')
        .or_else(|| initializer.strip_suffix(".unwrap()"))
    {
        return (rest.trim_end(), true);
    }
    let masked = mask_comments_and_strings(initializer);
    if masked.ends_with(')')
        && let Some(position) = masked.rfind(".expect(")
        && matching_close(&masked, position + ".expect".len(), b'(', b')') == Some(masked.len() - 1)
    {
        return (initializer[..position].trim_end(), true);
    }
    (initializer, false)
}

/// Whether `type_name::constructor(..)` (unwrapped when `unwrapped`)
/// evaluates to a `type_name`. `default` and `from` return `Self` by their
/// traits' signatures and `try_from` returns `Result<Self, _>`; any other
/// associated function must be the type's one inherent definition of that
/// name, returning `Self` (or the type) directly, or inside
/// `Result`/`Option` when unwrapped.
fn constructor_returns_self(
    type_name: &str,
    constructor: &str,
    unwrapped: bool,
    index: &RustIndex,
) -> bool {
    match constructor {
        "default" | "from" => return !unwrapped,
        "try_from" => return unwrapped,
        _ => {}
    }
    let mut definitions = index.functions().iter().filter(|function| {
        function.name == constructor
            && !function.item.has_self_param
            && matches!(
                &function.item.container,
                FunctionContainer::Inherent { self_ty } if path_base_name(self_ty) == Some(type_name)
            )
    });
    let (Some(definition), None) = (definitions.next(), definitions.next()) else {
        return false;
    };
    let Some(returned) = declared_return_type(&definition.body) else {
        return false;
    };
    let names_type = |text: &str| {
        let text = text.trim();
        text == "Self" || path_base_name(text) == Some(type_name)
    };
    if unwrapped {
        ["Result<", "Option<"].iter().any(|wrapper| {
            returned
                .strip_prefix(wrapper)
                .and_then(|inner| inner.strip_suffix('>'))
                .is_some_and(|inner| names_type(inner.split(',').next().unwrap_or(inner)))
        })
    } else {
        names_type(&returned)
    }
}

/// The return type a `fn` definition declares, whitespace-collapsed.
fn declared_return_type(definition: &str) -> Option<String> {
    let masked = mask_comments_and_strings(definition);
    let params = masked.find('(')?;
    let params_close = matching_close(&masked, params, b'(', b')')?;
    let body_open = params_close + masked[params_close..].find('{')?;
    let signature = collapse_whitespace(&definition[params_close + 1..body_open]);
    let signature = signature.split(" where ").next().unwrap_or(&signature);
    Some(signature.trim().strip_prefix("->")?.trim().to_string())
}

fn named_or_slice(
    type_text: &str,
    test: &TestSummary,
    test_source: Option<&str>,
    imports_foreign: ForeignImport<'_>,
) -> Option<ReceiverType> {
    if is_byte_slice_type(type_text) {
        return Some(ReceiverType::ByteSlice);
    }
    let base = path_base_name(type_text)?;
    if !base.starts_with(|character: char| character.is_ascii_uppercase()) {
        return None;
    }
    // A test file that imports the name from outside the workspace, renames
    // another item to it, or aliases it binds a different type than the
    // workspace declaration.
    let source = test_source?;
    if imports_foreign(&test.file, base)
        || file_renames_to(source, base)
        || file_aliases_type(source, base)
    {
        return None;
    }
    Some(ReceiverType::Named(base.to_string()))
}

/// A trait's methods are callable with method syntax only while the trait
/// is in scope: the test's file imports it by name from the workspace, or
/// declares it.
fn trait_in_scope(source: &str, trait_name: &str, index: &RustIndex) -> bool {
    if file_imports_foreign_callee_name(source, trait_name, &index.package_names) {
        return false;
    }
    if file_imports_own_item(source, trait_name, &index.package_names) {
        return true;
    }
    let masked = mask_comments_and_strings(source);
    whole_word_offsets(&masked, "trait")
        .into_iter()
        .any(|offset| {
            masked[offset + "trait".len()..]
                .trim_start()
                .strip_prefix(trait_name)
                .is_some_and(|after| {
                    !after.starts_with(|character: char| {
                        character.is_ascii_alphanumeric() || character == '_'
                    })
                })
        })
}

fn test_body_shadows_owner(test: &TestSummary, owner: &str) -> bool {
    if fact_body_defines_callee_fn(&test.nested_fn_names, owner)
        || fact_body_let_shadow_line(&test.let_bindings, owner).is_some()
    {
        return true;
    }
    let masked = mask_comments_and_strings(&test.body);
    test_body_defines_callee_fn(&masked, owner)
        || test_body_let_shadow_line(&masked, owner).is_some()
}

fn is_byte_slice_type(text: &str) -> bool {
    let compact: String = text.split_whitespace().collect();
    let Some(rest) = compact.strip_prefix('&') else {
        return false;
    };
    let rest = match rest.strip_prefix('\'') {
        Some(lifetime) => lifetime.trim_start_matches(|character: char| {
            character.is_ascii_alphanumeric() || character == '_'
        }),
        None => rest,
    };
    rest == "[u8]"
}

/// `&[..][..]` or `&b".."[..]`: a byte-slice expression.
fn is_byte_slice_expression(initializer: &str) -> bool {
    let Some(rest) = initializer.trim().strip_prefix('&') else {
        return false;
    };
    let Some(array) = rest.trim_end().strip_suffix("[..]") else {
        return false;
    };
    let array = array.trim();
    if let Some(bytes) = array.strip_prefix("b\"") {
        return bytes.ends_with('"');
    }
    let masked = mask_comments_and_strings(array);
    masked.starts_with('[')
        && matching_close(&masked, 0, b'[', b']').is_some_and(|close| close + 1 == masked.len())
}

/// The last `::` segment of a path, without generic arguments.
fn path_base_name(path: &str) -> Option<&str> {
    let path = path.trim();
    let without_generics = path.split('<').next()?.trim();
    let base = without_generics.rsplit("::").next()?.trim();
    is_plain_identifier(base).then_some(base)
}

fn is_plain_identifier(text: &str) -> bool {
    text.starts_with(|character: char| character.is_ascii_alphabetic() || character == '_')
        && text
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || character == '_')
}

fn is_ident_byte(byte: u8) -> bool {
    byte.is_ascii_alphanumeric() || byte == b'_'
}

fn whole_word_offsets(text: &str, word: &str) -> Vec<usize> {
    let bytes = text.as_bytes();
    let mut offsets = Vec::new();
    let mut search = 0usize;
    while let Some(relative) = text[search..].find(word) {
        let offset = search + relative;
        let end = offset + word.len();
        let before_ok = offset == 0 || !is_ident_byte(bytes[offset - 1]);
        let after_ok = end >= bytes.len() || !is_ident_byte(bytes[end]);
        if before_ok && after_ok {
            offsets.push(offset);
        }
        search = end;
    }
    offsets
}

/// Offset of the first `;` outside brackets.
fn top_level_semicolon(masked: &str) -> Option<usize> {
    let mut depth = 0usize;
    for (offset, byte) in masked.bytes().enumerate() {
        match byte {
            b'(' | b'[' | b'{' => depth += 1,
            b')' | b']' | b'}' => depth = depth.checked_sub(1)?,
            b';' if depth == 0 => return Some(offset),
            _ => {}
        }
    }
    None
}

/// The offset of the bracket closing the one at `opening`, in masked text.
fn matching_close(masked: &str, opening: usize, open: u8, close: u8) -> Option<usize> {
    let bytes = masked.as_bytes();
    if bytes.get(opening) != Some(&open) {
        return None;
    }
    let mut depth = 0usize;
    for (offset, byte) in bytes.iter().enumerate().skip(opening) {
        if *byte == open {
            depth += 1;
        } else if *byte == close {
            depth = depth.checked_sub(1)?;
            if depth == 0 {
                return Some(offset);
            }
        }
    }
    None
}

fn collapse_whitespace(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// Method names `&[u8]` resolves before a workspace trait's method: the
/// inherent methods of slices and byte slices, and the methods of prelude
/// and `std::io` traits implemented for them. A byte-slice receiver never
/// credits a pin through one of these names.
const BYTE_SLICE_METHODS: &[&str] = &[
    "align_to",
    "align_to_mut",
    "array_chunks",
    "array_windows",
    "as_array",
    "as_ascii",
    "as_chunks",
    "as_flattened",
    "as_mut",
    "as_mut_ptr",
    "as_mut_ptr_range",
    "as_ptr",
    "as_ptr_range",
    "as_rchunks",
    "as_ref",
    "as_simd",
    "binary_search",
    "binary_search_by",
    "binary_search_by_key",
    "borrow",
    "by_ref",
    "bytes",
    "chain",
    "chunk_by",
    "chunks",
    "chunks_exact",
    "clone",
    "clone_from",
    "cmp",
    "concat",
    "connect",
    "consume",
    "contains",
    "copy_from_slice",
    "copy_within",
    "element_offset",
    "ends_with",
    "eq",
    "eq_ignore_ascii_case",
    "escape_ascii",
    "fill",
    "fill_buf",
    "fill_with",
    "first",
    "first_chunk",
    "fmt",
    "ge",
    "get",
    "get_mut",
    "get_unchecked",
    "gt",
    "hash",
    "into",
    "into_iter",
    "is_ascii",
    "is_empty",
    "is_sorted",
    "is_sorted_by",
    "is_sorted_by_key",
    "iter",
    "join",
    "last",
    "last_chunk",
    "le",
    "len",
    "lines",
    "lt",
    "make_ascii_lowercase",
    "make_ascii_uppercase",
    "max",
    "min",
    "ne",
    "partial_cmp",
    "partition_point",
    "rchunks",
    "rchunks_exact",
    "read",
    "read_buf",
    "read_exact",
    "read_line",
    "read_to_end",
    "read_to_string",
    "read_until",
    "read_vectored",
    "repeat",
    "reverse",
    "rotate_left",
    "rotate_right",
    "rsplit",
    "rsplit_once",
    "rsplitn",
    "select_nth_unstable",
    "skip_until",
    "sort",
    "sort_by",
    "sort_by_cached_key",
    "sort_by_key",
    "sort_unstable",
    "sort_unstable_by",
    "sort_unstable_by_key",
    "split",
    "split_at",
    "split_at_checked",
    "split_first",
    "split_first_chunk",
    "split_inclusive",
    "split_last",
    "split_last_chunk",
    "split_off",
    "split_off_first",
    "split_off_last",
    "split_once",
    "splitn",
    "starts_with",
    "strip_prefix",
    "strip_suffix",
    "subslice_range",
    "swap",
    "swap_with_slice",
    "take",
    "to_ascii_lowercase",
    "to_ascii_uppercase",
    "to_owned",
    "to_vec",
    "trim_ascii",
    "trim_ascii_end",
    "trim_ascii_start",
    "trim_prefix",
    "trim_suffix",
    "try_into",
    "type_id",
    "utf8_chunks",
    "windows",
];

/// Methods of prelude traits that take `self` by value. Method lookup
/// tries the receiver type itself before `&T`, so for a receiver type that
/// implements the trait (`Iterator`, `IntoIterator`, `Into`), one of these
/// takes the call before an inherent `&self` method of the same name. ripr
/// cannot see which std traits a workspace type implements (derives,
/// blanket impls), so a named receiver never credits a pin through these
/// names.
const BY_VALUE_PRELUDE_METHODS: &[&str] = &[
    "all",
    "any",
    "chain",
    "clamp",
    "cloned",
    "collect",
    "copied",
    "count",
    "cycle",
    "enumerate",
    "filter",
    "filter_map",
    "find",
    "find_map",
    "flat_map",
    "flatten",
    "fold",
    "for_each",
    "fuse",
    "inspect",
    "into",
    "into_iter",
    "is_sorted",
    "is_sorted_by",
    "is_sorted_by_key",
    "last",
    "map",
    "map_while",
    "max",
    "max_by",
    "max_by_key",
    "min",
    "min_by",
    "min_by_key",
    "nth",
    "partition",
    "peekable",
    "position",
    "product",
    "reduce",
    "rev",
    "rfind",
    "rfold",
    "rposition",
    "scan",
    "size_hint",
    "skip",
    "skip_while",
    "step_by",
    "sum",
    "take",
    "take_while",
    "try_fold",
    "try_for_each",
    "try_into",
    "unzip",
    "zip",
];

#[cfg(test)]
mod tests;
