//! Owner-return pins (#4478): an `assert_eq!` whose operand is a call of
//! the changed owner pins the owner's whole return value, so it observes a
//! changed `return_value` expression without sharing a token with it.
//!
//! Crediting that assertion is only sound when three facts hold, and each
//! gate below fails closed when ripr cannot establish one:
//!
//! 1. The call names the owner. A bare `name(..)` names a module-level
//!    function, never an associated function or a trait method. A method
//!    call `recv.name(..)` names a function with a `self` receiver, and only
//!    when the receiver's type dispatches to the owner: the test binds the
//!    receiver to a type ripr can read, that type reaches the owner's `impl`
//!    or trait, and no other definition of `name` in the workspace could
//!    take the call instead.
//! 2. The call's return value came through the changed expression. The
//!    changed expression must be the owner's tail and must evaluate all of
//!    its parts on every input (no closure, `&&`/`||`, branch, or skipping
//!    combinator such as `map_or`). When the owner has other
//!    exits (`?`, `return`), the changed expression must be the owner's only
//!    `Ok(..)` (or `Some(..)`) constructor and the pinned value must be that
//!    constructor too: an `Err(..)` pin observes an early exit that never
//!    evaluates the changed `Ok(..)`.
//! 3. The pinned value is the whole return value: one plain `assert_eq!`
//!    in the test's own body with the call as a complete operand, nothing
//!    chained after it, and an expected value that does not call the owner
//!    again. `assert_ne!`, `debug_assert_eq!` and a `#[should_panic]` test
//!    pin nothing. Its exact parser context must also establish an eager
//!    statement path (or a directly invoked bounded closure), and no visible
//!    workspace macro definition/import may compete with `assert_eq!`.
//!    Deferred, conditional and ambiguous contexts do not supply this pin.
//!
//! This is bounded syntax, not name resolution. The documented residuals:
//! methods generated by derive or attribute macros are invisible, a
//! `macro_rules!` body that defines the method counts only when ripr can
//! read its `fn` text, and an out-of-workspace trait in scope that also
//! names the method is not detected.

use super::super::rust_index::{FunctionSummary, OracleFact, RustIndex, TestSummary};
use super::reveal::{
    assertion_comparison_operands, contains_as_whole_word, file_imports_foreign_callee_name,
    file_imports_own_item, file_use_statements, use_statement_first_segment,
};
use crate::analysis::extract::{
    fact_body_defines_callee_fn, fact_body_let_shadow_line, mask_comments_and_strings,
    outer_assertion_condition, test_body_defines_callee_fn, test_body_let_shadow_line,
};
use crate::analysis::facts::{FunctionContainer, SourceRoleProvenanceEdgeKind};
use crate::analysis::syntax::fn_signature::{LocalTypeEquality, local_type_equality};
use crate::analysis::syntax::{
    OwnerPinAssertions, empty_macro_binding_ambiguities, local_empty_macro_names,
    macro_binding_scan, owner_pin_assertions, trusted_macro_binding_ambiguities,
};
use crate::domain::{Probe, ProbeFamily};
use rayon::prelude::*;
use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

/// The owner-side half of the pin, established once per probe.
pub(in crate::analysis) struct OwnerReturnPin {
    name: String,
    call: PinCall,
    path: ReturnPathGate,
    /// The owner declares `-> bool`, so `assert!(owner(..))` pins its whole
    /// return value to `true` and `assert!(!owner(..))` to `false`.
    returns_bool: bool,
    /// Per test file: whether the owner's trait is in scope. The trait is
    /// fixed per pin and the scan masks the whole file, so it runs once.
    trait_scope_by_file: RefCell<BTreeMap<PathBuf, bool>>,
}

/// Run-scoped syntax decisions shared by every probe against one index.
/// No cache outlives that immutable index; no public/file facts are changed.
#[derive(Clone, Debug, Default)]
pub(in crate::analysis) struct OwnerPinSyntax {
    ambiguous_macro_bindings: RefCell<Option<BTreeSet<String>>>,
    by_file: RefCell<BTreeMap<PathBuf, OwnerPinAssertions>>,
    empty_macro_ambiguities: RefCell<BTreeMap<PathBuf, BTreeSet<String>>>,
    withheld: WithheldMacroBindings,
}

/// The macro bindings of files a narrowed diff index withheld (#5320).
/// The ambiguity unions below run over every indexed file, so the withheld
/// files' share is folded in to keep the decision the full selection made.
/// Name-specific empty-macro bindings need no entry here: the diff scope
/// admits every file that spells a test file's local empty-macro name.
#[derive(Clone, Debug, Default)]
pub(in crate::analysis) struct WithheldMacroBindings {
    /// Some withheld file may shadow any macro name.
    any_name: bool,
    /// Trusted macro names withheld files may shadow.
    trusted: BTreeSet<String>,
}

impl WithheldMacroBindings {
    /// Fold one withheld file in. Returns `true` once nothing further can
    /// change the result, so the caller can stop reading.
    pub(in crate::analysis) fn absorb(
        &mut self,
        source: &str,
        packages: &BTreeSet<String>,
    ) -> bool {
        if self.any_name {
            return true;
        }
        match macro_binding_scan(source, packages, NON_RETURNING_MACROS, &BTreeSet::new()) {
            Some(names) => self.trusted.extend(names),
            None => {
                self.any_name = true;
                self.trusted = NON_RETURNING_MACROS
                    .iter()
                    .map(|name| (*name).to_string())
                    .collect();
            }
        }
        self.any_name
    }
}

impl OwnerPinSyntax {
    /// Fold in the macro bindings of files the diff index withheld.
    pub(in crate::analysis) fn with_withheld(mut self, withheld: WithheldMacroBindings) -> Self {
        self.withheld = withheld;
        self
    }

    /// Shared equality-oracle admission for the bounded supported families.
    /// Execution provenance is independent of the error/boundary/value matcher.
    /// Applicability is the invocation
    /// identity, not the more restrictive owner-pin operand shape, so token
    /// matches and nested diagnostic syntax cannot bypass the same refusal.
    pub(in crate::analysis) fn admits_equality_assertion(
        &self,
        probe: &Probe,
        test: &TestSummary,
        assertion: &OracleFact,
        index: &RustIndex,
    ) -> bool {
        !matches!(
            probe.family,
            ProbeFamily::ReturnValue | ProbeFamily::ErrorPath | ProbeFamily::Predicate
        ) || !is_bare_assert_eq_invocation(&assertion.text)
            || self.admits(test, assertion, index)
    }

    fn admits(&self, test: &TestSummary, assertion: &OracleFact, index: &RustIndex) -> bool {
        let mut ambiguous = self.ambiguous_macro_bindings.borrow_mut();
        let ambiguous = ambiguous.get_or_insert_with(|| {
            let mut ambiguous = trusted_macro_ambiguities_in(index);
            ambiguous.extend(self.withheld.trusted.iter().cloned());
            ambiguous
        });
        let Some(facts) = index
            .files()
            .get(&test.file)
            .filter(|facts| !facts.used_lexical_fallback)
        else {
            return false;
        };
        if facts.role_provenance.earliest_unresolved_reason.is_some() {
            return false;
        }
        let mut empty_by_file = self.empty_macro_ambiguities.borrow_mut();
        let empty_ambiguities = empty_by_file.entry(test.file.clone()).or_insert_with(|| {
            let names = local_empty_macro_names(&facts.source);
            if names.is_empty() {
                return BTreeSet::new();
            }
            index
                .files()
                .iter()
                .flat_map(|(path, file)| {
                    empty_macro_binding_ambiguities(
                        &file.source,
                        &index.package_names,
                        &names,
                        path == &test.file,
                    )
                })
                .chain(
                    self.withheld
                        .any_name
                        .then(|| names.clone())
                        .into_iter()
                        .flatten(),
                )
                .collect()
        });
        let ambiguous: BTreeSet<_> = ambiguous.union(empty_ambiguities).cloned().collect();
        let mut by_file = self.by_file.borrow_mut();
        for edge in &facts.role_provenance.edges {
            // Module composition already owns resolution. Include expansions
            // lack an exact declaration coordinate here, so remain unknown.
            if edge.kind != SourceRoleProvenanceEdgeKind::Module {
                return false;
            }
            let Some(parent) = index
                .files()
                .get(&edge.parent)
                .filter(|facts| !facts.used_lexical_fallback)
            else {
                return false;
            };
            if !by_file
                .entry(edge.parent.clone())
                .or_insert_with(|| owner_pin_assertions(&parent.source, NON_RETURNING_MACROS))
                .admits_module_declaration(edge.line, &edge.declaration)
            {
                return false;
            }
        }
        by_file
            .entry(test.file.clone())
            .or_insert_with(|| owner_pin_assertions(&facts.source, NON_RETURNING_MACROS))
            .admits(
                (test.start_line, test.end_line, &test.name),
                &test.body,
                (assertion.line, &assertion.text),
                &ambiguous,
            )
    }
}

/// Trusted macro names some workspace file may rebind.
///
/// Parses workspace files, so on a warm `ripr check` of a large workspace
/// this scan dominated wall time (37% on ripr-swarm). Files are independent
/// and the result is a set, so the scan runs on the rayon pool with an
/// order-independent answer.
fn trusted_macro_ambiguities_in(index: &RustIndex) -> BTreeSet<String> {
    let scan = |sources: &[&str]| -> BTreeSet<String> {
        sources
            .par_iter()
            .flat_map_iter(|source| {
                trusted_macro_binding_ambiguities(
                    source,
                    &index.package_names,
                    NON_RETURNING_MACROS,
                )
            })
            .collect()
    };
    // One foreign glob import, `#[macro_use]` or unparsable file makes
    // every trusted name ambiguous, and most workspaces have one. Scan
    // the files that can do that first; once every name is ambiguous
    // the other files cannot change the union, so they are skipped.
    let (likely, rest): (Vec<&str>, Vec<&str>) = index
        .files()
        .values()
        .map(|facts| facts.data().source.as_str())
        .partition(|source| may_saturate_macro_ambiguity(source));
    let mut ambiguous = scan(&likely);
    if ambiguous.len() < NON_RETURNING_MACROS.len() {
        ambiguous.extend(scan(&rest));
    }
    ambiguous
}

/// Scan-order hint for the trusted-macro ambiguity scan, never its answer:
/// a glob import not rooted at `super`/`self`/`crate`, `#[macro_use]` or
/// `no_implicit_prelude`. `use super::*;` in nearly every test module is
/// workspace-owned and would otherwise put every file first.
fn may_saturate_macro_ambiguity(source: &str) -> bool {
    source.contains("macro_use")
        || source.contains("no_implicit_prelude")
        || source.match_indices("::*").any(|(offset, _)| {
            let before = source[..offset].trim_end_matches(|character: char| {
                character.is_ascii_alphanumeric() || character == '_'
            });
            !matches!(&source[before.len()..offset], "super" | "self" | "crate")
        })
}

/// Whether a test file imports a name from outside the workspace; the
/// caller supplies its run-scoped memo.
pub(in crate::analysis) type ForeignImport<'a> = &'a dyn Fn(&Path, &str) -> bool;

enum PinCall {
    /// `name(..)`: the owner is a module-level function.
    Bare,
    /// `recv.name(..)`: the receiver's type must be one of `receivers`, and
    /// a trait method also needs its trait in the test's scope.
    Method {
        receivers: Vec<ReceiverType>,
        trait_scope: Option<TraitScope>,
    },
}

/// A trait method is callable with method syntax only while its trait is
/// in scope.
struct TraitScope {
    trait_name: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
enum ReceiverType {
    /// A struct, enum or union declared in the workspace.
    Named(String),
    /// `&[u8]`, read from `&[..][..]` or `&b".."[..]`.
    ByteSlice,
}

enum ReturnPathGate {
    /// The changed expression is the owner's only exit.
    Any,
    /// The pinned value must start with this constructor.
    Head(&'static str),
    /// #6692: a field of a hand-written `Clone::clone`'s returned struct
    /// literal. The pinned value must be the clone's own receiver
    /// (`assert_eq!(w.clone(), w)`), compared through a derived
    /// `PartialEq`, so every field of the clone is compared with the
    /// original's.
    CloneReceiver,
}

impl OwnerReturnPin {
    /// The owner-side gates: `None` when the probe is not a return value,
    /// the owner's declaration or return paths are not established, or
    /// another workspace definition could take a call by the owner's name.
    pub(in crate::analysis) fn establish(
        probe: &Probe,
        owner: &FunctionSummary,
        index: &RustIndex,
    ) -> Option<Self> {
        if matches!(probe.family, ProbeFamily::FieldConstruction) {
            return Self::establish_clone_field(probe, owner, index);
        }
        if !owner.item.has_body {
            return None;
        }
        let returns_bool = declared_return_type(&owner.body).as_deref() == Some("bool");
        // A predicate that is a bool owner's whole tail is the owner's return
        // value, so the same pin observes it.
        match probe.family {
            ProbeFamily::ReturnValue => {}
            ProbeFamily::Predicate if returns_bool => {}
            _ => return None,
        }
        let parser_backed = index
            .files()
            .get(&owner.file)
            .is_some_and(|facts| !facts.used_lexical_fallback);
        if !parser_backed {
            return None;
        }
        let name = owner.name.as_str();
        let changed_line = probe.location.line.checked_sub(owner.start_line)?;
        let path = return_path_gate(&owner.body, &probe.expression, changed_line)?;
        let call = match (&owner.item.container, owner.item.has_self_param) {
            (FunctionContainer::Free, false) => PinCall::Bare,
            (FunctionContainer::Inherent { self_ty }, true) => PinCall::Method {
                receivers: vec![declared_receiver(self_ty, index)?],
                trait_scope: None,
            },
            (
                FunctionContainer::TraitImpl {
                    trait_path,
                    self_ty,
                },
                true,
            ) => PinCall::Method {
                receivers: vec![declared_receiver(self_ty, index)?],
                trait_scope: Some(TraitScope {
                    trait_name: path_base_name(trait_path)?.to_string(),
                }),
            },
            (FunctionContainer::Trait { trait_name }, true) => {
                let receivers = trait_impl_receivers(trait_name, index);
                if receivers.is_empty() {
                    return None;
                }
                PinCall::Method {
                    receivers,
                    trait_scope: Some(TraitScope {
                        trait_name: trait_name.clone(),
                    }),
                }
            }
            _ => return None,
        };
        let method = matches!(call, PinCall::Method { .. });
        if other_definition_competes(owner, index, method) {
            return None;
        }
        Some(Self {
            name: name.to_string(),
            call,
            path,
            returns_bool,
            trait_scope_by_file: RefCell::default(),
        })
    }

    /// #6692: the owner-side gates for a `field_construction` probe in a
    /// hand-written `impl Clone for T`. Established only when the changed
    /// line is a field of the struct literal that is `clone`'s only exit,
    /// `T` is declared once in the workspace with `#[derive(PartialEq)]`
    /// and has no hand-written `PartialEq` impl, no workspace trait is
    /// named `Clone`, and no other `fn clone` with a receiver competes.
    /// The test-side gate then requires `assert_eq!(recv.clone(), recv)`.
    fn establish_clone_field(
        probe: &Probe,
        owner: &FunctionSummary,
        index: &RustIndex,
    ) -> Option<Self> {
        if owner.name != "clone" || !owner.item.has_body || !owner.item.has_self_param {
            return None;
        }
        let FunctionContainer::TraitImpl {
            trait_path,
            self_ty,
        } = &owner.item.container
        else {
            return None;
        };
        if path_base_name(trait_path) != Some("Clone") {
            return None;
        }
        let parser_backed = index
            .files()
            .get(&owner.file)
            .is_some_and(|facts| !facts.used_lexical_fallback);
        if !parser_backed {
            return None;
        }
        let receiver = declared_receiver(self_ty, index)?;
        let ReceiverType::Named(type_name) = &receiver else {
            return None;
        };
        let changed_line = probe.location.line.checked_sub(owner.start_line)?;
        let field = initialized_field_name(&probe.expression)?;
        if !clone_tail_literal_spans(&owner.body, type_name, changed_line, &probe.expression)
            || !field_compares_with_derived_equality(type_name, field, index)
            || workspace_declares_trait(index, "Clone")
            || other_definition_competes(owner, index, true)
        {
            return None;
        }
        Some(Self {
            name: owner.name.clone(),
            call: PinCall::Method {
                receivers: vec![receiver],
                // `Clone` is in the prelude; a workspace `trait Clone` is
                // refused above and a foreign import in `admits`.
                trait_scope: None,
            },
            path: ReturnPathGate::CloneReceiver,
            returns_bool: false,
            trait_scope_by_file: RefCell::default(),
        })
    }

    /// The test-side gates: whether `assertion` in `test` pins the owner's
    /// return value through a call that names the owner.
    pub(in crate::analysis) fn admits(
        &self,
        test: &TestSummary,
        assertion: &OracleFact,
        index: &RustIndex,
        imports_foreign: ForeignImport<'_>,
        syntax: &OwnerPinSyntax,
    ) -> bool {
        // The assertion must be the test's own: a harness trial's body is
        // only its registration, and a helper's `let` bindings are not in it.
        if !(test.start_line..=test.end_line).contains(&assertion.line) {
            return false;
        }
        // A `#[should_panic]` test passes when the values differ.
        if test
            .attrs
            .iter()
            .chain(std::iter::once(&test.body))
            .any(|text| text.contains("should_panic"))
        {
            return false;
        }
        let condition;
        let (call, expected) = if is_plain_macro(&assertion.text, "assert_eq") {
            let Some(operands) = assertion_comparison_operands(&assertion.text) else {
                return false;
            };
            match (
                owner_call_shape(operands[0], &self.name),
                owner_call_shape(operands[1], &self.name),
            ) {
                (Some(call), None) => (call, operands[1]),
                (None, Some(call)) => (call, operands[0]),
                _ => return false,
            }
        } else if self.returns_bool && is_plain_macro(&assertion.text, "assert") {
            // `assert!(owner(..))` is `assert_eq!(owner(..), true)` and
            // `assert!(!owner(..))` is `assert_eq!(owner(..), false)`. The
            // message arguments never decide whether the test fails.
            let Some(text) = outer_assertion_condition(&assertion.text) else {
                return false;
            };
            condition = text;
            let operand = condition.trim();
            let (operand, expected) = match operand.strip_prefix('!') {
                Some(negated) => (negated.trim_start(), "false"),
                None => (operand, "true"),
            };
            let Some(call) = owner_call_shape(operand, &self.name) else {
                return false;
            };
            (call, expected)
        } else {
            return false;
        };
        if !syntax.admits(test, assertion, index) {
            return false;
        }
        // `assert_eq!(f(4), f(2) + f(2))` compares the owner with itself.
        if contains_as_whole_word(&mask_comments_and_strings(expected), &self.name) {
            return false;
        }
        match (&self.path, call) {
            // #6692: the clone must be compared with its own receiver, and
            // the test's file must not import some other `Clone`.
            (ReturnPathGate::CloneReceiver, CallShape::Method(receiver)) => {
                let independent = match &self.call {
                    PinCall::Method { receivers, .. } => receivers.iter().any(|receiver_type| {
                        matches!(receiver_type, ReceiverType::Named(type_name)
                            if clone_receiver_is_independent(test, receiver, type_name, index))
                    }),
                    PinCall::Bare => false,
                };
                if expected.trim() != receiver
                    || imports_foreign(&test.file, "Clone")
                    || !independent
                {
                    return false;
                }
            }
            (ReturnPathGate::CloneReceiver, CallShape::Bare) => return false,
            (path, _) => {
                if !path.admits(expected) {
                    return false;
                }
            }
        }
        let test_source = index
            .files()
            .get(&test.file)
            .map(|facts| facts.data().source.as_str());
        let masked_body = mask_comments_and_strings(&test.body);
        match (&self.call, call) {
            (PinCall::Bare, CallShape::Bare) => {
                !test_body_shadows_owner(test, &self.name)
                    && !binds_outside_let(&masked_body, &self.name)
                    && !bound_by_macro(&masked_body, &self.name)
                    && test_source.is_some_and(|source| !file_renames_to(source, &self.name))
            }
            (
                PinCall::Method {
                    receivers,
                    trait_scope,
                },
                CallShape::Method(receiver),
            ) => {
                if bound_by_macro(&masked_body, receiver) {
                    return false;
                }
                let Some(receiver_type) =
                    test_receiver_type(test, receiver, test_source, index, imports_foreign)
                else {
                    return false;
                };
                if !receivers.contains(&receiver_type) {
                    return false;
                }
                let shadowed_by_std = match &receiver_type {
                    ReceiverType::ByteSlice => BYTE_SLICE_METHODS.contains(&self.name.as_str()),
                    ReceiverType::Named(_) => {
                        BY_VALUE_PRELUDE_METHODS.contains(&self.name.as_str())
                    }
                };
                !shadowed_by_std
                    && trait_scope.as_ref().is_none_or(|scope| {
                        self.trait_in_scope(test, test_source, &scope.trait_name, index)
                    })
            }
            _ => false,
        }
    }

    fn trait_in_scope(
        &self,
        test: &TestSummary,
        test_source: Option<&str>,
        trait_name: &str,
        index: &RustIndex,
    ) -> bool {
        let Some(source) = test_source else {
            return false;
        };
        if let Some(known) = self.trait_scope_by_file.borrow().get(&test.file) {
            return *known;
        }
        let in_scope = trait_in_scope(source, trait_name, index);
        self.trait_scope_by_file
            .borrow_mut()
            .insert(test.file.clone(), in_scope);
        in_scope
    }
}

impl ReturnPathGate {
    fn admits(&self, expected: &str) -> bool {
        match self {
            Self::Any => true,
            Self::Head(head) => constructor_call_span(expected.trim(), head).is_some(),
            Self::CloneReceiver => false,
        }
    }
}

#[derive(Clone, Copy)]
enum CallShape<'a> {
    Bare,
    Method(&'a str),
}

/// The operand as a complete call of `name`: `name(..)` or `recv.name(..)`
/// with a plain identifier receiver and nothing chained after the call.
fn owner_call_shape<'a>(operand: &'a str, name: &str) -> Option<CallShape<'a>> {
    let operand = operand.trim();
    let call_start = if operand.starts_with(name) {
        0
    } else {
        let dot = operand.find('.')?;
        let receiver = &operand[..dot];
        if !is_plain_identifier(receiver) || receiver == "self" {
            return None;
        }
        if !operand[dot + 1..].starts_with(name) {
            return None;
        }
        dot + 1
    };
    let after_name = &operand[call_start + name.len()..];
    if !after_name.starts_with('(') {
        return None;
    }
    let masked = mask_comments_and_strings(operand);
    let opening = call_start + name.len();
    let closing = matching_close(&masked, opening, b'(', b')')?;
    if !operand[closing + 1..].trim().is_empty() {
        return None;
    }
    Some(if call_start == 0 {
        CallShape::Bare
    } else {
        CallShape::Method(&operand[..call_start - 1])
    })
}

/// The span of `head(..)` when `text` is exactly one `head(..)` call.
fn constructor_call_span(text: &str, head: &str) -> Option<usize> {
    let rest = text.strip_prefix(head)?;
    if !rest.starts_with('(') {
        return None;
    }
    let masked = mask_comments_and_strings(text);
    let closing = matching_close(&masked, head.len(), b'(', b')')?;
    text[closing + 1..].trim().is_empty().then_some(closing)
}

/// Whether the owner's return value can only have come through the changed
/// expression, and if so what the pinned value must look like.
/// `changed_line` is the changed line's offset from the body's first line;
/// the tail must span it, so an identical expression elsewhere in the body
/// is not mistaken for the changed one.
fn return_path_gate(body: &str, expression: &str, changed_line: usize) -> Option<ReturnPathGate> {
    let masked = mask_comments_and_strings(body);
    let open = body_block_open(&masked)?;
    let close = matching_close(&masked, open, b'{', b'}')?;
    let inner = &masked[open + 1..close];
    let inner_text = &body[open + 1..close];
    let changed = collapse_whitespace(expression.trim().trim_end_matches(';'));
    let changed = changed
        .strip_prefix("return ")
        .map_or(changed.as_str(), str::trim);
    if changed.is_empty() {
        return None;
    }
    let spans_changed_line = |start: usize, end: usize| {
        let line_of = |offset: usize| body[..open + 1 + offset].matches('\n').count();
        let text = &inner_text[start..end];
        let first = start + (text.len() - text.trim_start().len());
        let last = start + text.trim_end().len();
        (line_of(first)..=line_of(last)).contains(&changed_line)
    };
    let (after_semicolon, after_brace) = top_level_tail_starts(inner);
    let tail_is_changed = [after_semicolon, after_brace].into_iter().any(|start| {
        collapse_whitespace(&inner_text[start..]) == changed
            && spans_changed_line(start, inner_text.len())
    });
    // `return <changed>;` as the final statement is also the tail.
    let final_return_is_changed = !tail_is_changed
        && inner[after_semicolon..].trim().is_empty()
        && final_statement(inner, after_semicolon).is_some_and(|(start, end)| {
            collapse_whitespace(&inner_text[start..end])
                .strip_prefix("return ")
                .is_some_and(|value| value.trim() == changed)
                && spans_changed_line(start, end)
        });
    if !tail_is_changed && !final_return_is_changed {
        return None;
    }
    if has_unbounded_macro(inner) || evaluates_conditionally(&mask_comments_and_strings(changed)) {
        return None;
    }
    let returns = whole_word_offsets(inner, "return");
    let other_returns = returns.len() - usize::from(final_return_is_changed);
    let early_exits = inner.bytes().filter(|byte| *byte == b'?').count() + other_returns;
    if early_exits == 0 {
        return Some(ReturnPathGate::Any);
    }
    let (head, other) = if constructor_call_span(changed, "Ok").is_some() {
        ("Ok", "Err")
    } else if constructor_call_span(changed, "Some").is_some() {
        ("Some", "None")
    } else {
        return None;
    };
    let head_calls = whole_word_offsets(inner, head)
        .into_iter()
        .filter(|offset| inner[offset + head.len()..].trim_start().starts_with('('))
        .count();
    if head_calls != 1 {
        return None;
    }
    // Every other `return` must build the other constructor. When the
    // changed expression is the final `return`, it is the last one.
    let last = returns.len().checked_sub(1);
    let returns_agree = returns.iter().enumerate().all(|(position, offset)| {
        (final_return_is_changed && Some(position) == last)
            || starts_with_word(inner[offset + "return".len()..].trim_start(), other)
    });
    returns_agree.then_some(ReturnPathGate::Head(head))
}

/// Whether `text` starts with the whole word `word`.
fn starts_with_word(text: &str, word: &str) -> bool {
    text.strip_prefix(word).is_some_and(|after| {
        !after.starts_with(|character: char| character.is_ascii_alphanumeric() || character == '_')
    })
}

/// Byte offset of the `{` that opens the function body: the first brace
/// after the parameter list closes.
fn body_block_open(masked: &str) -> Option<usize> {
    let params = masked.find('(')?;
    let params_close = matching_close(masked, params, b'(', b')')?;
    masked[params_close..]
        .find('{')
        .map(|offset| params_close + offset)
}

/// Where the tail expression may start: after the last top-level `;`, and
/// after the last top-level `}` (a block-like statement needs no `;`).
fn top_level_tail_starts(inner: &str) -> (usize, usize) {
    let mut depth = 0usize;
    let mut after_semicolon = 0usize;
    let mut after_brace = 0usize;
    for (offset, byte) in inner.bytes().enumerate() {
        match byte {
            b'(' | b'[' | b'{' => depth += 1,
            b')' | b']' => depth = depth.saturating_sub(1),
            b'}' => {
                depth = depth.saturating_sub(1);
                if depth == 0 {
                    after_brace = offset + 1;
                }
            }
            b';' if depth == 0 => after_semicolon = offset + 1,
            _ => {}
        }
    }
    (after_semicolon, after_brace.max(after_semicolon))
}

/// The span of the top-level statement that ends at the `;` just before
/// `end`, without the `;`.
fn final_statement(masked: &str, end: usize) -> Option<(usize, usize)> {
    let statement_end = end.checked_sub(1)?;
    let (previous_semicolon, previous_brace) = top_level_tail_starts(&masked[..statement_end]);
    Some((previous_semicolon.max(previous_brace), statement_end))
}

/// Macros that cannot return a value from the enclosing function. Any other
/// macro in the owner body (`bail!`, `ensure!`, a crate's own macro) may
/// hide a `return`, so the return paths are not established.
const NON_RETURNING_MACROS: &[&str] = &[
    "assert",
    "assert_eq",
    "assert_ne",
    "cfg",
    "column",
    "concat",
    "dbg",
    "debug_assert",
    "debug_assert_eq",
    "debug_assert_ne",
    "eprint",
    "eprintln",
    "file",
    "format",
    "format_args",
    "line",
    "matches",
    "module_path",
    "panic",
    "print",
    "println",
    "stringify",
    "todo",
    "unimplemented",
    "unreachable",
    "vec",
    "write",
    "writeln",
];

fn has_unbounded_macro(masked: &str) -> bool {
    macro_invocations(masked)
        .into_iter()
        .any(|(name, _)| !NON_RETURNING_MACROS.contains(&name))
}

/// Every `name!` macro invocation in masked text, with the offset of its
/// opening delimiter. Whitespace may separate the name, the `!` and the
/// delimiter (`ensure !(..)`); a keyword before `!` is a negation
/// (`if !done`), not a macro.
fn macro_invocations(masked: &str) -> Vec<(&str, usize)> {
    let bytes = masked.as_bytes();
    let mut invocations = Vec::new();
    for (offset, byte) in bytes.iter().enumerate() {
        if *byte != b'!' || bytes.get(offset + 1) == Some(&b'=') {
            continue;
        }
        let before = masked[..offset].trim_end();
        let start = before
            .rfind(|character: char| !(character.is_ascii_alphanumeric() || character == '_'))
            .map_or(0, |position| position + 1);
        let name = &before[start..];
        if !is_plain_identifier(name) || NEGATING_KEYWORDS.contains(&name) {
            continue;
        }
        let after = &masked[offset + 1..];
        let delimiter = offset + 1 + (after.len() - after.trim_start().len());
        if matches!(bytes.get(delimiter), Some(b'(' | b'[' | b'{')) {
            invocations.push((name, delimiter));
        }
    }
    invocations
}

/// Keywords a `!` negation can follow; never macro names.
const NEGATING_KEYWORDS: &[&str] = &[
    "if", "while", "return", "match", "in", "else", "break", "let", "mut", "move", "as",
];

/// Whether the changed tail evaluates some of its parts only on some
/// inputs: a closure or `|`/`||`/`&&` operator, a branch or loop, or a
/// combinator that skips its argument (`map_or(0, ..)` on `None`). A pin on
/// such an input never evaluates the changed part, so the tail's value is
/// not established to come through it.
///
/// A binary bitwise `|` evaluates both operands on every input, so it is
/// not conditional (#6675); every other pipe (`||`, `|=`, a closure's
/// parameter list) still is. See [`has_non_bitwise_pipe`].
fn evaluates_conditionally(masked_tail: &str) -> bool {
    if has_non_bitwise_pipe(masked_tail) || masked_tail.contains("&&") {
        return true;
    }
    if [
        "if", "match", "else", "loop", "while", "for", "break", "continue",
    ]
    .iter()
    .any(|keyword| contains_as_whole_word(masked_tail, keyword))
    {
        return true;
    }
    CONDITIONAL_COMBINATORS.iter().any(|combinator| {
        whole_word_offsets(masked_tail, combinator)
            .into_iter()
            .any(|offset| {
                let before = masked_tail[..offset].trim_end();
                (before.ends_with('.') || before.ends_with("::"))
                    && masked_tail[offset + combinator.len()..]
                        .trim_start()
                        .starts_with(['(', ':'])
            })
    })
}

/// #6692: whether the changed line (`changed_line`, offset from the body's
/// first line) lies in a struct literal of `type_name` (or `Self`) that is
/// the whole tail of `body`, and that literal is the body's only exit: no
/// `?`, no `return`, no macro that may hide an exit, and no part evaluated
/// only on some inputs. The changed line must be one whole field
/// initializer of that literal's own braces (depth 1): a field of a nested
/// literal or an argument of a call inside a field is not the outer
/// field's value.
fn clone_tail_literal_spans(
    body: &str,
    type_name: &str,
    changed_line: usize,
    expression: &str,
) -> bool {
    let masked = mask_comments_and_strings(body);
    let Some(open) = body_block_open(&masked) else {
        return false;
    };
    let Some(close) = matching_close(&masked, open, b'{', b'}') else {
        return false;
    };
    let inner = &masked[open + 1..close];
    if has_unbounded_macro(inner)
        || inner.contains('?')
        || !whole_word_offsets(inner, "return").is_empty()
    {
        return false;
    }
    let (after_semicolon, _) = top_level_tail_starts(inner);
    let tail = &inner[after_semicolon..];
    let tail_start = after_semicolon + (tail.len() - tail.trim_start().len());
    let tail = tail.trim();
    let Some(after_type) = tail
        .strip_prefix(type_name)
        .or_else(|| tail.strip_prefix("Self"))
    else {
        return false;
    };
    let after_type = after_type.trim_start();
    if !after_type.starts_with('{') {
        return false;
    }
    let literal_open = tail.len() - after_type.len();
    let Some(literal_close) = matching_close(tail, literal_open, b'{', b'}') else {
        return false;
    };
    if literal_close + 1 != tail.len() || evaluates_conditionally(tail) {
        return false;
    }
    let line_of = |offset: usize| masked[..open + 1 + offset].matches('\n').count();
    let first = line_of(tail_start + literal_open);
    let last = line_of(tail_start + literal_close);
    if !(first < changed_line && changed_line < last) {
        return false;
    }
    let Some(line_start) = masked
        .match_indices('\n')
        .nth(changed_line - 1)
        .map(|(position, _)| position + 1)
    else {
        return false;
    };
    let line_end = masked[line_start..]
        .find('\n')
        .map_or(masked.len(), |position| line_start + position);
    let literal_start = open + 1 + tail_start + literal_open;
    let depth = masked[literal_start..line_start]
        .bytes()
        .fold(0_isize, |depth, byte| match byte {
            b'{' | b'(' | b'[' => depth + 1,
            b'}' | b')' | b']' => depth - 1,
            _ => depth,
        });
    let line = masked[line_start..line_end].trim();
    let field_text = |text: &str| collapse_whitespace(text.trim().trim_end_matches(',').trim());
    depth == 1
        && !line.contains(['{', '}'])
        && field_text(&body[line_start..line_end]) == field_text(expression)
}

/// The field a struct-literal initializer names: `start: self.start,` and
/// the shorthand `start,` both name `start`.
fn initialized_field_name(expression: &str) -> Option<&str> {
    let trimmed = expression.trim().trim_end_matches(',').trim();
    let name = match trimmed.find(':') {
        Some(colon) if trimmed[colon..].starts_with("::") => return None,
        Some(colon) => trimmed[..colon].trim(),
        None => trimmed,
    };
    let name = name.strip_prefix("r#").unwrap_or(name);
    (is_plain_identifier(name) && !name.starts_with(|ch: char| ch.is_ascii_digit())).then_some(name)
}

/// How deep [`type_compares_by_value`] follows workspace field types.
const EQUALITY_DEPTH_LIMIT: usize = 4;

/// #6692 (RIPR-SPEC-0225 rules 3-4): whether `==` on `type_name` compares
/// its field `field` by value through the derived comparison. `type_name`
/// must have derived equality ([`derived_equality`]); `field` must carry no
/// attribute and its type must compare by value. Anything ripr cannot read
/// fails closed.
fn field_compares_with_derived_equality(type_name: &str, field: &str, index: &RustIndex) -> bool {
    derived_equality(type_name, index).is_some_and(|(facts, declaring)| {
        let mut named = facts
            .fields
            .iter()
            .filter(|candidate| candidate.name.as_deref() == Some(field));
        match (named.next(), named.next()) {
            (Some(found), None) => {
                !found.has_attributes && type_compares_by_value(&found.ty, declaring, index, 0)
            }
            _ => false,
        }
    })
}

/// The equality facts of `type_name` when its `==` is the derived one: it
/// is declared in exactly one parser-backed indexed file, as the one type
/// of that name there, with `PartialEq` in its `#[derive(..)]` list, no
/// other attribute that may change equality, and no indexed file holds an
/// `impl .. PartialEq .. for <type_name>` (gated or not). The declaring
/// file's source comes back too: it decides what the field types' names
/// refer to.
fn derived_equality<'a>(
    type_name: &str,
    index: &'a RustIndex,
) -> Option<(LocalTypeEquality, &'a str)> {
    let mut declaring = index.files().values().filter(|facts| {
        facts.source.contains(type_name)
            && declares_type(&mask_comments_and_strings(&facts.source), type_name)
    });
    let declaring_file = declaring.next()?;
    if declaring.next().is_some() || declaring_file.used_lexical_fallback {
        return None;
    }
    let facts = local_type_equality(&declaring_file.source, type_name)?;
    if !facts.derives.iter().any(|name| name == "PartialEq") || facts.other_attributes {
        return None;
    }
    let manual = index.files().values().any(|file| {
        trait_impl_self_types(&file.source, "PartialEq")
            .iter()
            .any(|self_ty| path_base_name(strip_type_arguments(self_ty)) == Some(type_name))
    });
    (!manual).then_some((facts, declaring_file.data().source.as_str()))
}

/// Standard types whose `==` compares by value.
const STD_VALUE_TYPES: &[&str] = &[
    "bool", "char", "str", "String", "u8", "u16", "u32", "u64", "u128", "usize", "i8", "i16",
    "i32", "i64", "i128", "isize", "f32", "f64",
];

/// Standard containers whose `==` compares their type arguments by value.
const STD_VALUE_CONTAINERS: &[&str] = &[
    "Option", "Result", "Vec", "VecDeque", "Box", "Rc", "Arc", "BTreeMap", "BTreeSet", "HashMap",
    "HashSet",
];

/// RIPR-SPEC-0225 rule 4: whether a field type compares by value: a
/// standard value type, a reference, tuple, array or standard container of
/// such types, or a workspace type with derived equality whose own fields
/// do too, recursively. A workspace type of a standard name shadows it.
/// A multi-segment path must be rooted in `std`, `core` or `alloc`
/// (`foreign::String` is not `String`), and the declaring file must not
/// bind the base name some other way ([`declaring_file_rebinds`]).
fn type_compares_by_value(ty: &str, declaring: &str, index: &RustIndex, depth: usize) -> bool {
    if depth > EQUALITY_DEPTH_LIMIT {
        return false;
    }
    let ty = ty.trim();
    if let Some(referent) = ty.strip_prefix('&') {
        let referent = referent.trim_start();
        let referent = if referent.starts_with('\'') {
            referent
                .split_once(char::is_whitespace)
                .map_or("", |(_, rest)| rest)
        } else {
            referent
        };
        let referent = referent.strip_prefix("mut ").unwrap_or(referent);
        return type_compares_by_value(referent, declaring, index, depth + 1);
    }
    if let Some(inner) = ty.strip_prefix('(').and_then(|rest| rest.strip_suffix(')')) {
        return top_level_arguments(inner)
            .into_iter()
            .all(|element| type_compares_by_value(element, declaring, index, depth + 1));
    }
    if let Some(inner) = ty.strip_prefix('[').and_then(|rest| rest.strip_suffix(']')) {
        let element = inner.split(';').next().unwrap_or(inner);
        return type_compares_by_value(element, declaring, index, depth + 1);
    }
    let (path, arguments) = match ty.split_once('<') {
        Some((path, rest)) => match rest.strip_suffix('>') {
            Some(arguments) => (path.trim(), Some(arguments)),
            None => return false,
        },
        None => (ty, None),
    };
    let Some(base) = path_base_name(path) else {
        return false;
    };
    if let Some((root, _)) = path.trim_start_matches("::").split_once("::")
        && !(STD_ROOTS.contains(&root.trim()) && !workspace_renames_to(index, root.trim()))
    {
        return false;
    }
    let workspace_type = type_declared_in_workspace(base, index);
    if declaring_file_rebinds(declaring, base, workspace_type, index) {
        return false;
    }
    if workspace_type {
        return arguments.is_none()
            && derived_equality(base, index).is_some_and(|(facts, declaring)| {
                facts.fields.iter().all(|field| {
                    !field.has_attributes
                        && type_compares_by_value(&field.ty, declaring, index, depth + 1)
                })
            });
    }
    match arguments {
        None => STD_VALUE_TYPES.contains(&base),
        Some(arguments) => {
            STD_VALUE_CONTAINERS.contains(&base)
                && top_level_arguments(arguments)
                    .into_iter()
                    .all(|argument| type_compares_by_value(argument, declaring, index, depth + 1))
        }
    }
}

/// The roots of standard library paths.
const STD_ROOTS: &[&str] = &["std", "core", "alloc"];

/// Whether `base`, named in a field type of a type declared in the file
/// `declaring`, may denote something other than the standard type (or,
/// when `workspace_type`, the one workspace declaration) of that name. It
/// may when the file renames an item to it (`use x::Thing as String;`),
/// aliases it (`type String = ..;`), or has a `use` that names it or globs
/// (`use foreign::Vec;`, `use foreign::*;`) rooted outside `std`, `core`
/// and `alloc`. A `crate`/`self`/`super` (or own-package) root is a
/// workspace path: it may bring the workspace declaration, but never a
/// standard name's own type, and only while no workspace `use` re-exports
/// the name or a glob from elsewhere. Lexical and file-wide: a `use` in any
/// module of the file counts. Anything else fails closed.
fn declaring_file_rebinds(
    declaring: &str,
    base: &str,
    workspace_type: bool,
    index: &RustIndex,
) -> bool {
    if file_renames_to(declaring, base) || file_aliases_type(declaring, base) {
        return true;
    }
    file_use_statements(declaring).iter().any(|statement| {
        let names = contains_as_whole_word(statement, base);
        if !(names || statement.contains('*')) {
            return false;
        }
        match use_statement_first_segment(statement) {
            Some(root) if STD_ROOTS.contains(&root) => workspace_renames_to(index, root),
            // A workspace path that names a standard name imports some
            // other item of it; a workspace glob brings only workspace items.
            Some(root) if is_workspace_root(root, index) => {
                (names && !workspace_type) || workspace_may_export_other(index, base)
            }
            _ => true,
        }
    })
}

/// `crate`, `self`, `super`, or the crate name of a workspace package.
fn is_workspace_root(root: &str, index: &RustIndex) -> bool {
    matches!(root, "crate" | "self" | "super")
        || index
            .package_names
            .iter()
            .any(|name| name.replace('-', "_") == root)
}

/// Whether a workspace path may lead to some item named `base` other than
/// its workspace declaration: a workspace `use` rooted outside the standard
/// library and the workspace names `base` or globs (a re-export of a
/// foreign item), or a workspace file renames an item to `base` or aliases
/// a type as `base`.
fn workspace_may_export_other(index: &RustIndex, base: &str) -> bool {
    index.files().values().any(|facts| {
        file_renames_to(&facts.source, base)
            || file_aliases_type(&facts.source, base)
            || file_use_statements(&facts.source).iter().any(|statement| {
                (contains_as_whole_word(statement, base) || statement.contains('*'))
                    && use_statement_first_segment(statement).is_none_or(|root| {
                        !(STD_ROOTS.contains(&root) || is_workspace_root(root, index))
                    })
            })
    })
}

/// Whether any indexed file renames an item to `name` (`extern crate
/// other as std;`).
fn workspace_renames_to(index: &RustIndex, name: &str) -> bool {
    index
        .files()
        .values()
        .any(|facts| file_renames_to(&facts.source, name))
}

/// The comma-separated items of `text` at bracket depth zero.
fn top_level_arguments(text: &str) -> Vec<&str> {
    let mut items = Vec::new();
    let mut depth = 0usize;
    let mut start = 0usize;
    for (offset, byte) in text.bytes().enumerate() {
        match byte {
            b'<' | b'(' | b'[' => depth += 1,
            b'>' | b')' | b']' => depth = depth.saturating_sub(1),
            b',' if depth == 0 => {
                items.push(text[start..offset].trim());
                start = offset + 1;
            }
            _ => {}
        }
    }
    let last = text[start..].trim();
    if !last.is_empty() {
        items.push(last);
    }
    items
}

/// `Window<T>` -> `Window`.
fn strip_type_arguments(self_ty: &str) -> &str {
    self_ty.split('<').next().unwrap_or(self_ty).trim()
}

/// Whether masked `text` declares a struct, enum or union named `name`.
fn declares_type(text: &str, name: &str) -> bool {
    ["struct", "enum", "union"].iter().any(|keyword| {
        whole_word_offsets(text, keyword)
            .into_iter()
            .any(|offset| starts_with_word(text[offset + keyword.len()..].trim_start(), name))
    })
}

/// Whether any indexed file declares a trait named `name`.
fn workspace_declares_trait(index: &RustIndex, name: &str) -> bool {
    index.files().values().any(|facts| {
        facts.source.contains(name) && {
            let masked = mask_comments_and_strings(&facts.source);
            whole_word_offsets(&masked, "trait")
                .into_iter()
                .any(|offset| starts_with_word(masked[offset + "trait".len()..].trim_start(), name))
        }
    })
}

/// Whether masked text holds a `|` that is not a binary bitwise OR (#6675):
/// a `||` (lazy OR, or an empty closure), a `|=`, or a pipe in operand
/// position, which opens a closure parameter list (`map(|x| ..)`,
/// `move |x| ..`). A pipe is read as binary only when it directly follows a
/// completed operand: an identifier or number that is not a keyword, or a
/// closing `)`/`]` or `?`. A closure's closing pipe may follow its
/// parameter name, but its opening pipe never follows an operand, so every
/// closure still fails here. A pipe inside a macro invocation's
/// arguments (`matches!(k, A | B)`) or anywhere in a tail that binds with
/// `let` may separate pattern alternatives, which short-circuit, so it is
/// never read as binary. Anything else fails closed.
fn has_non_bitwise_pipe(masked: &str) -> bool {
    const OPERAND_POSITION_KEYWORDS: &[&str] = &[
        "async", "break", "else", "in", "let", "move", "mut", "return", "static", "yield",
    ];
    if !masked.contains('|') {
        return false;
    }
    if contains_as_whole_word(masked, "let") {
        return true;
    }
    let bytes = masked.as_bytes();
    // One entry per open delimiter: whether it opens a macro's arguments.
    let mut delimiters: Vec<bool> = Vec::new();
    for (offset, byte) in bytes.iter().enumerate() {
        match byte {
            b'(' | b'[' | b'{' => {
                let before = masked[..offset].trim_end();
                let opens_macro = before.strip_suffix('!').is_some_and(|head| {
                    head.ends_with(|character: char| {
                        character.is_alphanumeric() || character == '_'
                    })
                });
                delimiters.push(opens_macro);
                continue;
            }
            b')' | b']' | b'}' => {
                delimiters.pop();
                continue;
            }
            b'|' => {}
            _ => continue,
        }
        if delimiters.iter().any(|opens_macro| *opens_macro) {
            return true;
        }
        if matches!(bytes.get(offset + 1), Some(b'|' | b'='))
            || (offset > 0 && bytes[offset - 1] == b'|')
        {
            return true;
        }
        let before = masked[..offset].trim_end();
        let Some(previous) = before.bytes().last() else {
            return true;
        };
        let binary = match previous {
            b')' | b']' | b'?' => true,
            byte if byte.is_ascii_alphanumeric() || byte == b'_' => {
                let start = before
                    .char_indices()
                    .rev()
                    .find(|(_, character)| {
                        !(character.is_ascii_alphanumeric() || *character == '_')
                    })
                    .map_or(0, |(position, character)| position + character.len_utf8());
                !OPERAND_POSITION_KEYWORDS.contains(&&before[start..])
            }
            _ => false,
        };
        if !binary {
            return true;
        }
    }
    false
}

/// `Option`/`Result`/`bool` methods that evaluate or apply an argument only
/// on some inputs.
const CONDITIONAL_COMBINATORS: &[&str] = &[
    "and",
    "and_then",
    "filter",
    "get_or_insert_with",
    "is_none_or",
    "is_ok_and",
    "is_some_and",
    "map",
    "map_err",
    "map_or",
    "map_or_else",
    "ok_or",
    "ok_or_else",
    "or",
    "or_else",
    "then",
    "then_some",
    "unwrap_or",
    "unwrap_or_default",
    "unwrap_or_else",
    "xor",
    "zip",
];

fn is_bare_assert_eq_invocation(text: &str) -> bool {
    let masked = mask_comments_and_strings(text);
    let mut invocation = masked.trim_start();
    // The parser includes a macro statement's attributes in its fact text.
    // Skip only complete attributes; do not mistake an inner invocation in
    // another oracle's token tree for that oracle's own identity.
    while let Some(attribute) = invocation.strip_prefix('#') {
        let attribute = attribute.trim_start();
        let Some(close) = matching_close(attribute, 0, b'[', b']') else {
            return false;
        };
        invocation = attribute[close + 1..].trim_start();
    }
    invocation
        .strip_prefix("r#")
        .unwrap_or(invocation)
        .strip_prefix("assert_eq")
        .is_some_and(|after_name| after_name.trim_start().starts_with('!'))
}

/// Whether `text` is one plain `assert_eq!` invocation: not
/// `debug_assert_eq!` (compiled out in release tests), not a crate's own
/// `*_assert_eq!`, not a path-qualified or repeated one.
/// The text is exactly one unqualified invocation of `macro_name`.
fn is_plain_macro(text: &str, macro_name: &str) -> bool {
    let masked = mask_comments_and_strings(text);
    let invocations = macro_invocations(&masked);
    let [(name, _)] = invocations.as_slice() else {
        return false;
    };
    *name == macro_name
        && masked
            .find(macro_name)
            .is_some_and(|offset| !masked[..offset].trim_end().ends_with(':'))
}

/// Whether a macro other than a known non-binding one mentions `name` in
/// its arguments: `let_assert!(Ok(p) = ..)` and similar macros bind
/// patterns ripr does not read.
fn bound_by_macro(masked: &str, name: &str) -> bool {
    macro_invocations(masked)
        .into_iter()
        .filter(|(macro_name, _)| !NON_RETURNING_MACROS.contains(macro_name))
        .any(|(_, delimiter)| {
            let (open, close) = match masked.as_bytes()[delimiter] {
                b'(' => (b'(', b')'),
                b'[' => (b'[', b']'),
                _ => (b'{', b'}'),
            };
            let end = matching_close(masked, delimiter, open, close).unwrap_or(masked.len());
            contains_as_whole_word(&masked[delimiter..end], name)
        })
}

/// Whether the file renames some item to `name` (`use a::b as name;`), so
/// `name` may not be the item it looks like.
fn file_renames_to(source: &str, name: &str) -> bool {
    if !source.contains(name) {
        return false;
    }
    let masked = mask_comments_and_strings(source);
    whole_word_offsets(&masked, "as")
        .into_iter()
        .any(|offset| starts_with_word(masked[offset + "as".len()..].trim_start(), name))
}

/// Whether the file declares a type alias `type name`.
fn file_aliases_type(source: &str, name: &str) -> bool {
    if !source.contains(name) {
        return false;
    }
    let masked = mask_comments_and_strings(source);
    whole_word_offsets(&masked, "type")
        .into_iter()
        .any(|offset| starts_with_word(masked[offset + "type".len()..].trim_start(), name))
}

/// Whether another workspace definition of the owner's name could take a
/// call by that name. A bare call competes with every other module-level
/// function of the name; a method call competes with every other method of
/// the name that has a body (overrides, inherent methods of other types,
/// other traits' methods), except a pure `(**self).name(..)` forward, which
/// dispatches to the same method on the pointee. A definition whose item
/// container is unknown (lexical fallback) always competes, and so does a
/// `fn name` the parser never indexed (inside a `macro_rules!` body).
fn other_definition_competes(owner: &FunctionSummary, index: &RustIndex, method: bool) -> bool {
    let name = owner.name.as_str();
    let is_owner = |file: &PathBuf, line: usize| *file == owner.file && line == owner.start_line;
    let indexed_competes = index.functions().iter().any(|function| {
        if function.name != name || is_owner(&function.file, function.start_line) {
            return false;
        }
        match function.item.container {
            FunctionContainer::Unknown => true,
            FunctionContainer::Local => false,
            FunctionContainer::Free => !method,
            _ => {
                method
                    && function.item.has_self_param
                    && function.item.has_body
                    && !is_self_forward(&function.body, name)
            }
        }
    });
    if indexed_competes {
        return true;
    }
    index.files().iter().any(|(path, facts)| {
        // Masking only erases text, so a file whose raw source has no
        // `fn <name>` has none after masking either; skip the mask.
        if !facts.source.contains(name) || fn_definition_offsets(&facts.source, name).is_empty() {
            return false;
        }
        let masked = mask_comments_and_strings(&facts.source);
        fn_definition_offsets(&masked, name)
            .into_iter()
            .any(|offset| {
                let line = masked[..offset]
                    .bytes()
                    .filter(|byte| *byte == b'\n')
                    .count()
                    + 1;
                let indexed = facts
                    .functions
                    .iter()
                    .any(|function| function.name == name && function.start_line == line)
                    || is_owner(path, line);
                if indexed {
                    return false;
                }
                let Some(definition) = unindexed_definition(&facts.source, &masked, offset) else {
                    return true;
                };
                match definition.body {
                    None => false,
                    Some(body) => definition.has_self == method && !is_self_forward(body, name),
                }
            })
    })
}

struct UnindexedDefinition<'a> {
    has_self: bool,
    body: Option<&'a str>,
}

/// The parameter receiver and body of a `fn` definition the parser did not
/// index, read from its text.
fn unindexed_definition<'a>(
    source: &'a str,
    masked: &str,
    offset: usize,
) -> Option<UnindexedDefinition<'a>> {
    let params = offset + masked[offset..].find('(')?;
    let params_close = matching_close(masked, params, b'(', b')')?;
    let first_param = masked[params + 1..params_close]
        .split(',')
        .next()
        .unwrap_or("")
        .trim();
    let receiver = first_param.trim_start_matches('&').trim_start();
    let receiver = if receiver.starts_with('\'') {
        receiver
            .split_once(char::is_whitespace)
            .map_or("", |(_, rest)| rest.trim_start())
    } else {
        receiver
    };
    let receiver = receiver
        .strip_prefix("mut ")
        .map_or(receiver, str::trim_start);
    let has_self =
        receiver == "self" || receiver.starts_with("self:") || receiver.starts_with("self ");
    let mut depth = 0usize;
    for (relative, byte) in masked[params_close..].bytes().enumerate() {
        match byte {
            b'(' | b'[' => depth += 1,
            b')' | b']' => depth = depth.saturating_sub(1),
            b';' if depth == 0 => {
                return Some(UnindexedDefinition {
                    has_self,
                    body: None,
                });
            }
            b'{' if depth == 0 => {
                let open = params_close + relative;
                let close = matching_close(masked, open, b'{', b'}')?;
                return Some(UnindexedDefinition {
                    has_self,
                    body: Some(&source[open..=close]),
                });
            }
            _ => {}
        }
    }
    None
}

/// Whether `body` only forwards to the same method on the pointee:
/// `{ (**self).name(..) }` or `{ (*self).name(..) }`.
fn is_self_forward(body: &str, name: &str) -> bool {
    let masked = mask_comments_and_strings(body);
    let Some(open) = masked.find('{') else {
        return false;
    };
    let Some(close) = matching_close(&masked, open, b'{', b'}') else {
        return false;
    };
    let inner = body[open + 1..close].trim();
    ["(**self).", "(*self)."].iter().any(|prefix| {
        inner
            .strip_prefix(prefix)
            .is_some_and(|call| matches!(owner_call_shape(call, name), Some(CallShape::Bare)))
    })
}

/// Offsets of the `fn` keyword in every `fn <name>` definition.
fn fn_definition_offsets(masked: &str, name: &str) -> Vec<usize> {
    whole_word_offsets(masked, "fn")
        .into_iter()
        .filter(|offset| {
            let rest = masked[offset + 2..].trim_start();
            rest.strip_prefix(name).is_some_and(|after| {
                let after = after.trim_start();
                after.starts_with('(') || after.starts_with('<')
            })
        })
        .collect()
}

/// The name-keyed workspace scans [`OwnerReturnPin::establish`] runs for an
/// owner that files outside the index could still change (#5320). Each scan
/// is monotone in the files it sees, so once the index decides it, more
/// files cannot change it; an undecided scan names what a file must spell.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub(in crate::analysis) struct PinScopeNeeds {
    /// No other indexed `fn <name>` competes yet; another file's could.
    pub(in crate::analysis) competing_definitions: bool,
    /// The receiver type is not declared in the index yet; another file's
    /// `struct`/`enum`/`union` of this name would declare it.
    pub(in crate::analysis) receiver_type: Option<String>,
    /// A trait method's receivers come from every `impl <trait> for` block.
    pub(in crate::analysis) trait_impls: Option<String>,
    /// A test binding `let x = T::ctor()` pins this receiver type only when
    /// exactly one inherent `impl T { fn ctor }` exists; another file's
    /// `impl` block for a same-named type changes that count.
    pub(in crate::analysis) constructor_type: Option<String>,
}

/// What [`PinScopeNeeds`] says for `owner` over `index`.
pub(in crate::analysis) fn pin_scope_needs(
    owner: &FunctionSummary,
    index: &RustIndex,
) -> PinScopeNeeds {
    let mut needs = PinScopeNeeds::default();
    if !owner.item.has_body {
        return needs;
    }
    let method = match (&owner.item.container, owner.item.has_self_param) {
        (FunctionContainer::Free, false) => false,
        (FunctionContainer::Inherent { self_ty }, true)
        | (FunctionContainer::TraitImpl { self_ty, .. }, true) => {
            needs.constructor_type = path_base_name(self_ty).map(str::to_string);
            if declared_receiver(self_ty, index).is_none() {
                // A shape `declared_receiver` never accepts stays refused
                // whatever else is indexed.
                if self_ty.starts_with(['&', '[', '(', '*']) || self_ty.starts_with("dyn ") {
                    return needs;
                }
                let Some(base) = path_base_name(self_ty) else {
                    return needs;
                };
                needs.receiver_type = Some(base.to_string());
            }
            true
        }
        (FunctionContainer::Trait { trait_name }, true) => {
            needs.trait_impls = Some(trait_name.clone());
            true
        }
        _ => return needs,
    };
    needs.competing_definitions = !other_definition_competes(owner, index, method);
    needs
}

/// The receiver type an `impl` block's self type names, when it is one this
/// module can match a test binding against.
fn declared_receiver(self_ty: &str, index: &RustIndex) -> Option<ReceiverType> {
    if is_byte_slice_type(self_ty) {
        return Some(ReceiverType::ByteSlice);
    }
    if self_ty.starts_with(['&', '[', '(', '*']) || self_ty.starts_with("dyn ") {
        return None;
    }
    let base = path_base_name(self_ty)?;
    type_declared_in_workspace(base, index).then(|| ReceiverType::Named(base.to_string()))
}

/// Every receiver type with an `impl .. <trait_name> for <type>` block in
/// the workspace.
fn trait_impl_receivers(trait_name: &str, index: &RustIndex) -> Vec<ReceiverType> {
    let mut receivers = Vec::new();
    for facts in index.files().values() {
        for self_ty in trait_impl_self_types(&facts.source, trait_name) {
            if let Some(receiver) = declared_receiver(&self_ty, index)
                && !receivers.contains(&receiver)
            {
                receivers.push(receiver);
            }
        }
    }
    receivers
}

/// The base names of the self types `source` implements `trait_name` for:
/// the names whose declarations and inherent constructors decide a default
/// method's receivers (#5320).
pub(in crate::analysis) fn trait_impl_self_type_names(
    source: &str,
    trait_name: &str,
) -> BTreeSet<String> {
    trait_impl_self_types(source, trait_name)
        .iter()
        .filter_map(|self_ty| path_base_name(self_ty).map(str::to_string))
        .collect()
}

/// The self types of the `impl .. <trait_name> for <type>` headers in
/// `source`.
fn trait_impl_self_types(source: &str, trait_name: &str) -> Vec<String> {
    let mut self_types = Vec::new();
    if whole_word_offsets(source, trait_name).is_empty() {
        return self_types;
    }
    let masked = mask_comments_and_strings(source);
    for offset in whole_word_offsets(&masked, "impl") {
        let Some(header_end) = masked[offset..].find(['{', ';']) else {
            continue;
        };
        let header = collapse_whitespace(&masked[offset + "impl".len()..offset + header_end]);
        let header = strip_leading_generics(&header);
        let Some((trait_path, self_ty)) = header.split_once(" for ") else {
            continue;
        };
        let self_ty = self_ty.split(" where ").next().unwrap_or(self_ty).trim();
        if path_base_name(trait_path.trim()) == Some(trait_name) {
            self_types.push(self_ty.to_string());
        }
    }
    self_types
}

fn strip_leading_generics(header: &str) -> &str {
    let header = header.trim_start();
    if !header.starts_with('<') {
        return header;
    }
    let mut depth = 0usize;
    for (offset, byte) in header.bytes().enumerate() {
        match byte {
            b'<' => depth += 1,
            b'>' => {
                depth = depth.saturating_sub(1);
                if depth == 0 {
                    return header[offset + 1..].trim_start();
                }
            }
            _ => {}
        }
    }
    header
}

fn type_declared_in_workspace(name: &str, index: &RustIndex) -> bool {
    let declares = |text: &str| {
        ["struct", "enum", "union"].iter().any(|keyword| {
            whole_word_offsets(text, keyword)
                .into_iter()
                .any(|offset| starts_with_word(text[offset + keyword.len()..].trim_start(), name))
        })
    };
    // The raw check is a superset of the masked one; mask only on a hit.
    index.files().values().any(|facts| {
        facts.source.contains(name)
            && declares(&facts.source)
            && declares(&mask_comments_and_strings(&facts.source))
    })
}

/// The type the test binds `receiver` to: every `let` that binds the name
/// is a simple `let [mut] receiver [: T] = ..;` whose type ripr can read,
/// and all of them agree. Other uses of the binding (borrows, arguments,
/// reassignments) cannot change a Rust binding's type; another binding of
/// the same name in a pattern ripr does not read (a closure parameter, a
/// `for` or match-arm pattern, a destructuring `let`, a nested `fn`)
/// leaves the type unestablished.
fn test_receiver_type(
    test: &TestSummary,
    receiver: &str,
    test_source: Option<&str>,
    index: &RustIndex,
    imports_foreign: ForeignImport<'_>,
) -> Option<ReceiverType> {
    let mut bound: Option<ReceiverType> = None;
    for binding in receiver_let_bindings(test, receiver)? {
        let receiver_type = binding_type(binding, test, test_source, index, imports_foreign)?;
        match &bound {
            None => bound = Some(receiver_type),
            Some(existing) if *existing == receiver_type => {}
            Some(_) => return None,
        }
    }
    bound
}

/// The text after the name in every `let [mut] receiver [: T] = ..;` of the
/// test body (the optional annotation and the initializer), or `None` when
/// the name may be bound some other way ripr does not read.
fn receiver_let_bindings<'a>(test: &'a TestSummary, receiver: &str) -> Option<Vec<&'a str>> {
    let masked = mask_comments_and_strings(&test.body);
    if binds_outside_let(&masked, receiver) {
        return None;
    }
    let mut bindings = Vec::new();
    for offset in whole_word_offsets(&masked, "let") {
        let pattern_start = offset + "let".len();
        let Some(relative_end) = top_level_semicolon(&masked[pattern_start..]) else {
            // A `let` ripr cannot bound (an `if let` closing its block):
            // its pattern may still bind the name.
            let rest = &masked[pattern_start..];
            let end = rest.find(['=', '{']).unwrap_or(rest.len());
            if contains_as_whole_word(&rest[..end], receiver) {
                return None;
            }
            continue;
        };
        let statement_end = pattern_start + relative_end;
        let statement = &masked[pattern_start..statement_end];
        let pattern_end = statement
            .match_indices('=')
            .map(|(position, _)| position)
            .find(|position| {
                !matches!(statement.as_bytes().get(position + 1), Some(b'=' | b'>'))
                    && !matches!(
                        statement.as_bytes().get(position.wrapping_sub(1)),
                        Some(b'=' | b'!' | b'<' | b'>')
                    )
            })
            .unwrap_or(statement.len());
        if !contains_as_whole_word(&statement[..pattern_end], receiver) {
            continue;
        }
        let pattern = statement[..pattern_end].trim();
        let pattern = pattern
            .strip_prefix("mut ")
            .map_or(pattern, str::trim_start);
        let annotation = pattern.strip_prefix(receiver)?.trim_start();
        if !(annotation.is_empty() || annotation.starts_with(':')) {
            return None;
        }
        let binding = &test.body[pattern_start..statement_end];
        bindings.push(&binding[binding.find(receiver)? + receiver.len()..]);
    }
    Some(bindings)
}

/// Methods that may run the `clone` under test.
const CLONING_METHODS: &[&str] = &["clone", "clone_from", "cloned", "to_owned"];

/// #6692: whether the clone's receiver was built without the clone under
/// test, so a wrong `clone` cannot also have produced the value it is
/// compared with (`let w: Window = base.clone(); assert_eq!(w.clone(), w)`
/// passes for an idempotent wrong field). Every `let` of the receiver must
/// initialize it with a `type_name { .. }` or `type_name(..)` literal, or a
/// call to the type's one inherent constructor whose body clones nothing,
/// and no part of an initializer may clone. The test may not reassign or
/// mutably borrow the receiver. Anything else fails closed.
fn clone_receiver_is_independent(
    test: &TestSummary,
    receiver: &str,
    type_name: &str,
    index: &RustIndex,
) -> bool {
    let masked = mask_comments_and_strings(&test.body);
    if receiver_is_reassigned(&masked, receiver) {
        return false;
    }
    let Some(bindings) = receiver_let_bindings(test, receiver) else {
        return false;
    };
    !bindings.is_empty()
        && bindings
            .into_iter()
            .all(|binding| initializer_is_independent(binding, type_name, index))
}

/// Whether the test may change `receiver` after binding it: an assignment
/// (`w = ..`, `w += ..`), or any `mut` before the name (`let mut w`,
/// `&mut w`, `ref mut w`, `|mut w|`). A `let mut` binding alone refuses:
/// a field write (`w.start = w.end`), a `&mut w.start` borrow or a
/// `&mut self` method call (`w.set_start(9)`) all need one, and ripr does
/// not read them.
fn receiver_is_reassigned(masked: &str, receiver: &str) -> bool {
    const COMPOUND: &[&str] = &["+=", "-=", "*=", "/=", "%=", "^=", "&=", "|=", "<<=", ">>="];
    whole_word_offsets(masked, receiver)
        .into_iter()
        .any(|offset| {
            let after = masked[offset + receiver.len()..].trim_start();
            let assigns =
                (after.starts_with('=') && !after.starts_with("==") && !after.starts_with("=>"))
                    || COMPOUND.iter().any(|operator| after.starts_with(operator));
            let before = masked[..offset].trim_end();
            let mutable = before.strip_suffix("mut").is_some_and(|rest| {
                !rest
                    .as_bytes()
                    .last()
                    .is_some_and(|byte| is_ident_byte(*byte))
            });
            let let_binding = before.strip_suffix("let").is_some_and(|rest| {
                !rest
                    .as_bytes()
                    .last()
                    .is_some_and(|byte| is_ident_byte(*byte))
            });
            (assigns && !let_binding) || mutable
        })
}

/// One receiver initializer: a `type_name { .. }` or `type_name(..)`
/// literal, or a `type_name::ctor(..)` call to the type's one inherent
/// constructor, whose fields or arguments are all [`is_trivial_expression`]
/// without locals: no call, method, macro, index, block or local binding
/// may supply a value (a helper or a local could carry a wrong clone's
/// output, `Window::new(make(&base))`). The constructor body must be a
/// bare `Self`/`type_name` literal of its parameters
/// ([`constructor_body_is_plain_literal`]).
fn initializer_is_independent(binding: &str, type_name: &str, index: &RustIndex) -> bool {
    let masked = mask_comments_and_strings(binding);
    let Some(equals) = masked.find('=') else {
        return false;
    };
    let initializer = masked[equals + 1..].trim();
    if CLONING_METHODS
        .iter()
        .any(|method| contains_as_whole_word(initializer, method))
    {
        return false;
    }
    let Some(rest) = initializer.strip_prefix(type_name) else {
        return false;
    };
    if let Some(call) = rest.strip_prefix("::") {
        let call_end = call
            .find(|character: char| !(character.is_ascii_alphanumeric() || character == '_'))
            .unwrap_or(call.len());
        let constructor = &call[..call_end];
        let arguments = call[call_end..].trim_start();
        if !arguments.starts_with('(')
            || matching_close(arguments, 0, b'(', b')') != Some(arguments.len() - 1)
            || !literal_items_are_trivial(&arguments[1..arguments.len() - 1], false, false)
        {
            return false;
        }
        let mut definitions = index.functions().iter().filter(|function| {
            function.name == constructor
                && !function.item.has_self_param
                && matches!(
                    &function.item.container,
                    FunctionContainer::Inherent { self_ty } if path_base_name(self_ty) == Some(type_name)
                )
        });
        let (Some(definition), None) = (definitions.next(), definitions.next()) else {
            return false;
        };
        return constructor_body_is_plain_literal(&definition.body, type_name);
    }
    plain_literal(rest.trim_start(), false)
}

/// Whether `rest` (the text after a type name) is exactly one `{ .. }` or
/// `( .. )` literal body whose items are trivial; `locals` admits plain
/// lowercase bindings (a constructor's parameters) and field shorthand.
fn plain_literal(rest: &str, locals: bool) -> bool {
    let (open, close, braced) = match rest.as_bytes().first() {
        Some(b'{') => (b'{', b'}', true),
        Some(b'(') => (b'(', b')', false),
        _ => return false,
    };
    matching_close(rest, 0, open, close) == Some(rest.len() - 1)
        && literal_items_are_trivial(&rest[1..rest.len() - 1], braced, locals)
}

/// Whether every comma-separated item of a literal or argument list is a
/// trivial expression; in a braced literal each item is `field: expr` (or,
/// with `locals`, the shorthand `field`). A `..base` update refuses.
fn literal_items_are_trivial(items: &str, braced: bool, locals: bool) -> bool {
    if items.contains("..") {
        return false;
    }
    top_level_arguments(items).into_iter().all(|item| {
        if !braced {
            return is_trivial_expression(item, locals);
        }
        match item.split_once(':') {
            Some((field, value)) => {
                is_plain_identifier(field.trim())
                    && !value.starts_with(':')
                    && is_trivial_expression(value, locals)
            }
            None => locals && is_plain_identifier(item.trim()),
        }
    })
}

/// Whether a constructor's (masked) body is nothing but a `Self { .. }`,
/// `type_name { .. }`, `Self(..)` or `type_name(..)` literal of trivial
/// items over its parameters: no `let`, call, method, macro or helper that
/// could run a clone.
fn constructor_body_is_plain_literal(definition: &str, type_name: &str) -> bool {
    let masked = mask_comments_and_strings(definition);
    let Some(open) = masked
        .find('(')
        .and_then(|params| matching_close(&masked, params, b'(', b')'))
        .and_then(|params_close| {
            masked[params_close..]
                .find('{')
                .map(|offset| params_close + offset)
        })
    else {
        return false;
    };
    let Some(close) = matching_close(&masked, open, b'{', b'}') else {
        return false;
    };
    if !masked[close + 1..].trim().is_empty() {
        return false;
    }
    let tail = masked[open + 1..close].trim();
    let Some(rest) = tail
        .strip_prefix("Self")
        .or_else(|| tail.strip_prefix(type_name))
    else {
        return false;
    };
    plain_literal(rest.trim_start(), true)
}

/// Primitive type names a trivial expression may cast to.
const CAST_TYPES: &[&str] = &[
    "u8", "u16", "u32", "u64", "u128", "usize", "i8", "i16", "i32", "i64", "i128", "isize", "f32",
    "f64", "char", "bool",
];

/// Whether a (masked) expression only combines literals, `true`/`false`,
/// constants and enum variants named by a path whose last segment starts
/// uppercase, `as` casts to primitives and arithmetic, comparison and
/// bitwise operators. Calls, methods, macros, indexing, blocks, closures,
/// derefs, ranges, `?` and lowercase bindings (unless `locals`) refuse:
/// any of them may carry a value the clone under test produced.
fn is_trivial_expression(expression: &str, locals: bool) -> bool {
    let bytes = expression.as_bytes();
    if expression.trim().is_empty() {
        return false;
    }
    let mut index = 0usize;
    let mut after_as = false;
    while index < bytes.len() {
        let byte = bytes[index];
        if byte.is_ascii_digit() {
            index += 1;
            while index < bytes.len()
                && (is_ident_byte(bytes[index])
                    || (bytes[index] == b'.'
                        && bytes.get(index + 1).is_some_and(u8::is_ascii_digit)))
            {
                index += 1;
            }
            continue;
        }
        if byte.is_ascii_alphabetic() || byte == b'_' {
            let start = index;
            while index < bytes.len()
                && (is_ident_byte(bytes[index])
                    || (bytes[index] == b':' && bytes.get(index + 1) == Some(&b':')))
            {
                index += if bytes[index] == b':' { 2 } else { 1 };
            }
            let path = &expression[start..index];
            let last = path.rsplit("::").next().unwrap_or(path);
            let next = bytes.get(index).copied();
            let string_prefix = matches!(path, "b" | "r" | "br" | "c" | "cr")
                && matches!(next, Some(b'"' | b'#' | b'\''));
            let admitted = if after_as {
                CAST_TYPES.contains(&path)
            } else if path == "as" {
                after_as = true;
                continue;
            } else {
                string_prefix
                    || matches!(path, "true" | "false")
                    || last.starts_with(|character: char| character.is_ascii_uppercase())
                    || (locals && path == last && is_plain_identifier(path))
            };
            after_as = false;
            if !admitted || last.is_empty() {
                return false;
            }
            continue;
        }
        if byte.is_ascii_whitespace()
            || matches!(
                byte,
                b'"' | b'\'' | b'#' | b'-' | b'+' | b'/' | b'%' | b'&' | b'^' | b'<' | b'>' | b'='
            )
        {
            index += 1;
            continue;
        }
        return false;
    }
    !after_as
}

/// Whether `name` may be bound by a pattern that is not a `let`: a closure
/// parameter list, a `for` pattern, a match arm, the test's own or a
/// nested `fn`'s parameters. Lexical and conservative: a `|` operator or an unrelated
/// match arm that mentions the name also counts.
fn binds_outside_let(masked: &str, name: &str) -> bool {
    let fns = whole_word_offsets(masked, "fn");
    if fns.len() > 1 {
        return true;
    }
    // The test's own parameters (`#[case] name: T`) bind the name too.
    let parameters = fns.first().and_then(|offset| {
        let open = offset + masked[*offset..].find('(')?;
        let close = matching_close(masked, open, b'(', b')')?;
        Some(&masked[open..close])
    });
    if parameters.is_none_or(|parameters| contains_as_whole_word(parameters, name)) {
        return true;
    }
    let bytes = masked.as_bytes();
    let pipes = bytes
        .iter()
        .enumerate()
        .filter(|(offset, byte)| {
            **byte == b'|'
                && bytes.get(offset + 1) != Some(&b'|')
                && (*offset == 0 || bytes[offset - 1] != b'|')
        })
        .map(|(offset, _)| offset)
        .collect::<Vec<_>>();
    // Every region between two consecutive pipes: a `|` operator must not
    // shift a closure's parameter list out of the pairing.
    if pipes
        .windows(2)
        .any(|pair| contains_as_whole_word(&masked[pair[0]..pair[1]], name))
    {
        return true;
    }
    let for_pattern = whole_word_offsets(masked, "for").into_iter().any(|offset| {
        let rest = &masked[offset + "for".len()..];
        let end = whole_word_offsets(rest, "in")
            .first()
            .copied()
            .unwrap_or(rest.len());
        contains_as_whole_word(&rest[..end], name)
    });
    if for_pattern {
        return true;
    }
    masked.match_indices("=>").any(|(arrow, _)| {
        let start = masked[..arrow]
            .rfind(['{', ',', '}'])
            .map_or(0, |position| position + 1);
        contains_as_whole_word(&masked[start..arrow], name)
    })
}

/// The type of one `let <receiver> ...;` binding: its annotation, or a
/// constructor-shaped initializer.
fn binding_type(
    binding: &str,
    test: &TestSummary,
    test_source: Option<&str>,
    index: &RustIndex,
    imports_foreign: ForeignImport<'_>,
) -> Option<ReceiverType> {
    let binding = binding.trim();
    let (annotation, initializer) = if let Some(rest) = binding.strip_prefix(':') {
        let (annotation, initializer) = rest.split_once('=')?;
        (Some(annotation.trim()), initializer.trim())
    } else {
        (None, binding.strip_prefix('=')?.trim())
    };
    if let Some(annotation) = annotation {
        return named_or_slice(annotation, test, test_source, imports_foreign);
    }
    if is_byte_slice_expression(initializer) {
        return Some(ReceiverType::ByteSlice);
    }
    let (initializer, unwrapped) = strip_unwrap(initializer);
    let type_end = initializer
        .find(|character: char| !(character.is_ascii_alphanumeric() || character == '_'))?;
    let type_name = &initializer[..type_end];
    let rest = &initializer[type_end..];
    let constructor = if let Some(call) = rest.strip_prefix("::") {
        let call_end =
            call.find(|character: char| !(character.is_ascii_alphanumeric() || character == '_'))?;
        let masked = mask_comments_and_strings(&call[call_end..]);
        masked.starts_with('(')
            && matching_close(&masked, 0, b'(', b')')
                .is_some_and(|closing| masked[closing + 1..].trim().is_empty())
            && constructor_returns_self(type_name, &call[..call_end], unwrapped, index)
    } else {
        let rest = rest.trim_start();
        let (open, close) = if rest.starts_with('{') {
            (b'{', b'}')
        } else {
            (b'(', b')')
        };
        let masked = mask_comments_and_strings(rest);
        !unwrapped
            && masked.as_bytes().first() == Some(&open)
            && matching_close(&masked, 0, open, close)
                .is_some_and(|closing| masked[closing + 1..].trim().is_empty())
    };
    if !constructor {
        return None;
    }
    named_or_slice(type_name, test, test_source, imports_foreign)
}

/// The initializer without a trailing `?`, `.unwrap()` or `.expect(..)`,
/// and whether one was there.
fn strip_unwrap(initializer: &str) -> (&str, bool) {
    let initializer = initializer.trim();
    if let Some(rest) = initializer
        .strip_suffix('?')
        .or_else(|| initializer.strip_suffix(".unwrap()"))
    {
        return (rest.trim_end(), true);
    }
    let masked = mask_comments_and_strings(initializer);
    if masked.ends_with(')')
        && let Some(position) = masked.rfind(".expect(")
        && matching_close(&masked, position + ".expect".len(), b'(', b')') == Some(masked.len() - 1)
    {
        return (initializer[..position].trim_end(), true);
    }
    (initializer, false)
}

/// Whether `type_name::constructor(..)` (unwrapped when `unwrapped`)
/// evaluates to a `type_name`. `default` and `from` return `Self` by their
/// traits' signatures and `try_from` returns `Result<Self, _>`; any other
/// associated function must be the type's one inherent definition of that
/// name, returning `Self` (or the type) directly, or inside
/// `Result`/`Option` when unwrapped.
fn constructor_returns_self(
    type_name: &str,
    constructor: &str,
    unwrapped: bool,
    index: &RustIndex,
) -> bool {
    match constructor {
        "default" | "from" => return !unwrapped,
        "try_from" => return unwrapped,
        _ => {}
    }
    let mut definitions = index.functions().iter().filter(|function| {
        function.name == constructor
            && !function.item.has_self_param
            && matches!(
                &function.item.container,
                FunctionContainer::Inherent { self_ty } if path_base_name(self_ty) == Some(type_name)
            )
    });
    let (Some(definition), None) = (definitions.next(), definitions.next()) else {
        return false;
    };
    let Some(returned) = declared_return_type(&definition.body) else {
        return false;
    };
    let names_type = |text: &str| {
        let text = text.trim();
        text == "Self" || path_base_name(text) == Some(type_name)
    };
    if unwrapped {
        ["Result<", "Option<"].iter().any(|wrapper| {
            returned
                .strip_prefix(wrapper)
                .and_then(|inner| inner.strip_suffix('>'))
                .is_some_and(|inner| names_type(inner.split(',').next().unwrap_or(inner)))
        })
    } else {
        names_type(&returned)
    }
}

/// The return type a `fn` definition declares, whitespace-collapsed.
fn declared_return_type(definition: &str) -> Option<String> {
    let masked = mask_comments_and_strings(definition);
    let params = masked.find('(')?;
    let params_close = matching_close(&masked, params, b'(', b')')?;
    let body_open = params_close + masked[params_close..].find('{')?;
    let signature = collapse_whitespace(&definition[params_close + 1..body_open]);
    let signature = signature.split(" where ").next().unwrap_or(&signature);
    Some(signature.trim().strip_prefix("->")?.trim().to_string())
}

fn named_or_slice(
    type_text: &str,
    test: &TestSummary,
    test_source: Option<&str>,
    imports_foreign: ForeignImport<'_>,
) -> Option<ReceiverType> {
    if is_byte_slice_type(type_text) {
        return Some(ReceiverType::ByteSlice);
    }
    let base = path_base_name(type_text)?;
    if !base.starts_with(|character: char| character.is_ascii_uppercase()) {
        return None;
    }
    // A test file that imports the name from outside the workspace, renames
    // another item to it, or aliases it binds a different type than the
    // workspace declaration.
    let source = test_source?;
    if imports_foreign(&test.file, base)
        || file_renames_to(source, base)
        || file_aliases_type(source, base)
    {
        return None;
    }
    Some(ReceiverType::Named(base.to_string()))
}

/// A trait's methods are callable with method syntax only while the trait
/// is in scope: the test's file imports it by name from the workspace, or
/// declares it.
fn trait_in_scope(source: &str, trait_name: &str, index: &RustIndex) -> bool {
    if file_imports_foreign_callee_name(source, trait_name, &index.package_names) {
        return false;
    }
    if file_imports_own_item(source, trait_name, &index.package_names) {
        return true;
    }
    let masked = mask_comments_and_strings(source);
    whole_word_offsets(&masked, "trait")
        .into_iter()
        .any(|offset| {
            masked[offset + "trait".len()..]
                .trim_start()
                .strip_prefix(trait_name)
                .is_some_and(|after| {
                    !after.starts_with(|character: char| {
                        character.is_ascii_alphanumeric() || character == '_'
                    })
                })
        })
}

fn test_body_shadows_owner(test: &TestSummary, owner: &str) -> bool {
    if fact_body_defines_callee_fn(&test.nested_fn_names, owner)
        || fact_body_let_shadow_line(&test.let_bindings, owner).is_some()
    {
        return true;
    }
    let masked = mask_comments_and_strings(&test.body);
    test_body_defines_callee_fn(&masked, owner)
        || test_body_let_shadow_line(&masked, owner).is_some()
}

fn is_byte_slice_type(text: &str) -> bool {
    let compact: String = text.split_whitespace().collect();
    let Some(rest) = compact.strip_prefix('&') else {
        return false;
    };
    let rest = match rest.strip_prefix('\'') {
        Some(lifetime) => lifetime.trim_start_matches(|character: char| {
            character.is_ascii_alphanumeric() || character == '_'
        }),
        None => rest,
    };
    rest == "[u8]"
}

/// `&[..][..]` or `&b".."[..]`: a byte-slice expression.
fn is_byte_slice_expression(initializer: &str) -> bool {
    let Some(rest) = initializer.trim().strip_prefix('&') else {
        return false;
    };
    let Some(array) = rest.trim_end().strip_suffix("[..]") else {
        return false;
    };
    let array = array.trim();
    if let Some(bytes) = array.strip_prefix("b\"") {
        return bytes.ends_with('"');
    }
    let masked = mask_comments_and_strings(array);
    masked.starts_with('[')
        && matching_close(&masked, 0, b'[', b']').is_some_and(|close| close + 1 == masked.len())
}

/// The last `::` segment of a path, without generic arguments.
fn path_base_name(path: &str) -> Option<&str> {
    let path = path.trim();
    let without_generics = path.split('<').next()?.trim();
    let base = without_generics.rsplit("::").next()?.trim();
    is_plain_identifier(base).then_some(base)
}

fn is_plain_identifier(text: &str) -> bool {
    text.starts_with(|character: char| character.is_ascii_alphabetic() || character == '_')
        && text
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || character == '_')
}

fn is_ident_byte(byte: u8) -> bool {
    byte.is_ascii_alphanumeric() || byte == b'_'
}

fn whole_word_offsets(text: &str, word: &str) -> Vec<usize> {
    let bytes = text.as_bytes();
    let mut offsets = Vec::new();
    let mut search = 0usize;
    while let Some(relative) = text[search..].find(word) {
        let offset = search + relative;
        let end = offset + word.len();
        let before_ok = offset == 0 || !is_ident_byte(bytes[offset - 1]);
        let after_ok = end >= bytes.len() || !is_ident_byte(bytes[end]);
        if before_ok && after_ok {
            offsets.push(offset);
        }
        search = end;
    }
    offsets
}

/// Offset of the first `;` outside brackets.
fn top_level_semicolon(masked: &str) -> Option<usize> {
    let mut depth = 0usize;
    for (offset, byte) in masked.bytes().enumerate() {
        match byte {
            b'(' | b'[' | b'{' => depth += 1,
            b')' | b']' | b'}' => depth = depth.checked_sub(1)?,
            b';' if depth == 0 => return Some(offset),
            _ => {}
        }
    }
    None
}

/// The offset of the bracket closing the one at `opening`, in masked text.
fn matching_close(masked: &str, opening: usize, open: u8, close: u8) -> Option<usize> {
    let bytes = masked.as_bytes();
    if bytes.get(opening) != Some(&open) {
        return None;
    }
    let mut depth = 0usize;
    for (offset, byte) in bytes.iter().enumerate().skip(opening) {
        if *byte == open {
            depth += 1;
        } else if *byte == close {
            depth = depth.checked_sub(1)?;
            if depth == 0 {
                return Some(offset);
            }
        }
    }
    None
}

fn collapse_whitespace(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// Method names `&[u8]` resolves before a workspace trait's method: the
/// inherent methods of slices and byte slices, and the methods of prelude
/// and `std::io` traits implemented for them. A byte-slice receiver never
/// credits a pin through one of these names.
const BYTE_SLICE_METHODS: &[&str] = &[
    "align_to",
    "align_to_mut",
    "array_chunks",
    "array_windows",
    "as_array",
    "as_ascii",
    "as_chunks",
    "as_flattened",
    "as_mut",
    "as_mut_ptr",
    "as_mut_ptr_range",
    "as_ptr",
    "as_ptr_range",
    "as_rchunks",
    "as_ref",
    "as_simd",
    "binary_search",
    "binary_search_by",
    "binary_search_by_key",
    "borrow",
    "by_ref",
    "bytes",
    "chain",
    "chunk_by",
    "chunks",
    "chunks_exact",
    "clone",
    "clone_from",
    "cmp",
    "concat",
    "connect",
    "consume",
    "contains",
    "copy_from_slice",
    "copy_within",
    "element_offset",
    "ends_with",
    "eq",
    "eq_ignore_ascii_case",
    "escape_ascii",
    "fill",
    "fill_buf",
    "fill_with",
    "first",
    "first_chunk",
    "fmt",
    "ge",
    "get",
    "get_mut",
    "get_unchecked",
    "gt",
    "hash",
    "into",
    "into_iter",
    "is_ascii",
    "is_empty",
    "is_sorted",
    "is_sorted_by",
    "is_sorted_by_key",
    "iter",
    "join",
    "last",
    "last_chunk",
    "le",
    "len",
    "lines",
    "lt",
    "make_ascii_lowercase",
    "make_ascii_uppercase",
    "max",
    "min",
    "ne",
    "partial_cmp",
    "partition_point",
    "rchunks",
    "rchunks_exact",
    "read",
    "read_buf",
    "read_exact",
    "read_line",
    "read_to_end",
    "read_to_string",
    "read_until",
    "read_vectored",
    "repeat",
    "reverse",
    "rotate_left",
    "rotate_right",
    "rsplit",
    "rsplit_once",
    "rsplitn",
    "select_nth_unstable",
    "skip_until",
    "sort",
    "sort_by",
    "sort_by_cached_key",
    "sort_by_key",
    "sort_unstable",
    "sort_unstable_by",
    "sort_unstable_by_key",
    "split",
    "split_at",
    "split_at_checked",
    "split_first",
    "split_first_chunk",
    "split_inclusive",
    "split_last",
    "split_last_chunk",
    "split_off",
    "split_off_first",
    "split_off_last",
    "split_once",
    "splitn",
    "starts_with",
    "strip_prefix",
    "strip_suffix",
    "subslice_range",
    "swap",
    "swap_with_slice",
    "take",
    "to_ascii_lowercase",
    "to_ascii_uppercase",
    "to_owned",
    "to_vec",
    "trim_ascii",
    "trim_ascii_end",
    "trim_ascii_start",
    "trim_prefix",
    "trim_suffix",
    "try_into",
    "type_id",
    "utf8_chunks",
    "windows",
];

/// Methods of prelude traits that take `self` by value. Method lookup
/// tries the receiver type itself before `&T`, so for a receiver type that
/// implements the trait (`Iterator`, `IntoIterator`, `Into`), one of these
/// takes the call before an inherent `&self` method of the same name. ripr
/// cannot see which std traits a workspace type implements (derives,
/// blanket impls), so a named receiver never credits a pin through these
/// names.
const BY_VALUE_PRELUDE_METHODS: &[&str] = &[
    "all",
    "any",
    "chain",
    "clamp",
    "cloned",
    "collect",
    "copied",
    "count",
    "cycle",
    "enumerate",
    "filter",
    "filter_map",
    "find",
    "find_map",
    "flat_map",
    "flatten",
    "fold",
    "for_each",
    "fuse",
    "inspect",
    "into",
    "into_iter",
    "is_sorted",
    "is_sorted_by",
    "is_sorted_by_key",
    "last",
    "map",
    "map_while",
    "max",
    "max_by",
    "max_by_key",
    "min",
    "min_by",
    "min_by_key",
    "nth",
    "partition",
    "peekable",
    "position",
    "product",
    "reduce",
    "rev",
    "rfind",
    "rfold",
    "rposition",
    "scan",
    "size_hint",
    "skip",
    "skip_while",
    "step_by",
    "sum",
    "take",
    "take_while",
    "try_fold",
    "try_for_each",
    "try_into",
    "unzip",
    "zip",
];

#[cfg(test)]
mod tests;
