#!/usr/bin/env python3
"""Author the work_portfolio captured corpora (canonical + variants).

Regenerate after intentional fixture changes:
    python3 fixtures/work_portfolio/author_corpus.py
Then commit the regenerated bytes together with the SPEC.md scenario pins.
"""
import copy
import hashlib
import json
from pathlib import Path

HERE = Path(__file__).parent

CAPTURED_AT = "2026-10-05T12:00:00Z"
OBSERVED_AT = "2026-10-05T12:00:00Z"
STALE_AT = "2026-09-01T00:00:00Z"
# The exact base main SHA this corpus was captured against (40 hex chars).
MAIN_SHA = "7cb64d60c9dd0dda59586e6b72dcdf150296a26f"
REPOSITORY = "EffortlessMetrics/ripr-swarm"
WIN_ROOT = "C:\\code\\ripr-swarm"
UNIX_ROOT = "/c/code/ripr-swarm"


def wt(root, name):
    return f"{root}\\{name}" if root == WIN_ROOT else f"{root}/{name}"


def sources(state_map, observed_map=None, request_id="req-captured-0001"):
    observed_map = observed_map or {}
    rows = []
    for kind in [
        "github_issues",
        "github_pull_requests",
        "github_claims",
        "local_state",
        "cargo_allow",
        "campaigns",
        "surfaces",
    ]:
        state = state_map.get(kind, "observed")
        row = {"source": kind, "state": state}
        if state in ("observed", "stale"):
            row["observed_at"] = observed_map.get(kind, OBSERVED_AT)
            row["request_id"] = request_id
        rows.append(row)
    return rows


def manifest(root, state_map=None, observed_map=None, request_id="req-captured-0001"):
    return {
        "schema_version": "work_captured_manifest.v1",
        "repository": REPOSITORY,
        "default_branch": "main",
        "default_branch_sha": MAIN_SHA,
        "root": root,
        "captured_at": CAPTURED_AT,
        "sources": sources(state_map or {}, observed_map, request_id),
    }


CAMPAIGNS = {
    "schema_version": "work_campaigns.v1",
    # Deliberately not sorted: the loader must not depend on input ordering.
    "campaigns": [
        {
            "id": "campaign-editor-ux",
            "title": "Editor UX campaign",
            "state": "active",
            "surfaces": ["surface-editor"],
            "issues": [9202, 1693],
        },
        {
            "id": "campaign-doc-polish",
            "title": "Docs polish campaign",
            "state": "complete",
            "surfaces": ["surface-docs"],
            "issues": [9301],
        },
        {
            "id": "campaign-rust-repair",
            "title": "Rust repair campaign",
            "state": "active",
            "surfaces": ["surface-rust-cli"],
            "issues": [9107, 9103, 9101, 9109, 9108, 9104, 9105, 9102, 9106],
        },
        {
            "id": "campaign-infra-hardening",
            "title": "Infra hardening campaign",
            "state": "active",
            "surfaces": ["surface-ci"],
            "issues": [],
            "note": "no eligible current work; the campaign must stay visible without hiding others",
        },
    ],
}


def issue(number, title, **overrides):
    row = {
        "number": number,
        "title": title,
        "state": "open",
        "lifecycle_disposition": "qualified_one_pr",
        "campaigns": ["campaign-rust-repair"],
        "blocked_by": [],
        "requirement_refs": [],
        "semantic_paths": [],
        "conflict_resources": [],
        "accepted_contracts": [],
        "contract_state": "none",
        "single_agent_preferred": False,
        "regression_risks": [],
    }
    row.update(overrides)
    return row


def build_issues():
    return {
        "schema_version": "work_issues.v1",
        "issues": [
            issue(
                9102,
                "Bound the rust JSON formatter receipts",
                semantic_paths=["crates/ripr/src/output/json/formatter.rs"],
                conflict_resources=["output-contract:rust-json"],
                accepted_contracts=["RIPR-SPEC-0200"],
                contract_state="accepted",
                honesty_risk="moderate",
                proof_cost="low",
                review_ci_cost="low",
            ),
            issue(
                9101,
                "Fix rust JSON report golden drift",
                semantic_paths=["crates/ripr/src/output/json/report.rs"],
                conflict_resources=["output-contract:rust-json"],
                accepted_contracts=["RIPR-SPEC-0200"],
                contract_state="accepted",
                honesty_risk="high",
                proof_cost="moderate",
                review_ci_cost="moderate",
                readiness_source="RIPR-SPEC-0200",
                regression_risks=[
                    "golden re-blessing could mask a wrong result; the repair must re-justify each touched golden"
                ],
            ),
            issue(
                9103,
                "Emit workflow receipts under the bounded budget",
                semantic_paths=[".github/workflows/ci.yml"],
                conflict_resources=["workflow:ci-small"],
                accepted_contracts=["RIPR-SPEC-0201"],
                contract_state="accepted",
                honesty_risk="low",
                proof_cost="moderate",
                review_ci_cost="low",
            ),
            issue(
                9104,
                "Consume the cargo-allow graph in the portfolio compiler",
                lifecycle_disposition="blocked",
                blocked_by=[
                    {
                        "kind": "external_dependency",
                        "reference": "cargo-allow#upstream-0.9",
                        "description": "the upstream cargo-allow release must land before the graph can be consumed",
                    }
                ],
                requirement_refs=["REQ-allow-graph"],
                semantic_paths=["xtask/src/work_portfolio.rs"],
                contract_state="draft",
            ),
            issue(
                9105,
                "Implement duplicate-family grouping for requirement A",
                requirement_refs=["REQ-dup-family"],
                semantic_paths=["crates/ripr/src/domain/summary.rs"],
                accepted_contracts=["RIPR-SPEC-0202"],
                contract_state="accepted",
                honesty_risk="moderate",
                proof_cost="low",
                review_ci_cost="low",
            ),
            issue(
                9106,
                "Resolve requirement A through the app seam",
                requirement_refs=["REQ-dup-family"],
                semantic_paths=["crates/ripr/src/domain/summary.rs", "crates/ripr/src/app.rs"],
                accepted_contracts=["RIPR-SPEC-0202"],
                contract_state="accepted",
                honesty_risk="moderate",
                proof_cost="low",
                review_ci_cost="low",
            ),
            issue(
                9107,
                "Repair the seam inventory latency cache",
                semantic_paths=["crates/ripr/src/analysis/seams.rs"],
                accepted_contracts=["RIPR-SPEC-0203"],
                contract_state="accepted",
                honesty_risk="low",
                proof_cost="low",
                review_ci_cost="low",
            ),
            issue(
                9108,
                "Unregistered lane for the doctor command",
                semantic_paths=["xtask/src/main.rs"],
                accepted_contracts=["RIPR-SPEC-0204"],
                contract_state="accepted",
                honesty_risk="low",
                proof_cost="low",
                review_ci_cost="low",
            ),
            issue(
                9109,
                "Reconcile the merged preview fix",
                lifecycle_disposition="merged_pending_closeout",
                semantic_paths=["crates/ripr/src/output/preview.rs"],
                accepted_contracts=["RIPR-SPEC-0205"],
                contract_state="accepted",
                honesty_risk="moderate",
                proof_cost="low",
                review_ci_cost="low",
            ),
            issue(
                1693,
                "Preview projection honesty follow-ups",
                campaigns=["campaign-editor-ux"],
                semantic_paths=["editors/vscode/src/preview.ts"],
                conflict_resources=["output-contract:preview-panel"],
                requirement_refs=["REQ-editor-preview"],
                accepted_contracts=["RIPR-SPEC-0206"],
                contract_state="accepted",
                honesty_risk="high",
                proof_cost="moderate",
                review_ci_cost="moderate",
            ),
            issue(
                9202,
                "Fix editor badge label casing",
                campaigns=["campaign-editor-ux"],
                semantic_paths=["editors/vscode/src/badge.ts"],
                requirement_refs=["REQ-editor-badges"],
                accepted_contracts=["RIPR-SPEC-0207"],
                contract_state="accepted",
                single_agent_preferred=True,
                honesty_risk="low",
                proof_cost="low",
                review_ci_cost="low",
            ),
            issue(
                9301,
                "Docs polish umbrella",
                state="closed",
                lifecycle_disposition="completed",
                campaigns=["campaign-doc-polish"],
                semantic_paths=["docs/POLISH.md"],
                accepted_contracts=["RIPR-SPEC-0208"],
                contract_state="accepted",
                honesty_risk="low",
                proof_cost="low",
                review_ci_cost="low",
            ),
        ],
    }


def build_pull_requests(root):
    def pr(number, title, state, head, linked, claim, review, findings, checks, worktree=None):
        row = {
            "number": number,
            "title": title,
            "state": state,
            "draft": False,
            "head_branch": head,
            "base_branch": "main",
            "linked_issues": linked,
            "review_state": review,
            "unresolved_review_findings": findings,
            "checks_state": checks,
        }
        if claim is not None:
            row["registered_claim"] = claim
        if worktree is not None:
            row["worktree_path"] = worktree
        return row

    return {
        "schema_version": "work_pull_requests.v1",
        "pull_requests": [
            pr(8802, "Formatter receipts", "open", "feat/work-9102", [9102], "claim-9102", "none", 0, "pending", wt(root, "wt-9102")),
            pr(8804, "Doctor lane (unregistered)", "open", "feat/work-9108", [9108], None, "none", 0, "unknown", wt(root, "wt-9108")),
            pr(8801, "Golden drift repair", "open", "feat/work-9101", [9101], "claim-9101", "changes_requested", 2, "success", wt(root, "wt-9101")),
            pr(8803, "Workflow receipts", "open", "feat/work-9103", [9103], "claim-9103", "approved", 0, "success"),
            pr(8806, "Preview fix", "merged", "feat/work-9109", [9109], None, "approved", 0, "success"),
            pr(8805, "Docs polish", "merged", "feat/work-9301", [9301], None, "approved", 0, "success"),
        ],
    }


def build_claims(root):
    def claim(cid, num, branch):
        return {
            "id": cid,
            "issue": num,
            "branch": branch,
            "worktree": wt(root, branch.replace("feat/", "wt-").replace("work-", "")),
            "exclusive": True,
            "state": "active",
        }

    return {
        "schema_version": "work_claims.v1",
        "claims": [
            claim("claim-9102", 9102, "feat/work-9102"),
            claim("claim-9107-b", 9107, "feat/work-9107-b"),
            claim("claim-9101", 9101, "feat/work-9101"),
            claim("claim-9107-a", 9107, "feat/work-9107-a"),
            claim("claim-9103", 9103, "feat/work-9103"),
        ],
    }


def build_local_state(root):
    def branch(name):
        return {"name": name}

    return {
        "schema_version": "work_local_state.v1",
        "root": root,
        "branches": [
            branch("main"),
            branch("feat/work-9108"),
            branch("feat/work-9101"),
            branch("feat/work-9107-b"),
            branch("feat/work-9102"),
            branch("feat/work-9301"),
            branch("feat/work-9103"),
            branch("feat/work-9107-a"),
        ],
        "worktrees": [
            {"path": wt(root, "wt-9107-b")},
            {"path": wt(root, "wt-9108")},
            {"path": wt(root, "wt-9102")},
            {"path": wt(root, "wt-9101")},
            {"path": wt(root, "wt-9103")},
            {"path": wt(root, "wt-9107-a")},
        ],
    }


SURFACES = {
    "schema_version": "work_surfaces.v1",
    "surfaces": [
        {"id": "surface-editor"},
        {"id": "surface-docs"},
        {"id": "surface-rust-cli"},
        {"id": "surface-ci"},
    ],
}

CARGO_ALLOW = {
    "schema_version": "work_cargo_allow.v1",
    "requirements": [
        {
            "id": "REQ-editor-badges",
            "spec_refs": ["RIPR-SPEC-0207"],
            "slices": [
                {"id": "slice-9202", "delta_id": "DELTA-editor-badges", "issue_refs": [9202]}
            ],
        },
        {
            "id": "REQ-dup-family",
            "spec_refs": ["RIPR-SPEC-0202"],
            "slices": [
                {"id": "slice-9106", "delta_id": "DELTA-dup-family", "issue_refs": [9106]},
                {"id": "slice-9105", "delta_id": "DELTA-dup-family", "issue_refs": [9105]},
            ],
        },
        {
            "id": "REQ-allow-graph",
            "spec_refs": [],
            "slices": [
                {"id": "slice-9104", "delta_id": "DELTA-allow-graph", "issue_refs": [9104]}
            ],
        },
        {
            "id": "REQ-editor-preview",
            "spec_refs": ["RIPR-SPEC-0206"],
            "slices": [
                {"id": "slice-1693", "delta_id": "DELTA-editor-preview", "issue_refs": [1693]}
            ],
        },
    ],
}


def canonical(root=WIN_ROOT):
    return {
        "manifest.json": manifest(root),
        "campaigns.json": CAMPAIGNS,
        "issues.json": build_issues(),
        "pull_requests.json": build_pull_requests(root),
        "claims.json": build_claims(root),
        "local_state.json": build_local_state(root),
        "surfaces.json": SURFACES,
        "cargo_allow.json": CARGO_ALLOW,
    }


def deep_reverse_lists(value):
    if isinstance(value, dict):
        return {key: deep_reverse_lists(child) for key, child in value.items()}
    if isinstance(value, list):
        return [deep_reverse_lists(child) for child in reversed(value)]
    return value


def variant_unix_root():
    return canonical(UNIX_ROOT)


def variant_reordered():
    return {name: deep_reverse_lists(copy.deepcopy(body)) for name, body in canonical().items()}


def variant_missing_github():
    state_map = {
        "github_issues": "missing",
        "github_pull_requests": "missing",
        "github_claims": "missing",
    }
    files = canonical()
    files["manifest.json"] = manifest(WIN_ROOT, state_map)
    for name in ("issues.json", "pull_requests.json", "claims.json"):
        del files[name]
    return files


def variant_stale_local():
    files = canonical()
    observed_map = {"local_state": STALE_AT}
    files["manifest.json"] = manifest(WIN_ROOT, {}, observed_map)
    return files


def variant_no_cargo_allow():
    files = canonical()
    files["manifest.json"] = manifest(WIN_ROOT, {"cargo_allow": "unavailable"})
    del files["cargo_allow.json"]
    return files


VARIANTS = {
    "corpus": canonical,
    "variants/unix_root": variant_unix_root,
    "variants/reordered": variant_reordered,
    "variants/missing_github": variant_missing_github,
    "variants/stale_local": variant_stale_local,
    "variants/no_cargo_allow": variant_no_cargo_allow,
}


def write_json(path, body):
    path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(body, indent=2, sort_keys=False) + "\n"
    path.write_text(text, encoding="utf-8", newline="\n")
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def main():
    provenance = {
        "schema_version": "work_portfolio_provenance.v1",
        "repository": REPOSITORY,
        "captured_at": CAPTURED_AT,
        "capture_method": "authored captured-input corpora for the RIPR-SPEC-0233 work-portfolio compiler; regenerate with fixtures/work_portfolio/author_corpus.py",
        "corpora": [],
    }
    for name, builder in VARIANTS.items():
        files = builder()
        entries = []
        for file_name in sorted(files):
            digest = write_json(HERE / name / file_name, files[file_name])
            entries.append({"path": file_name, "sha256": digest})
        provenance["corpora"].append({"name": name, "files": entries})
    write_json(HERE / "provenance.json", provenance)
    print(f"authored {len(VARIANTS)} corpora under {HERE}")


if __name__ == "__main__":
    main()
