[alias]
build-lld = [
    "--config",
    "target.x86_64-unknown-linux-gnu.linker='clang'",
    "--config",
    "target.x86_64-unknown-linux-gnu.rustflags=['-C','link-arg=-fuse-ld=lld']",
    "build",
]
xtask = "run -p xtask --"

[env]
TEMP = { value = "target", relative = true, force = true }
TMP = { value = "target", relative = true, force = true }
TMPDIR = { value = "target", relative = true, force = true }
