//! Production identity catalog. Records existing authorities; does not mint
//! replacement wrappers for types owned by later slices (#4805–#4809).

use super::kinds::{IdentityKind, PortabilityClass};
#[cfg(test)]
use super::record::SerializationField;
use super::record::{AdjacentField, FieldRole, FieldVisibility, IdentityRecord, field};

const AGENT_REQUEST: &str = "schemas/ripr/ripr-agent-request.schema.json";
const AGENT_SUCCESS: &str = "schemas/ripr/ripr-agent-success.schema.json";
const AGENT_ERROR: &str = "schemas/ripr/ripr-agent-error.schema.json";
const REPAIR_ATTEMPT: &str = "schemas/ripr/repair-attempt.schema.json";
const REPAIR_ASSURANCE: &str = "schemas/ripr/repair-assurance.schema.json";
const CHECK_SCHEMA: &str = "schemas/ripr/check.schema.json";
const ACTION_CONTRACT: &str = "crates/ripr/src/lsp/action_contract.rs";
const COMMAND_SPEC: &str = "crates/ripr/src/domain/command_spec.rs";
const FEEDBACK: &str = "crates/ripr/src/output/feedback.rs";
const DIAGNOSTICS: &str = "crates/ripr/src/lsp/diagnostics.rs";

/// Serialization surfaces the registry check scans for unknown identity fields.
pub const GOVERNED_IDENTITY_SURFACES: &[&str] = &[
    AGENT_REQUEST,
    AGENT_SUCCESS,
    AGENT_ERROR,
    REPAIR_ATTEMPT,
    REPAIR_ASSURANCE,
    CHECK_SCHEMA,
    ACTION_CONTRACT,
    COMMAND_SPEC,
    FEEDBACK,
];

const VOLATILE_COMMON: &[&str] = &[
    "timestamp",
    "timestamps",
    "created_unix_ms",
    "pid",
    "client_name",
    "display",
    "display_text",
    "markdown",
    "scheduler_generation",
    "request_order",
    "traversal_order",
    "absolute_checkout",
    "absolute_path",
    "effective_root",
];

pub(crate) const PRODUCTION_RECORDS: &[IdentityRecord] = &[
    IdentityRecord {
        kind: IdentityKind::CanonicalItemId,
        canonical_type: "analysis::canonical_gap::CanonicalGapIdentity",
        owner_path: "crates/ripr/src/analysis/canonical_gap.rs",
        owner_issue: "#1932/#4804 (records PR-era Lane 1 gap identity; typed wrapper is #4805)",
        portability: PortabilityClass::Portable,
        semantic_inputs: &[
            "owner",
            "seam_kind",
            "flow_sink",
            "missing_discriminator",
            "assertion_shape",
        ],
        volatile_excluded: VOLATILE_COMMON,
        parents: &[],
        children: &[IdentityKind::FindingId, IdentityKind::InstructionSemanticId],
        invalidation: "Owner, seam kind, flow sink, missing discriminator, or assertion shape change. Line numbers are locators, not identity.",
        persistence: "May be persisted as a burn-down key. Must not be reused as a seam location or diagnostic transport id.",
        serialization: &[
            field(
                "canonical_gap_id",
                FieldRole::Canonical,
                CHECK_SCHEMA,
                FieldVisibility::Public,
                None,
            ),
            field(
                "canonical_gap_id",
                FieldRole::Canonical,
                REPAIR_ASSURANCE,
                FieldVisibility::Public,
                None,
            ),
            field(
                "canonical_gap_id",
                FieldRole::Canonical,
                ACTION_CONTRACT,
                FieldVisibility::Public,
                None,
            ),
            field(
                "gap_id",
                FieldRole::CompatibilityAlias,
                ACTION_CONTRACT,
                FieldVisibility::Public,
                Some("retire after CanonicalItemId typed migration (#4805/#4809)"),
            ),
        ],
        competing_wrappers: &[
            "gap_id on some diagnostic payloads still names the same burn-down key",
        ],
    },
    IdentityRecord {
        kind: IdentityKind::SeamLocationId,
        canonical_type: "analysis::seams::SeamId",
        owner_path: "crates/ripr/src/analysis/seams.rs",
        owner_issue: "#1932 (location-tied seam identity; distinct from CanonicalItemId)",
        portability: PortabilityClass::RepositoryBound,
        semantic_inputs: &["owner_span", "source_location", "seam_kind"],
        volatile_excluded: VOLATILE_COMMON,
        parents: &[],
        children: &[],
        invalidation: "Source location or seam span change. Canonical gap grouping must not be used as a substitute.",
        persistence: "Usable as a before/after locator. Must not be persisted as CanonicalItemId.",
        serialization: &[
            field(
                "seam_id",
                FieldRole::Canonical,
                REPAIR_ATTEMPT,
                FieldVisibility::Public,
                None,
            ),
            field(
                "seam_id",
                FieldRole::Canonical,
                REPAIR_ASSURANCE,
                FieldVisibility::Public,
                None,
            ),
            field(
                "seam_id",
                FieldRole::Canonical,
                ACTION_CONTRACT,
                FieldVisibility::Public,
                None,
            ),
        ],
        competing_wrappers: &[
            "CanonicalGapIdentity is a separate burn-down key and must not alias seam_id",
        ],
    },
    IdentityRecord {
        kind: IdentityKind::FindingId,
        canonical_type: "domain::support::ProbeId",
        owner_path: "crates/ripr/src/domain/support.rs",
        owner_issue: "#1932 (producer finding/probe identity; typed CanonicalItemId family is #4805)",
        portability: PortabilityClass::Portable,
        semantic_inputs: &["owner", "probe_family", "changed_span"],
        volatile_excluded: VOLATILE_COMMON,
        parents: &[IdentityKind::CanonicalItemId],
        children: &[],
        invalidation: "Changed owner or probe family. Display titles do not participate.",
        persistence: "May be referenced from packets. Must not become DiagnosticResultId.",
        serialization: &[field(
            "finding_id",
            FieldRole::Canonical,
            ACTION_CONTRACT,
            FieldVisibility::Public,
            None,
        )],
        competing_wrappers: &[
            "ProbeId remains the current Rust type; this row records it rather than wrapping it",
        ],
    },
    IdentityRecord {
        kind: IdentityKind::InstructionSemanticId,
        canonical_type: "(not yet typed; #4805)",
        owner_path: "crates/ripr/src/domain/fix_instruction.rs",
        owner_issue: "#1663/#1894/#4805",
        portability: PortabilityClass::Portable,
        semantic_inputs: &["safe_next_action_concept", "canonical_item"],
        volatile_excluded: VOLATILE_COMMON,
        parents: &[IdentityKind::CanonicalItemId],
        children: &[IdentityKind::InstructionInstanceId],
        invalidation: "The portable next-action concept changes. Client name, display text, and snapshot identity must not.",
        persistence: "Portable across equivalent checkouts. Must not be used as an executable action or edit id.",
        serialization: &[],
        competing_wrappers: &["FixInstructionSummary is state, not this identity"],
    },
    IdentityRecord {
        kind: IdentityKind::InstructionInstanceId,
        canonical_type: "(not yet typed; #4805)",
        owner_path: "crates/ripr/src/domain/fix_instruction.rs",
        owner_issue: "#1663/#1894/#4805",
        portability: PortabilityClass::SnapshotBound,
        semantic_inputs: &["instruction_semantic", "completed_snapshot", "source_facts"],
        volatile_excluded: VOLATILE_COMMON,
        parents: &[
            IdentityKind::InstructionSemanticId,
            IdentityKind::CompletedAnalysisSnapshotId,
        ],
        children: &[IdentityKind::ActionId, IdentityKind::EditInstructionId],
        invalidation: "Snapshot or source-fact change. Semantic meaning can remain stable while this instance does not.",
        persistence: "Must not outlive the snapshot that produced it.",
        serialization: &[],
        competing_wrappers: &[],
    },
    IdentityRecord {
        kind: IdentityKind::ActionId,
        canonical_type: "(fingerprint in lsp::action_contract::action_data; typed wrapper is #4806)",
        owner_path: "crates/ripr/src/lsp/action_contract.rs",
        owner_issue: "#1892/#1661/#4806",
        portability: PortabilityClass::SessionBound,
        semantic_inputs: &[
            "action_class",
            "canonical_identity",
            "command_id",
            "action_name",
        ],
        volatile_excluded: &[
            "title",
            "display",
            "markdown",
            "client_name",
            "timestamp",
            "pid",
            "effective_root",
        ],
        parents: &[IdentityKind::InstructionInstanceId, IdentityKind::CommandId],
        children: &[],
        invalidation: "Action class, addressed canonical identity, command id, or stable action name change. Title text must not.",
        persistence: "Session/code-action payload only. Must not be reused as InstructionSemanticId.",
        serialization: &[field(
            "action_id",
            FieldRole::Canonical,
            ACTION_CONTRACT,
            FieldVisibility::Public,
            None,
        )],
        competing_wrappers: &["LSP Command.title must not be treated as ActionId"],
    },
    IdentityRecord {
        kind: IdentityKind::EditInstructionId,
        canonical_type: "(not yet typed; #4806)",
        owner_path: "crates/ripr/src/lsp/saved_edit_sequence.rs",
        owner_issue: "#1571/#1895/#4806",
        portability: PortabilityClass::SnapshotBound,
        semantic_inputs: &[
            "instruction_instance",
            "original_source_digest",
            "range",
            "document_version",
        ],
        volatile_excluded: VOLATILE_COMMON,
        parents: &[IdentityKind::InstructionInstanceId],
        children: &[],
        invalidation: "Any source, range, or document-version change. Cannot survive an edit.",
        persistence: "Must not be persisted across document versions.",
        serialization: &[],
        competing_wrappers: &["SequenceIdentity is harness identity, not an edit instruction"],
    },
    IdentityRecord {
        kind: IdentityKind::AnalysisAttemptId,
        canonical_type: "lsp refresh generation echoed as snapshot_id (not #1602 handle)",
        owner_path: "crates/ripr/src/lsp/agent_protocol.rs",
        owner_issue: "#1603/#1765/#4807",
        portability: PortabilityClass::SessionBound,
        semantic_inputs: &["refresh_generation", "accepted_request_identity"],
        volatile_excluded: &[
            "timestamp",
            "pid",
            "client_name",
            "display",
            "markdown",
            "absolute_checkout",
        ],
        parents: &[],
        children: &[],
        invalidation: "A new accepted refresh. Scheduler coalescing must not mint a completed snapshot handle.",
        persistence: "Must not be stored where CompletedAnalysisSnapshotId is required. snapshot_handles remains false until #1602.",
        serialization: &[
            field(
                "snapshot_id",
                FieldRole::Canonical,
                AGENT_REQUEST,
                FieldVisibility::Public,
                Some(
                    "do not read as #1602 immutable snapshot handle; removal when CompletedAnalysisSnapshotId occupies the handle slot",
                ),
            ),
            field(
                "snapshot_id",
                FieldRole::Canonical,
                AGENT_SUCCESS,
                FieldVisibility::Public,
                Some(
                    "do not read as #1602 immutable snapshot handle; removal when CompletedAnalysisSnapshotId occupies the handle slot",
                ),
            ),
            field(
                "snapshot_id",
                FieldRole::Canonical,
                AGENT_ERROR,
                FieldVisibility::Public,
                Some(
                    "do not read as #1602 immutable snapshot handle; removal when CompletedAnalysisSnapshotId occupies the handle slot",
                ),
            ),
            field(
                "snapshot_id",
                FieldRole::Canonical,
                ACTION_CONTRACT,
                FieldVisibility::Public,
                Some("nested evidence_identity.snapshot_id echoes refresh generation, not #1602"),
            ),
            field(
                "evidence_identity",
                FieldRole::Component,
                ACTION_CONTRACT,
                FieldVisibility::Public,
                None,
            ),
        ],
        competing_wrappers: &[
            "agent snapshot_id currently echoes refresh generation, not CompletedAnalysisSnapshotId",
        ],
    },
    IdentityRecord {
        kind: IdentityKind::CompletedAnalysisSnapshotId,
        canonical_type: "analysis_outcome::AnalysisIdentity.snapshot_identity",
        owner_path: "crates/ripr/src/analysis_outcome.rs",
        owner_issue: "#1765/#1602/#4807",
        portability: PortabilityClass::SnapshotBound,
        semantic_inputs: &["completed_analysis_inputs", "result_commitment"],
        volatile_excluded: VOLATILE_COMMON,
        parents: &[IdentityKind::InputIdentity],
        children: &[
            IdentityKind::InstructionInstanceId,
            IdentityKind::DiagnosticResultId,
            IdentityKind::ContinuationId,
            IdentityKind::FeedbackReceiptId,
        ],
        invalidation: "Any completed-analysis input or result commitment change. Request order and scheduler generation do not define this id.",
        persistence: "The immutable handle. Never accept AnalysisAttemptId in this slot.",
        serialization: &[field(
            "snapshot_identity",
            FieldRole::Canonical,
            CHECK_SCHEMA,
            FieldVisibility::Public,
            None,
        )],
        competing_wrappers: &[
            "agent protocol snapshot_id is not this identity while snapshot_handles is false",
        ],
    },
    IdentityRecord {
        kind: IdentityKind::InputIdentity,
        canonical_type: "lsp::input_identity::LspAnalysisInputIdentity",
        owner_path: "crates/ripr/src/lsp/input_identity.rs",
        owner_issue: "#1642/#1671/#2000/#4804",
        portability: PortabilityClass::RepositoryBound,
        semantic_inputs: &[
            "repository_config_identity",
            "session_options_identity",
            "requested_base",
            "resolved_base",
            "mode",
            "profile",
            "enabled_languages",
            "manifest_identity",
            "lockfile_identity",
            "analyzer_version",
            "schema_version",
            "saved_workspace_revision",
        ],
        volatile_excluded: &[
            "timestamp",
            "pid",
            "client_name",
            "display",
            "markdown",
            "scheduler_generation",
        ],
        parents: &[],
        children: &[IdentityKind::CompletedAnalysisSnapshotId],
        invalidation: "Any listed semantic input change. Absolute checkout spelling is recorded separately as root_identity containment evidence.",
        persistence: "Session/analysis input identity. Equivalent sources in a different checkout are a different InputIdentity while portable CanonicalItemId can remain stable.",
        serialization: &[
            field(
                "input_identity",
                FieldRole::Canonical,
                AGENT_SUCCESS,
                FieldVisibility::Public,
                None,
            ),
            field(
                "input_identity",
                FieldRole::Canonical,
                CHECK_SCHEMA,
                FieldVisibility::Public,
                None,
            ),
            field(
                "input_identity",
                FieldRole::Canonical,
                ACTION_CONTRACT,
                FieldVisibility::Public,
                None,
            ),
            field(
                "root_identity",
                FieldRole::Component,
                AGENT_SUCCESS,
                FieldVisibility::Public,
                None,
            ),
            field(
                "root_identity",
                FieldRole::Component,
                CHECK_SCHEMA,
                FieldVisibility::Public,
                None,
            ),
            field(
                "root_identity",
                FieldRole::Component,
                REPAIR_ASSURANCE,
                FieldVisibility::Public,
                None,
            ),
            field(
                "config_identity",
                FieldRole::Component,
                AGENT_SUCCESS,
                FieldVisibility::Public,
                None,
            ),
            field(
                "config_identity",
                FieldRole::Component,
                CHECK_SCHEMA,
                FieldVisibility::Public,
                None,
            ),
            field(
                "base_identity",
                FieldRole::Component,
                AGENT_SUCCESS,
                FieldVisibility::Public,
                None,
            ),
            field(
                "repository_identity",
                FieldRole::Component,
                CHECK_SCHEMA,
                FieldVisibility::Public,
                None,
            ),
        ],
        competing_wrappers: &[
            "LspAnalysisInputIdentity::stable_id currently fingerprints effective_root; that is repository-bound containment, not a portable semantic input",
        ],
    },
    IdentityRecord {
        kind: IdentityKind::DiagnosticResultId,
        canonical_type: "lsp::diagnostics::DiagnosticResultIdCache",
        owner_path: "crates/ripr/src/lsp/diagnostics.rs",
        owner_issue: "#1565/#1566/#4807",
        portability: PortabilityClass::TransportBound,
        semantic_inputs: &[
            "completed_snapshot",
            "document_uri",
            "normalized_payload",
            "delivery_selection",
        ],
        volatile_excluded: VOLATILE_COMMON,
        parents: &[IdentityKind::CompletedAnalysisSnapshotId],
        children: &[],
        invalidation: "Snapshot, document, delivery selection, or diagnostic payload change.",
        persistence: "Pull/push diagnostics transport only. Must never become CanonicalItemId.",
        serialization: &[
            field(
                "document_id",
                FieldRole::Canonical,
                DIAGNOSTICS,
                FieldVisibility::Private,
                None,
            ),
            field(
                "workspace_id",
                FieldRole::Canonical,
                DIAGNOSTICS,
                FieldVisibility::Private,
                None,
            ),
        ],
        competing_wrappers: &[
            "action_data diagnostic_id is DiagnosticCodeId, not this result identity",
        ],
    },
    IdentityRecord {
        kind: IdentityKind::DiagnosticCodeId,
        canonical_type: "LSP Diagnostic.code / diagnostic data diagnostic_id",
        owner_path: "crates/ripr/src/lsp/action_contract.rs",
        owner_issue: "#1892/#4804 (distinct from DiagnosticResultId)",
        portability: PortabilityClass::TransportBound,
        semantic_inputs: &["diagnostic_code"],
        volatile_excluded: VOLATILE_COMMON,
        parents: &[],
        children: &[],
        invalidation: "Diagnostic code change. Result-id payload digest must not be substituted.",
        persistence: "Code-action payload only.",
        serialization: &[field(
            "diagnostic_id",
            FieldRole::Canonical,
            ACTION_CONTRACT,
            FieldVisibility::Public,
            None,
        )],
        competing_wrappers: &[
            "DiagnosticResultIdCache document/workspace ids are a different identity",
        ],
    },
    IdentityRecord {
        kind: IdentityKind::ContinuationId,
        canonical_type: "(request continuation_id / success continuation_identity; typed wrapper is #4807)",
        owner_path: "crates/ripr/src/lsp/agent_protocol.rs",
        owner_issue: "#1603/#1899/#4807",
        portability: PortabilityClass::TransportBound,
        semantic_inputs: &["snapshot", "profile", "budget", "page_order"],
        volatile_excluded: &[
            "timestamp",
            "pid",
            "client_name",
            "display",
            "markdown",
            "absolute_checkout",
        ],
        parents: &[IdentityKind::CompletedAnalysisSnapshotId],
        children: &[],
        invalidation: "Snapshot, profile, budget, or page-order change.",
        persistence: "Page token only. Must not become CanonicalItemId.",
        serialization: &[
            field(
                "continuation_id",
                FieldRole::Canonical,
                AGENT_REQUEST,
                FieldVisibility::Public,
                None,
            ),
            field(
                "continuation_identity",
                FieldRole::CompatibilityAlias,
                AGENT_SUCCESS,
                FieldVisibility::Public,
                Some("unify on ContinuationId during #4807 typed migration"),
            ),
            field(
                "budget_identity",
                FieldRole::Component,
                AGENT_SUCCESS,
                FieldVisibility::Public,
                None,
            ),
            field(
                "complete_evidence_identity",
                FieldRole::Component,
                AGENT_SUCCESS,
                FieldVisibility::Public,
                None,
            ),
        ],
        competing_wrappers: &[
            "continuation_id and continuation_identity are one authority with two wire names",
        ],
    },
    IdentityRecord {
        kind: IdentityKind::CommandId,
        canonical_type: "domain::command_spec::CommandSpec.command_id",
        owner_path: "crates/ripr/src/domain/command_spec.rs",
        owner_issue: "#1617/#1754/#4808",
        portability: PortabilityClass::Portable,
        semantic_inputs: &[
            "command_id",
            "program",
            "args",
            "role",
            "execution_mode",
            "policies",
        ],
        volatile_excluded: &[
            "human_display",
            "display",
            "timestamp",
            "pid",
            "client_name",
            "markdown",
            "absolute_checkout",
        ],
        parents: &[],
        children: &[IdentityKind::ActionId, IdentityKind::ReceiptId],
        invalidation: "Semantic argv, role, or policy change. Display-string-only changes must not.",
        persistence: "May be persisted as a route name. Display text is never reconstructive authority.",
        serialization: &[
            field(
                "command_id",
                FieldRole::Canonical,
                COMMAND_SPEC,
                FieldVisibility::Public,
                None,
            ),
            field(
                "command_id",
                FieldRole::Canonical,
                REPAIR_ASSURANCE,
                FieldVisibility::Public,
                None,
            ),
        ],
        competing_wrappers: &["legacy verify/receipt display strings are not CommandId"],
    },
    IdentityRecord {
        kind: IdentityKind::RepairAttemptId,
        canonical_type: "app::repair_attempt::RepairAttemptId",
        owner_path: "crates/ripr/src/app/repair_attempt.rs",
        owner_issue: "#2927/#3511/#4808",
        portability: PortabilityClass::RepositoryBound,
        semantic_inputs: &["durable_attempt_nonce"],
        volatile_excluded: VOLATILE_COMMON,
        parents: &[],
        children: &[IdentityKind::ReceiptId],
        invalidation: "A new reserved attempt directory. May span several completed snapshots. Must not alias AnalysisAttemptId or CompletedAnalysisSnapshotId.",
        persistence: "The durable repair transaction. Repository-global latest-receipt files are compatibility projections of this attempt.",
        serialization: &[
            field(
                "repair_attempt_id",
                FieldRole::Canonical,
                REPAIR_ATTEMPT,
                FieldVisibility::Public,
                None,
            ),
            field(
                "attempt_id",
                FieldRole::CompatibilityAlias,
                REPAIR_ATTEMPT,
                FieldVisibility::Public,
                Some(
                    "after.attempt_id is the same RepairAttemptId; do not treat as AnalysisAttemptId",
                ),
            ),
        ],
        competing_wrappers: &[
            "feedback ResultIdentity.attempt_id is a caller-supplied reference slot, not this authority",
        ],
    },
    IdentityRecord {
        kind: IdentityKind::ReceiptId,
        canonical_type: "(agent/repair evidence receipt; typed wrapper is #4808)",
        owner_path: "crates/ripr/src/app/repair_attempt.rs",
        owner_issue: "#1941/#4808",
        portability: PortabilityClass::SnapshotBound,
        semantic_inputs: &[
            "exact_heads",
            "command_id",
            "proof_identity",
            "movement_facts",
        ],
        volatile_excluded: VOLATILE_COMMON,
        parents: &[IdentityKind::RepairAttemptId, IdentityKind::CommandId],
        children: &[],
        invalidation: "Exact head, command/proof identity, or movement-fact change.",
        persistence: "Evidence of one before/after attempt. Must not be confused with FeedbackReceiptId.",
        serialization: &[],
        competing_wrappers: &["feedback receipt_id is FeedbackReceiptId on a different surface"],
    },
    IdentityRecord {
        kind: IdentityKind::FeedbackReceiptId,
        canonical_type: "domain::feedback::FeedbackReceipt.feedback_id / identity.receipt_id",
        owner_path: "crates/ripr/src/domain/feedback.rs",
        owner_issue: "#4585/#4804 (same field name as repair ReceiptId; different authority)",
        portability: PortabilityClass::SnapshotBound,
        semantic_inputs: &["snapshot_id", "canonical_item", "route_digest", "judgment"],
        volatile_excluded: &[
            "recorded_at",
            "timestamp",
            "pid",
            "client_name",
            "display",
            "markdown",
        ],
        parents: &[IdentityKind::CompletedAnalysisSnapshotId],
        children: &[],
        invalidation: "Referenced snapshot or judgment identity change. Timestamp is outside payload identity.",
        persistence: "Local usefulness receipt only. Never a repair-evidence ReceiptId.",
        serialization: &[
            field(
                "receipt_id",
                FieldRole::Canonical,
                FEEDBACK,
                FieldVisibility::Public,
                None,
            ),
            field(
                "snapshot_id",
                FieldRole::Component,
                FEEDBACK,
                FieldVisibility::Public,
                None,
            ),
        ],
        competing_wrappers: &[
            "repair ReceiptId is a different identity that must not share this surface's receipt_id meaning",
        ],
    },
];

pub(crate) const ADJACENT_FIELDS: &[AdjacentField] = &[
    AdjacentField {
        name: "diff_identity",
        surfaces: &[CHECK_SCHEMA],
        reason: "Git candidate diff digest (#3278); not an agentic-LSP item/instruction/action identity",
    },
    AdjacentField {
        name: "registration_id",
        surfaces: &[CHECK_SCHEMA],
        reason: "Test harness registration identity; not a CanonicalItemId",
    },
    AdjacentField {
        name: "before_artifact_identity",
        surfaces: &[REPAIR_ASSURANCE],
        reason: "Repair artifact digest identity; tracked so the scanner cannot treat it as a new taxonomy id",
    },
    AdjacentField {
        name: "after_artifact_identity",
        surfaces: &[REPAIR_ASSURANCE],
        reason: "Repair artifact digest identity; tracked so the scanner cannot treat it as a new taxonomy id",
    },
    AdjacentField {
        name: "attempt_id",
        surfaces: &[FEEDBACK],
        reason: "Caller-supplied feedback --attempt slot; must not collapse RepairAttemptId and AnalysisAttemptId",
    },
    AdjacentField {
        name: "feedback_id",
        surfaces: &[FEEDBACK],
        reason: "Idempotency/store key for a usefulness receipt, not ReceiptId",
    },
];

pub(crate) fn production_records() -> &'static [IdentityRecord] {
    PRODUCTION_RECORDS
}

pub(crate) fn adjacent_fields() -> &'static [AdjacentField] {
    ADJACENT_FIELDS
}

#[cfg(test)]
pub(crate) const fn test_field(
    name: &'static str,
    role: FieldRole,
    surface: &'static str,
) -> SerializationField {
    field(name, role, surface, FieldVisibility::Public, None)
}

#[cfg(test)]
pub(crate) const fn test_field_private(
    name: &'static str,
    role: FieldRole,
    surface: &'static str,
) -> SerializationField {
    field(name, role, surface, FieldVisibility::Private, None)
}
