/**
 * Release-admitted distribution descriptors for managed server downloads
 * (#3798).
 *
 * GENERATED by `cargo xtask release-server-manifest` from the built
 * distribution; the release cut commits the refresh before the extension is
 * packaged. One raw-byte manifest SHA-256 per distribution generation admits
 * both the exact stable placement and the one predeclared exact RC placement,
 * because a generation's manifest bytes are placement-neutral and identical
 * on both placements.
 *
 * A generation without an admitted descriptor has no fallback row: stable
 * absence stays terminal and no RC manifest is fetched (#3798, control 7).
 * Never edit a digest by hand — regenerate the module from the built
 * distribution so the digest names real manifest bytes.
 */
export interface ServerDistributionDescriptor {
  /** Distribution generation, e.g. `0.11.0`: no prerelease or build metadata. */
  readonly generation: string;
  /**
   * Raw-byte SHA-256 of the generation's
   * `ripr-server-manifest-v<generation>.json` as published to both placements.
   */
  readonly manifestSha256: string;
}

export const SERVER_DISTRIBUTION_DESCRIPTORS: readonly ServerDistributionDescriptor[] = [];
