//! `cargo xtask perl-migration-refresh` — the maintainer-only refresh oracle
//! for the Perl real-producer contract corpus (issue #3217, RIPR-SPEC-0064).
//!
//! The corpus at `fixtures/perl_packet_contract_migration/corpus.json` pins
//! packets generated by the real `perl-ripr-facts` producer at a pinned
//! commit, together with the accepted contradiction and consumer-disposition
//! records. This command re-runs each pinned producer command with a
//! maintainer-supplied producer binary, writes the candidate packet under
//! `target/ripr/reports/perl-migration-candidates/`, and emits a typed drift
//! report per case comparing the candidate against the accepted golden.
//!
//! Boundaries:
//!
//! - Advisory only: detected drift never fails the command (exit 0); the
//!   report is the artifact. Only a failed producer run, an unreadable
//!   corpus, or bad arguments fail.
//! - It never writes under `fixtures/`: the accepted golden packet and the
//!   contradiction/disposition records are read-only inputs. Candidates and
//!   drift reports land under `target/`.
//! - Promotion is a reviewed manual act; this command never rewrites
//!   accepted evidence.
//!
//! Subprocess execution goes through the single process-allowlisted surface
//! (`crate::run::capture_output_in_dir`); this file has no direct
//! `std::process::Command` use (see `cargo xtask check-process-policy`).

use super::write_parented_file;
use crate::run::capture_output_in_dir;
use serde_json::{Value, json};
use sha2::{Digest, Sha256};
use std::path::Path;

const CORPUS_PATH: &str = "fixtures/perl_packet_contract_migration/corpus.json";
const CANDIDATE_DIR: &str = "target/ripr/reports/perl-migration-candidates";
const REFRESH_KIND: &str = "perl_packet_contract_migration_refresh";
const REFRESH_SCHEMA_VERSION: &str = "0.1";
const OUT_PLACEHOLDER: &str = "<out>";
const PROMOTION_NOTE: &str = "manual: update corpus.json packet_sha256, expected/contradictions.v1.json and expected/consumer-dispositions.v1.json in a reviewed PR; this command never rewrites accepted evidence";
const USAGE: &str = "usage: cargo xtask perl-migration-refresh --producer-bin <path> [--case <id>]";
const HELP: &str = "usage: cargo xtask perl-migration-refresh --producer-bin <path> [--case <id>]

Re-runs the pinned perl_packet_contract_migration producer command with the
supplied producer binary and writes, per case, a candidate packet plus a
typed drift report under target/ripr/reports/perl-migration-candidates/.
The drift report compares packet-shaped properties (ids, fingerprints,
digests, owners, changes, oracles, relations, limitations, provenance
range shapes) between the pinned golden packet and the fresh candidate.

The command is advisory: drift never fails it (exit 0); the report is the
artifact. It never writes under fixtures/ — the accepted golden packet and
the contradiction/consumer-disposition records are read-only inputs.
Promotion is a reviewed manual act.";

pub(crate) fn perl_migration_refresh(args: &[String]) -> Result<(), String> {
    if args.iter().any(|arg| arg == "--help" || arg == "-h") {
        println!("{HELP}");
        return Ok(());
    }
    let options = parse_options(args)?;
    if !Path::new(&options.producer_bin).is_file() {
        return Err(format!(
            "--producer-bin `{}` does not exist as a file; {USAGE}",
            options.producer_bin
        ));
    }
    let corpus_text = std::fs::read_to_string(CORPUS_PATH)
        .map_err(|err| format!("failed to read perl migration corpus {CORPUS_PATH}: {err}"))?;
    let cases = parse_corpus(&corpus_text)?;
    let selected: Vec<&CorpusCase> = match &options.case {
        Some(wanted) => {
            let matched: Vec<&CorpusCase> =
                cases.iter().filter(|case| case.id == *wanted).collect();
            if matched.is_empty() {
                let known = cases
                    .iter()
                    .map(|case| case.id.as_str())
                    .collect::<Vec<_>>()
                    .join(", ");
                return Err(format!(
                    "unknown --case `{wanted}`; corpus cases: {known}; {USAGE}"
                ));
            }
            matched
        }
        None => cases.iter().collect(),
    };
    std::fs::create_dir_all(CANDIDATE_DIR)
        .map_err(|err| format!("failed to create candidate directory {CANDIDATE_DIR}: {err}"))?;

    let mut failures: Vec<String> = Vec::new();
    for case in &selected {
        match refresh_case(case, &options.producer_bin) {
            Ok(outcome) => {
                println!(
                    "case {}: candidate {} byte_identical={} drift={}",
                    case.id, outcome.candidate_path, outcome.byte_identical, outcome.drift_count
                );
                println!("case {}: drift report {}", case.id, outcome.drift_path);
            }
            Err(err) => {
                println!("case {}: FAILED: {err}", case.id);
                failures.push(format!("case {}: {err}", case.id));
            }
        }
    }
    println!(
        "perl-migration-refresh is advisory: drift never fails this command; promotion is a reviewed manual act — {PROMOTION_NOTE}"
    );
    if failures.is_empty() {
        Ok(())
    } else {
        Err(failures.join("\n"))
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct PerlMigrationOptions {
    producer_bin: String,
    case: Option<String>,
}

fn parse_options(args: &[String]) -> Result<PerlMigrationOptions, String> {
    let mut options = PerlMigrationOptions {
        producer_bin: String::new(),
        case: None,
    };
    let mut index = 0usize;
    while index < args.len() {
        match args[index].as_str() {
            "--producer-bin" => {
                index += 1;
                options.producer_bin = option_value(args, index, "--producer-bin")?.to_string();
            }
            "--case" => {
                index += 1;
                options.case = Some(option_value(args, index, "--case")?.to_string());
            }
            other => {
                return Err(format!(
                    "unknown perl-migration-refresh argument `{other}`; {USAGE}"
                ));
            }
        }
        index += 1;
    }
    if options.producer_bin.is_empty() {
        return Err(format!("missing required --producer-bin <path>; {USAGE}"));
    }
    Ok(options)
}

fn option_value<'a>(args: &'a [String], index: usize, flag: &str) -> Result<&'a str, String> {
    let Some(value) = args.get(index) else {
        return Err(format!("missing value for {flag}; {USAGE}"));
    };
    if value.trim().is_empty() {
        return Err(format!(
            "perl-migration-refresh {flag} requires a non-empty value; {USAGE}"
        ));
    }
    Ok(value)
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct CorpusCase {
    id: String,
    producer_commit: String,
    producer_binary_name: String,
    producer_command: String,
    packet: String,
    packet_sha256: String,
}

fn parse_corpus(text: &str) -> Result<Vec<CorpusCase>, String> {
    let value: Value = serde_json::from_str(text)
        .map_err(|err| format!("failed to parse perl migration corpus {CORPUS_PATH}: {err}"))?;
    let cases = value
        .get("cases")
        .and_then(Value::as_array)
        .ok_or_else(|| format!("corpus {CORPUS_PATH} is missing a `cases` array"))?;
    cases.iter().map(parse_corpus_case).collect()
}

fn parse_corpus_case(value: &Value) -> Result<CorpusCase, String> {
    let id = required_str(value, "id")?;
    let producer = value
        .get("producer")
        .ok_or_else(|| format!("corpus case `{id}` is missing `producer`"))?;
    Ok(CorpusCase {
        id: id.to_string(),
        producer_commit: required_str(producer, "commit")?.to_string(),
        producer_binary_name: required_str(producer, "binary")?.to_string(),
        producer_command: required_str(value, "producer_command")?.to_string(),
        packet: required_str(value, "packet")?.to_string(),
        packet_sha256: required_str(value, "packet_sha256")?.to_string(),
    })
}

fn required_str<'a>(value: &'a Value, key: &str) -> Result<&'a str, String> {
    value
        .get(key)
        .and_then(Value::as_str)
        .ok_or_else(|| format!("corpus object is missing string field `{key}`"))
}

/// Builds the producer argv for one case: the leading pinned program token
/// becomes the supplied producer binary and the `--out <out>` placeholder
/// becomes the candidate path under `target/` (never under `fixtures/`).
fn build_producer_invocation(
    producer_bin: &str,
    case: &CorpusCase,
    candidate_out: &str,
) -> Result<Vec<String>, String> {
    let mut tokens: Vec<String> = case
        .producer_command
        .split_whitespace()
        .map(str::to_string)
        .collect();
    if tokens.first().map(String::as_str) != Some(case.producer_binary_name.as_str()) {
        return Err(format!(
            "producer_command must start with the pinned producer binary `{}`",
            case.producer_binary_name
        ));
    }
    tokens[0] = producer_bin.to_string();
    let out_flag_index = tokens
        .iter()
        .position(|token| token == "--out")
        .ok_or_else(|| format!("producer_command is missing `--out {OUT_PLACEHOLDER}`"))?;
    let placeholder = tokens.get(out_flag_index + 1).ok_or_else(|| {
        format!("producer_command `--out` is missing its `{OUT_PLACEHOLDER}` placeholder")
    })?;
    if placeholder != OUT_PLACEHOLDER {
        return Err(format!(
            "producer_command `--out` value must be the `{OUT_PLACEHOLDER}` placeholder, found `{placeholder}`"
        ));
    }
    tokens[out_flag_index + 1] = candidate_out.to_string();
    Ok(tokens)
}

struct CaseOutcome {
    candidate_path: String,
    drift_path: String,
    byte_identical: bool,
    drift_count: usize,
}

fn refresh_case(case: &CorpusCase, producer_bin: &str) -> Result<CaseOutcome, String> {
    let candidate_path = format!("{CANDIDATE_DIR}/{}.json", case.id);
    let drift_path = format!("{CANDIDATE_DIR}/{}.drift.json", case.id);
    let argv = build_producer_invocation(producer_bin, case, &candidate_path)?;
    // `argv[0]` is the producer program token; the runner takes it separately
    // from the argument list.
    let program = argv
        .first()
        .ok_or_else(|| format!("case {}: producer argv is empty", case.id))?;
    let args: Vec<String> = argv.iter().skip(1).cloned().collect();
    let cwd = std::env::current_dir()
        .map_err(|err| format!("failed to resolve the current directory: {err}"))?;
    let output = capture_output_in_dir(
        program,
        &args,
        &cwd,
        &format!("perl-migration-refresh producer for case {}", case.id),
    )?;
    if !output.status.success() {
        return Err(format!(
            "producer exited with {}; stdout: {}; stderr: {}",
            output.status,
            output.stdout.trim(),
            output.stderr.trim()
        ));
    }
    let candidate_bytes = std::fs::read(&candidate_path).map_err(|err| {
        format!(
            "case {}: failed to read candidate packet {candidate_path}: {err}",
            case.id
        )
    })?;
    let pinned_bytes = std::fs::read(&case.packet).map_err(|err| {
        format!(
            "case {}: failed to read pinned packet {}: {err}",
            case.id, case.packet
        )
    })?;
    let report = build_report(
        case,
        producer_bin,
        &candidate_path,
        &pinned_bytes,
        &candidate_bytes,
    )?;
    let report_text = serde_json::to_string_pretty(&report.value)
        .map_err(|err| format!("case {}: failed to serialize drift report: {err}", case.id))?;
    write_parented_file(
        Path::new(&drift_path),
        &format!("case {} drift report", case.id),
        format!("{report_text}\n").as_bytes(),
    )?;
    Ok(CaseOutcome {
        candidate_path,
        drift_path,
        byte_identical: report.byte_identical,
        drift_count: report.drift_count,
    })
}

struct CaseReport {
    value: Value,
    byte_identical: bool,
    drift_count: usize,
}

fn build_report(
    case: &CorpusCase,
    producer_bin: &str,
    candidate_path: &str,
    pinned_bytes: &[u8],
    candidate_bytes: &[u8],
) -> Result<CaseReport, String> {
    let pinned_packet: Value = serde_json::from_slice(pinned_bytes).map_err(|err| {
        format!(
            "case {}: pinned packet {} is not valid JSON: {err}",
            case.id, case.packet
        )
    })?;
    let candidate_packet: Value = serde_json::from_slice(candidate_bytes).map_err(|err| {
        format!(
            "case {}: candidate packet {candidate_path} is not valid JSON: {err}",
            case.id
        )
    })?;
    let pinned_observed = extract_observed(&pinned_packet);
    let candidate_observed = extract_observed(&candidate_packet);
    let drift = compute_drift(&pinned_observed, &candidate_observed);
    let byte_identical = pinned_bytes == candidate_bytes;
    Ok(CaseReport {
        value: json!({
            "kind": REFRESH_KIND,
            "schema_version": REFRESH_SCHEMA_VERSION,
            "case_id": case.id,
            "producer_bin": producer_bin,
            "producer_commit_pinned": case.producer_commit,
            "pinned": {
                "packet": case.packet,
                "packet_sha256": case.packet_sha256,
            },
            "candidate": {
                "packet": candidate_path,
                "packet_sha256": sha256_hex(candidate_bytes),
            },
            "byte_identical": byte_identical,
            "observed": candidate_observed,
            "drift": drift,
            "promotion": PROMOTION_NOTE,
        }),
        byte_identical,
        drift_count: drift.len(),
    })
}

fn sha256_hex(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    format!("sha256:{:x}", hasher.finalize())
}

/// Projects one packet onto the contract-relevant property set. The property
/// names double as drift-entry `property` values, so the extraction and the
/// drift comparison stay aligned by construction.
fn extract_observed(packet: &Value) -> Value {
    let scalar = |keys: &[&str]| get_path(packet, keys).cloned().unwrap_or(Value::Null);

    let files_digests: Vec<Value> = packet
        .get("files")
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .filter_map(|item| item.get("digest").cloned())
                .collect()
        })
        .unwrap_or_default();

    let owners: Vec<Value> = packet
        .get("owners")
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .map(|item| {
                    json!({
                        "owner_id": item.get("owner_id").cloned().unwrap_or(Value::Null),
                        "range_start_line": item
                            .get("range")
                            .and_then(|range| range.get("start_line"))
                            .cloned()
                            .unwrap_or(Value::Null),
                    })
                })
                .collect()
        })
        .unwrap_or_default();

    let changes: Vec<Value> = packet
        .get("changes")
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .map(|item| {
                    json!({
                        "change_id": item.get("change_id").cloned().unwrap_or(Value::Null),
                        "changed_text_digest": item
                            .get("changed_text_digest")
                            .cloned()
                            .unwrap_or(Value::Null),
                        "missing_discriminator": item
                            .get("missing_discriminator")
                            .cloned()
                            .unwrap_or(Value::Null),
                        "provenance_refs_len": refs_len(item.get("provenance_refs")),
                    })
                })
                .collect()
        })
        .unwrap_or_default();

    let test_frameworks: Vec<Value> = packet
        .get("tests")
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .filter_map(|item| item.get("framework").cloned())
                .collect()
        })
        .unwrap_or_default();

    let oracles: Vec<Value> = packet
        .get("oracles")
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .map(|item| {
                    json!({
                        "oracle_id": item.get("oracle_id").cloned().unwrap_or(Value::Null),
                        "kind": item.get("kind").cloned().unwrap_or(Value::Null),
                        "strength": item.get("strength").cloned().unwrap_or(Value::Null),
                        "target_owner_id": item
                            .get("target_owner_id")
                            .cloned()
                            .unwrap_or(Value::Null),
                        "has_observed_sink": is_present(item.get("observed_sink")),
                        "has_expected_expression": is_present(item.get("expected_expression")),
                    })
                })
                .collect()
        })
        .unwrap_or_default();

    let relations: Vec<Value> = packet
        .get("relations")
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .map(|item| {
                    json!({
                        "relation_kind": item.get("relation_kind").cloned().unwrap_or(Value::Null),
                        "reachability_hint": item
                            .get("reachability_hint")
                            .cloned()
                            .unwrap_or(Value::Null),
                        "provenance_refs_len": refs_len(item.get("provenance_refs")),
                    })
                })
                .collect()
        })
        .unwrap_or_default();

    let limitation_kinds: Vec<Value> = packet
        .get("limitations")
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .filter_map(|item| item.get("kind").cloned())
                .collect()
        })
        .unwrap_or_default();

    let provenance: Vec<Value> = packet
        .get("provenance")
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .map(|item| {
                    json!({
                        "provenance_id": item.get("provenance_id").cloned().unwrap_or(Value::Null),
                        "range_shape": range_shape(item.get("range")),
                    })
                })
                .collect()
        })
        .unwrap_or_default();

    json!({
        "schema_version": scalar(&["schema_version"]),
        "packet_status": scalar(&["packet_status"]),
        "packet_id": scalar(&["packet_id"]),
        "packet_fingerprint": scalar(&["packet_fingerprint"]),
        "root.path_style": scalar(&["root", "path_style"]),
        "root.vcs_head": scalar(&["root", "vcs_head"]),
        "producer.name": scalar(&["producer", "name"]),
        "producer.version": scalar(&["producer", "version"]),
        "producer.capabilities": array_at(packet, &["producer", "capabilities"]),
        "input.base": scalar(&["input", "base"]),
        "input.head": scalar(&["input", "head"]),
        "input.diff_id": scalar(&["input", "diff_id"]),
        "files[].digest": files_digests,
        "owners[]": owners,
        "changes[]": changes,
        "tests[].framework": test_frameworks,
        "oracles[]": oracles,
        "relations[]": relations,
        "limitations[].kind": limitation_kinds,
        "provenance[]": provenance,
    })
}

fn get_path<'a>(value: &'a Value, keys: &[&str]) -> Option<&'a Value> {
    let mut current = value;
    for key in keys {
        current = current.get(key)?;
    }
    Some(current)
}

fn array_at(value: &Value, keys: &[&str]) -> Value {
    get_path(value, keys)
        .and_then(Value::as_array)
        .map(|items| Value::Array(items.clone()))
        .unwrap_or_else(|| Value::Array(Vec::new()))
}

fn refs_len(value: Option<&Value>) -> usize {
    value.and_then(Value::as_array).map_or(0, |refs| refs.len())
}

fn is_present(value: Option<&Value>) -> bool {
    value.is_some_and(|item| !item.is_null())
}

/// Classifies a provenance `range` by its JSON shape; the corpus pins the
/// producer's string-shaped ranges as a known consumer contradiction.
fn range_shape(value: Option<&Value>) -> &'static str {
    match value {
        None => "missing",
        Some(Value::Null) => "null",
        Some(Value::String(_)) => "string",
        Some(Value::Object(_)) => "object",
        Some(_) => "other",
    }
}

/// One drift entry per property name whose pinned value differs from the
/// candidate value. `serde_json` object keys iterate in sorted order, so the
/// entries are deterministic.
fn compute_drift(pinned: &Value, candidate: &Value) -> Vec<Value> {
    let mut drift = Vec::new();
    if let Some(properties) = pinned.as_object() {
        for (property, pinned_value) in properties {
            let candidate_value = candidate.get(property).unwrap_or(&Value::Null);
            if pinned_value != candidate_value {
                drift.push(json!({
                    "property": property,
                    "pinned": pinned_value,
                    "candidate": candidate_value,
                }));
            }
        }
    }
    drift
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn help_flag_prints_usage_and_returns_ok() -> Result<(), String> {
        // `--help` must succeed without touching the corpus, the producer
        // binary, or the filesystem.
        perl_migration_refresh(&["--help".to_string()])?;
        perl_migration_refresh(&["-h".to_string()])?;
        if !HELP.starts_with("usage: cargo xtask perl-migration-refresh") {
            return Err(format!("help should open with the usage line: {HELP}"));
        }
        for expected in ["--producer-bin", "--case", "never writes under fixtures/"] {
            if !HELP.contains(expected) {
                return Err(format!("help should mention {expected}: {HELP}"));
            }
        }
        Ok(())
    }

    #[test]
    fn parse_options_requires_producer_bin() -> Result<(), String> {
        let Err(err) = parse_options(&[]) else {
            return Err("missing --producer-bin should fail".to_string());
        };
        if !err.contains("missing required --producer-bin") || !err.contains(USAGE) {
            return Err(format!("missing-bin error should carry usage: {err}"));
        }
        Ok(())
    }

    #[test]
    fn parse_options_rejects_unknown_flags() -> Result<(), String> {
        let Err(err) = parse_options(&["--bogus".to_string()]) else {
            return Err("unknown flag should fail".to_string());
        };
        if !err.contains("--bogus") || !err.contains(USAGE) {
            return Err(format!("unknown-flag error should carry usage: {err}"));
        }
        Ok(())
    }

    #[test]
    fn parse_options_rejects_missing_flag_values() -> Result<(), String> {
        for args in [
            vec!["--producer-bin".to_string()],
            vec![
                "--producer-bin".to_string(),
                "bin".to_string(),
                "--case".to_string(),
            ],
        ] {
            let Err(err) = parse_options(&args) else {
                return Err("missing flag value should fail".to_string());
            };
            if !err.contains("missing value for") {
                return Err(format!("missing-value error should be named: {err}"));
            }
        }
        Ok(())
    }

    #[test]
    fn parse_options_parses_producer_bin_and_case() -> Result<(), String> {
        let options = parse_options(&["--producer-bin".to_string(), "bin".to_string()])?;
        if options.producer_bin != "bin" || options.case.is_some() {
            return Err(format!("unexpected default options: {options:?}"));
        }
        let selected = parse_options(&[
            "--case".to_string(),
            "ordinary_discount".to_string(),
            "--producer-bin".to_string(),
            "perl-ripr-facts.exe".to_string(),
        ])?;
        if selected.case.as_deref() != Some("ordinary_discount") {
            return Err(format!("--case should be recorded: {selected:?}"));
        }
        Ok(())
    }

    #[test]
    fn entry_rejects_missing_producer_binary_file() -> Result<(), String> {
        // The existence check runs before the corpus read, so a bad
        // `--producer-bin` fails cleanly without touching fixtures.
        let missing = format!(
            "target/ripr/reports/perl-migration-candidates/missing-producer-{}.bin",
            std::process::id()
        );
        let Err(err) = perl_migration_refresh(&["--producer-bin".to_string(), missing]) else {
            return Err("nonexistent producer binary should fail".to_string());
        };
        if !err.contains("does not exist as a file") || !err.contains(USAGE) {
            return Err(format!("missing-binary error should carry usage: {err}"));
        }
        Ok(())
    }

    fn sample_case() -> CorpusCase {
        CorpusCase {
            id: "ordinary_discount".to_string(),
            producer_commit: "a9664af790888333efbe50a042fa060f3cc2d171".to_string(),
            producer_binary_name: "perl-ripr-facts".to_string(),
            producer_command: "perl-ripr-facts ripr-facts --schema ripr-perl-facts-v1 --root fixtures/ordinary_discount --base origin/main --head HEAD --diff fixtures/ordinary_discount/diff.patch --out <out>".to_string(),
            packet: "fixtures/perl_packet_contract_migration/producer-packets/v1/ordinary_discount.json".to_string(),
            packet_sha256: "sha256:0cc8f4bb".to_string(),
        }
    }

    #[test]
    fn producer_invocation_replaces_program_and_out_placeholder() -> Result<(), String> {
        let argv = build_producer_invocation(
            "bin/perl-ripr-facts.exe",
            &sample_case(),
            "target/ripr/reports/perl-migration-candidates/ordinary_discount.json",
        )?;
        if argv[0] != "bin/perl-ripr-facts.exe" {
            return Err(format!(
                "leading token should be the supplied binary: {argv:?}"
            ));
        }
        let out_index = argv
            .iter()
            .position(|token| token == "--out")
            .ok_or_else(|| format!("argv should keep --out: {argv:?}"))?;
        let out_value = argv
            .get(out_index + 1)
            .ok_or_else(|| format!("--out should keep a value: {argv:?}"))?;
        if out_value != "target/ripr/reports/perl-migration-candidates/ordinary_discount.json" {
            return Err(format!("--out placeholder should be replaced: {argv:?}"));
        }
        if argv.iter().any(|token| token == OUT_PLACEHOLDER) {
            return Err(format!("no placeholder token should remain: {argv:?}"));
        }
        Ok(())
    }

    #[test]
    fn producer_invocation_rejects_wrong_program_and_bad_placeholder() -> Result<(), String> {
        let mut wrong_program = sample_case();
        wrong_program.producer_command = "other-producer ripr-facts --out <out>".to_string();
        let Err(program_err) = build_producer_invocation("bin", &wrong_program, "target/out.json")
        else {
            return Err("wrong leading program should fail".to_string());
        };
        if !program_err.contains("perl-ripr-facts") {
            return Err(format!(
                "program error should name the pinned binary: {program_err}"
            ));
        }

        let mut bad_placeholder = sample_case();
        bad_placeholder.producer_command = "perl-ripr-facts ripr-facts --out real.json".to_string();
        let Err(placeholder_err) =
            build_producer_invocation("bin", &bad_placeholder, "target/out.json")
        else {
            return Err("non-placeholder --out value should fail".to_string());
        };
        if !placeholder_err.contains(OUT_PLACEHOLDER) {
            return Err(format!(
                "placeholder error should name the placeholder: {placeholder_err}"
            ));
        }

        let mut no_out = sample_case();
        no_out.producer_command = "perl-ripr-facts ripr-facts".to_string();
        let Err(out_err) = build_producer_invocation("bin", &no_out, "target/out.json") else {
            return Err("missing --out should fail".to_string());
        };
        if !out_err.contains("--out") {
            return Err(format!("missing-out error should name --out: {out_err}"));
        }
        Ok(())
    }

    fn sample_packet() -> Value {
        json!({
            "schema_version": "ripr-perl-facts-v1",
            "packet_status": "partial",
            "packet_id": "packet-1",
            "packet_fingerprint": "sha256:addedb4d",
            "root": {"path_style": "posix", "vcs_head": "HEAD"},
            "producer": {
                "name": "perl-lsp",
                "version": "0.17.0",
                "capabilities": ["files", "owners"]
            },
            "input": {"base": "origin/main", "head": "HEAD", "diff_id": null},
            "files": [{"digest": "sha256:aaa"}, {"digest": "sha256:bbb"}],
            "owners": [
                {"owner_id": "owner:pkg", "range": {"start_line": 0}},
                {"owner_id": "owner:sub", "range": {"start_line": 5}}
            ],
            "changes": [{
                "change_id": "change:1",
                "changed_text_digest": "fnv64:abcd",
                "missing_discriminator": null,
                "provenance_refs": []
            }],
            "tests": [{"framework": "Test::More"}],
            "oracles": [
                {
                    "oracle_id": "oracle:1",
                    "kind": "exact_return_assertion",
                    "strength": "strong_exact",
                    "target_owner_id": "owner:sub",
                    "observed_sink": "5  if $amount < 25",
                    "expected_expression": null
                },
                {
                    "oracle_id": "oracle:2",
                    "kind": "exact_return_assertion",
                    "strength": "strong_exact",
                    "target_owner_id": null
                }
            ],
            "relations": [{
                "relation_kind": "direct_owner_call",
                "reachability_hint": "reachable",
                "provenance_refs": ["prov:a"]
            }],
            "limitations": [{"kind": "partial_emitter"}, {"kind": "range_precision"}],
            "provenance": [
                {"provenance_id": "cli-surface"},
                {"provenance_id": "prov:td", "range": "3:0-3:14"},
                {"provenance_id": "prov:oe", "range": null},
                {"provenance_id": "prov:sx", "range": {"start_line": 1}}
            ]
        })
    }

    #[test]
    fn extract_observed_shapes_packet_properties() -> Result<(), String> {
        let observed = extract_observed(&sample_packet());
        let get = |property: &str| {
            observed
                .get(property)
                .ok_or_else(|| format!("observed should carry `{property}`"))
        };

        if get("schema_version")? != "ripr-perl-facts-v1" {
            return Err(format!("schema_version should pass through: {observed}"));
        }
        if !get("input.diff_id")?.is_null() {
            return Err("input.diff_id null should stay null".to_string());
        }
        if get("files[].digest")? != &json!(["sha256:aaa", "sha256:bbb"]) {
            return Err(format!("file digests should be projected: {observed}"));
        }
        if get("owners[]")?
            != &json!([
                {"owner_id": "owner:pkg", "range_start_line": 0},
                {"owner_id": "owner:sub", "range_start_line": 5}
            ])
        {
            return Err(format!(
                "owners should project id plus start line: {observed}"
            ));
        }
        if get("changes[]")?
            != &json!([{
                "change_id": "change:1",
                "changed_text_digest": "fnv64:abcd",
                "missing_discriminator": null,
                "provenance_refs_len": 0
            }])
        {
            return Err(format!(
                "changes should project the shaped record: {observed}"
            ));
        }
        if get("tests[].framework")? != &json!(["Test::More"]) {
            return Err(format!("test frameworks should be projected: {observed}"));
        }
        if get("oracles[]")?
            != &json!([
                {
                    "oracle_id": "oracle:1",
                    "kind": "exact_return_assertion",
                    "strength": "strong_exact",
                    "target_owner_id": "owner:sub",
                    "has_observed_sink": true,
                    "has_expected_expression": false
                },
                {
                    "oracle_id": "oracle:2",
                    "kind": "exact_return_assertion",
                    "strength": "strong_exact",
                    "target_owner_id": null,
                    "has_observed_sink": false,
                    "has_expected_expression": false
                }
            ])
        {
            return Err(format!(
                "oracles should project presence booleans: {observed}"
            ));
        }
        if get("relations[]")?
            != &json!([{
                "relation_kind": "direct_owner_call",
                "reachability_hint": "reachable",
                "provenance_refs_len": 1
            }])
        {
            return Err(format!(
                "relations should project shaped records: {observed}"
            ));
        }
        if get("limitations[].kind")? != &json!(["partial_emitter", "range_precision"]) {
            return Err(format!("limitation kinds should be projected: {observed}"));
        }

        let provenance = get("provenance[]")?;
        let shapes: Vec<&str> = provenance
            .as_array()
            .ok_or_else(|| format!("provenance should be an array: {provenance}"))?
            .iter()
            .filter_map(|item| item.get("range_shape").and_then(Value::as_str))
            .collect();
        if shapes != ["missing", "string", "null", "object"] {
            return Err(format!(
                "range shapes should map string/object/null/absent in order: {shapes:?}"
            ));
        }
        Ok(())
    }

    #[test]
    fn extract_observed_defaults_missing_sections() -> Result<(), String> {
        let observed = extract_observed(&json!({ "schema_version": "ripr-perl-facts-v1" }));
        for property in [
            "packet_status",
            "packet_id",
            "packet_fingerprint",
            "root.path_style",
            "root.vcs_head",
            "producer.name",
            "producer.version",
            "input.base",
            "input.head",
            "input.diff_id",
        ] {
            if !observed.get(property).is_some_and(Value::is_null) {
                return Err(format!("absent `{property}` should extract as null"));
            }
        }
        for property in [
            "producer.capabilities",
            "files[].digest",
            "owners[]",
            "changes[]",
            "tests[].framework",
            "oracles[]",
            "relations[]",
            "limitations[].kind",
            "provenance[]",
        ] {
            if observed.get(property).and_then(Value::as_array).is_none() {
                return Err(format!("absent `{property}` should extract as an array"));
            }
        }
        Ok(())
    }

    #[test]
    fn compute_drift_reports_exactly_the_differing_property() -> Result<(), String> {
        let pinned = json!({"schema_version": "ripr-perl-facts-v1", "packet_status": "partial"});
        let candidate = json!({"schema_version": "ripr-perl-facts-v2", "packet_status": "partial"});
        let drift = compute_drift(&pinned, &candidate);
        let expected = json!([{
            "property": "schema_version",
            "pinned": "ripr-perl-facts-v1",
            "candidate": "ripr-perl-facts-v2"
        }]);
        let expected_entries = expected.as_array().cloned().unwrap_or_default();
        if drift != expected_entries {
            return Err(format!(
                "drift should match the single differing property: {drift:?}"
            ));
        }
        let identical = compute_drift(&pinned, &pinned);
        if !identical.is_empty() {
            return Err(format!(
                "identical observations should produce no drift: {identical:?}"
            ));
        }
        Ok(())
    }

    #[test]
    fn build_report_flags_byte_identity_and_property_drift() -> Result<(), String> {
        let case = sample_case();
        let candidate_path = "target/ripr/reports/perl-migration-candidates/ordinary_discount.json";
        let pinned_bytes = serde_json::to_vec(&sample_packet())
            .map_err(|err| format!("sample serialize: {err}"))?;

        let identical = build_report(
            &case,
            "bin/perl-ripr-facts.exe",
            candidate_path,
            &pinned_bytes,
            &pinned_bytes,
        )?;
        if !identical.byte_identical || identical.drift_count != 0 {
            return Err("identical bytes should mean no drift".to_string());
        }
        let value = &identical.value;
        if value.get("kind").and_then(Value::as_str) != Some(REFRESH_KIND) {
            return Err(format!("report kind should be pinned: {value}"));
        }
        if value.get("schema_version").and_then(Value::as_str) != Some(REFRESH_SCHEMA_VERSION) {
            return Err(format!("report schema_version should be pinned: {value}"));
        }
        if value.get("producer_commit_pinned").and_then(Value::as_str)
            != Some(case.producer_commit.as_str())
        {
            return Err(format!("report should pin the producer commit: {value}"));
        }
        if value.get("promotion").and_then(Value::as_str) != Some(PROMOTION_NOTE) {
            return Err(format!(
                "report should carry the manual promotion note: {value}"
            ));
        }
        let candidate_sha = value
            .get("candidate")
            .and_then(|candidate| candidate.get("packet_sha256"))
            .and_then(Value::as_str)
            .ok_or_else(|| format!("candidate should carry packet_sha256: {value}"))?;
        if candidate_sha != sha256_hex(&pinned_bytes) {
            return Err(format!(
                "candidate sha should be computed from the candidate bytes: {candidate_sha}"
            ));
        }
        let pinned_sha = value
            .get("pinned")
            .and_then(|pinned| pinned.get("packet_sha256"))
            .and_then(Value::as_str)
            .ok_or_else(|| format!("pinned should carry packet_sha256: {value}"))?;
        if pinned_sha != case.packet_sha256 {
            return Err(format!(
                "pinned sha should come from the corpus: {pinned_sha}"
            ));
        }

        let mut drifted_packet = sample_packet();
        drifted_packet["packet_status"] = json!("complete");
        let candidate_bytes = serde_json::to_vec(&drifted_packet)
            .map_err(|err| format!("drifted serialize: {err}"))?;
        let drifted = build_report(
            &case,
            "bin/perl-ripr-facts.exe",
            candidate_path,
            &pinned_bytes,
            &candidate_bytes,
        )?;
        if drifted.byte_identical || drifted.drift_count != 1 {
            return Err("a changed packet_status should be exactly one drift".to_string());
        }
        let entries = drifted
            .value
            .get("drift")
            .and_then(Value::as_array)
            .ok_or_else(|| format!("drift should be an array: {}", drifted.value))?;
        let entry = entries
            .first()
            .ok_or_else(|| format!("drift should have one entry: {}", drifted.value))?;
        if entry.get("property").and_then(Value::as_str) != Some("packet_status")
            || entry.get("pinned").and_then(Value::as_str) != Some("partial")
            || entry.get("candidate").and_then(Value::as_str) != Some("complete")
        {
            return Err(format!(
                "drift entry should name pinned and candidate: {entry}"
            ));
        }
        Ok(())
    }

    #[test]
    fn parse_corpus_parses_minimal_cases() -> Result<(), String> {
        let corpus = r#"{
            "kind": "perl_packet_contract_migration_corpus",
            "schema_version": "0.1",
            "cases": [
                {
                    "id": "ordinary_discount",
                    "producer": {
                        "repository": "EffortlessMetrics/perl-lsp-swarm",
                        "commit": "a9664af790888333efbe50a042fa060f3cc2d171",
                        "version": "0.17.0",
                        "binary": "perl-ripr-facts"
                    },
                    "producer_command": "perl-ripr-facts ripr-facts --out <out>",
                    "packet": "fixtures/perl_packet_contract_migration/producer-packets/v1/ordinary_discount.json",
                    "packet_sha256": "sha256:0cc8f4bb"
                }
            ]
        }"#;
        let cases = parse_corpus(corpus)?;
        let case = cases
            .first()
            .ok_or_else(|| "corpus should parse one case".to_string())?;
        if case.id != "ordinary_discount"
            || case.producer_binary_name != "perl-ripr-facts"
            || case.packet_sha256 != "sha256:0cc8f4bb"
        {
            return Err(format!("case should parse its identity fields: {case:?}"));
        }

        let Err(missing) = parse_corpus(r#"{"cases": [{"id": "x"}]}"#) else {
            return Err("a case without producer fields should fail".to_string());
        };
        if !missing.contains("`producer`") {
            return Err(format!("missing-producer error should be named: {missing}"));
        }

        let Err(no_cases) = parse_corpus(r#"{"kind": "other"}"#) else {
            return Err("a corpus without cases should fail".to_string());
        };
        if !no_cases.contains("cases") {
            return Err(format!(
                "missing-cases error should name `cases`: {no_cases}"
            ));
        }
        Ok(())
    }
}
